import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

let registrations: ReturnType<typeof vi.spyOn>
beforeEach(() => {
  localStorage.clear()
  sessionStorage.clear()
  vi.resetModules()
  registrations = vi.spyOn(window, 'addEventListener')
})
afterEach(() => {
  for (const [type, listener] of registrations.mock.calls) {
    if (type === 'storage') window.removeEventListener(type, listener as EventListener)
  }
  vi.restoreAllMocks()
})

describe('Shared progress with tab-local chapter selection', () => {
  it('merges advanced chapter progress across stale tabs and resets only the selected chapter', async () => {
    const tabA = await import('./advanced/store')
    vi.resetModules()
    const tabB = await import('./advanced/store')
    tabA.updateAdvanced(s => { s.policy.step = 4; s.policy.completed = [0, 1, 2, 3]; s.policy.open = true })
    tabB.updateAdvanced(s => { s.intelligence.step = 2; s.intelligence.open = true })
    tabA.resetAdvanced('remediation')
    const saved = JSON.parse(localStorage.getItem(tabA.ADVANCED_KEY)!)
    expect(saved.policy.step).toBe(4)
    expect(saved.intelligence.step).toBe(2)
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.ADVANCED_KEY }))
    expect(tabA.advancedStore.getSnapshot().policy.open).toBe(true)
    expect(tabB.advancedStore.getSnapshot().intelligence.open).toBe(true)
    expect(tabB.advancedStore.getSnapshot().policy.step).toBe(4)
  })
  it('preserves another chapter when a stale tab writes and when it resets its own chapter', async () => {
    const tabA = await import('./workflows/store')
    tabA.chooseMode('quality')
    vi.resetModules()
    const tabB = await import('./workflows/store')
    tabB.chooseMode('ai')
    tabA.updateWorkflows(s => { s.quality.step = 7; s.quality.completed = [0, 1, 2] })
    tabB.updateWorkflows(s => { s.ai.step = 4 })
    const saved = JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!)
    expect(saved.quality).toMatchObject({ step: 7, completed: [0, 1, 2] })
    expect(saved.ai.step).toBe(4)
    tabB.resetWorkflow('ai')
    expect(JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!).quality.step).toBe(7)
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.WORKFLOW_KEY }))
    expect(tabA.workflowStore.getSnapshot().mode).toBe('quality')
    expect(tabB.workflowStore.getSnapshot().mode).toBe('ai')
    expect(tabA.workflowStore.getSnapshot().quality.open).toBe(true)
  })
  it('merges fresh scan checkpoints before a stale tab updates its view', async () => {
    const tabA = await import('./scenario/store')
    vi.resetModules()
    const tabB = await import('./scenario/store')
    tabA.updateScenario(s => { s.enabled = true; s.step = 9; s.completed = ['asset', 'scan']; s.feedPublished = true })
    tabB.updateScenario(s => { s.open = false })
    expect(JSON.parse(localStorage.getItem(tabA.SCENARIO_KEY)!)).toMatchObject({ step: 9, completed: ['asset', 'scan'], feedPublished: true })
    window.dispatchEvent(new StorageEvent('storage', { key: tabA.SCENARIO_KEY }))
    expect(tabA.scenarioStore.getSnapshot()).toMatchObject({ enabled: true, step: 9 })
    expect(tabB.scenarioStore.getSnapshot()).toMatchObject({ enabled: false, open: false, step: 9 })
  })
  it('restores the selected chapter from this tab rather than the shared dataset', async () => {
    const tabA = await import('./workflows/store')
    tabA.chooseMode('quality')
    const raw = JSON.parse(localStorage.getItem(tabA.WORKFLOW_KEY)!)
    localStorage.setItem(tabA.WORKFLOW_KEY, JSON.stringify({ ...raw, mode: 'ai' }))
    vi.resetModules()
    const refreshed = await import('./workflows/store')
    expect(refreshed.workflowStore.getSnapshot().mode).toBe('quality')
  })
  it('retains in-memory progress when browser storage is unavailable', async () => {
    const store = await import('./workflows/store')
    store.updateWorkflows(s => { s.quality.step = 3 })
    vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new Error('Storage blocked') })
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage blocked') })
    store.updateWorkflows(s => { s.ai.step = 2 })
    expect(store.workflowStore.getSnapshot()).toMatchObject({ storageWarning: true, quality: { step: 3 }, ai: { step: 2 } })
  })
})
