CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","java");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","java"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="java-string-intern",type="smell",qual="maint",sev="low",cwe="",title="String.intern() misuse",
   desc="Calling intern() on ad-hoc strings can pressure the string pool with little benefit.",
   rationale="intern() adds strings to a permanent pool; overusing it for equality shortcuts wastes memory and rarely helps.",
   remediation="Compare with equals() and avoid manual interning.",
   source="https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#intern--",
   re=r"\.intern\s*\(\s*\)",nc="String k = raw.intern();",c="String k = raw;"),
 r(id="java-numberformat-static",type="bug",qual="rel",sev="medium",cwe="",title="Static NumberFormat field",
   desc="NumberFormat is not thread-safe; a shared static instance corrupts output.",
   rationale="Like SimpleDateFormat, NumberFormat holds mutable state, so a static (shared) instance yields wrong results under concurrency.",
   remediation="Use a local instance, or a thread-safe formatter.",
   source="https://docs.oracle.com/javase/8/docs/api/java/text/NumberFormat.html",
   re=r"\bstatic\b[^;=]*\bNumberFormat\b",nc="private static NumberFormat NF = NumberFormat.getInstance();",c="NumberFormat nf = NumberFormat.getInstance();"),
 r(id="java-exception-no-message",type="smell",qual="maint",sev="low",cwe="",title="Exception thrown without a message",
   desc="Throwing an exception with no message loses diagnostic context.",
   rationale="A message-less exception forces maintainers to read code to understand a failure; a clear message aids debugging.",
   remediation="Pass a descriptive message to the exception constructor.",
   source="https://pmd.github.io/pmd/pmd_rules_java_design.html",
   re=r"throw\s+new\s+\w*Exception\s*\(\s*\)",nc="throw new IllegalStateException();",c='throw new IllegalStateException("cache not initialized");'),
 r(id="java-long-literal-lowercase-l",type="bug",qual="rel",sev="low",cwe="",title="Long literal with lowercase l",
   desc="A trailing lowercase l looks like the digit 1.",
   rationale="100l is easily misread as 1001; the uppercase L suffix is unambiguous.",
   remediation="Use an uppercase L suffix.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/DCL50-J.+Use+visually+distinct+identifiers",
   re=r"\b[0-9]+l\b",nc="long max = 1000000l;",c="long max = 1000000L;"),
 r(id="java-octal-literal",type="bug",qual="rel",sev="low",cwe="",title="Octal integer literal",
   desc="A leading-zero integer literal is octal, a common surprise.",
   rationale="A leading zero makes the literal octal, so 0755 is 493 (not 755); this is a frequent source of numeric bugs.",
   remediation="Drop the leading zero for a decimal, or use an explicit radix.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/DCL50-J.+Use+visually+distinct+identifiers",
   re=r"=\s*0[0-7]{2,}\b",nc="int mode = 0755;",c="int mode = 493;"),
 r(id="java-empty-synchronized",type="bug",qual="rel",sev="medium",cwe="",title="Empty synchronized block",
   desc="An empty synchronized block only acquires and releases the lock.",
   rationale="A synchronized block with no body does nothing useful beyond a memory barrier and usually signals removed or misplaced code.",
   remediation="Remove the block, or add the intended guarded statements.",
   source="https://pmd.github.io/pmd/pmd_rules_java_errorprone.html",
   re=r"synchronized\s*\([^)]*\)\s*\{\s*\}",nc="synchronized (lock) {}",c="synchronized (lock) { counter++; }"),
 r(id="java-boolean-getboolean",type="bug",qual="rel",sev="medium",cwe="",title="Boolean.getBoolean misuse",
   desc="Boolean.getBoolean reads a system property, not a string; likely a mistake.",
   rationale="Boolean.getBoolean(name) looks up the system property `name`, so passing a value string always returns false — parseBoolean is almost always intended.",
   remediation="Use Boolean.parseBoolean(s) to parse a string.",
   source="https://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html#getBoolean-java.lang.String-",
   re=r"Boolean\.getBoolean\s*\(",nc="boolean on = Boolean.getBoolean(value);",c="boolean on = Boolean.parseBoolean(value);"),
]
