# VB.NET language-pack security rules (#211). Clean-room, line-detectable, and precision-biased.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "vb")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "vbnet", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- inj (15) ----
    r("inj", id="vb:sql-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL command built by concatenation",
      desc="A SQL command string combines SQL text with a value using VB concatenation.",
      rationale="Concatenation can turn data into SQL syntax before the database parses the command.",
      remediation="Use a parameterized command and bind values through Parameters.Add.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'(?i)"[^"\r\n]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^"\r\n]*"\s*(?:&|\+)\s*[A-Za-z_][A-Za-z0-9_]*',
      nc='Dim sql = "SELECT * FROM Users WHERE Name = " & name',
      c='Dim cmd = New SqlCommand("SELECT * FROM Users WHERE Name = @name", connection)', effort=30),
    r("inj", id="vb:sql-interpolated-string", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL command uses an interpolated string",
      desc="A VB interpolated string contains a SQL keyword and an expression hole.",
      rationale="Interpolating a value into SQL changes the command text instead of binding data separately.",
      remediation="Keep SQL text constant and add each value as a database parameter.",
      source="https://owasp.org/www-community/attacks/SQL_Injection",
      re=r'(?i)\$"[^"\r\n]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^"\r\n]*\{[^}]+\}',
      nc='Dim sql = $"SELECT * FROM Users WHERE Id = {userId}"',
      c='Dim cmd = New SqlCommand("SELECT * FROM Users WHERE Id = @id", connection)', effort=30),
    r("inj", id="vb:sql-string-format", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL command built with String.Format",
      desc="String.Format produces text containing a SQL statement.",
      rationale="Formatting values into a SQL statement leaves no parameter boundary for the database to enforce.",
      remediation="Use SQL parameters rather than formatting values into command text.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'(?i)\bString\.Format\s*\(\s*"[^"\r\n]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b',
      nc='Dim sql = String.Format("SELECT * FROM Users WHERE Id = {0}", userId)',
      c='Dim cmd = New SqlCommand("SELECT * FROM Users WHERE Id = @id", connection)', effort=30),
    r("inj", id="vb:sql-command-text-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="CommandText receives concatenated SQL",
      desc="A CommandText assignment combines SQL text and a value.",
      rationale="Building CommandText from values can allow a value to alter query structure.",
      remediation="Assign a parameterized statement and add typed parameter values.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.parameters",
      re=r'(?i)\bCommandText\s*=\s*"[^"\r\n]*\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^"\r\n]*"\s*(?:&|\+)',
      nc='command.CommandText = "DELETE FROM Sessions WHERE Id = " & sessionId',
      c='command.CommandText = "DELETE FROM Sessions WHERE Id = @id"', effort=30),
    r("inj", id="vb:process-start-var", type="hotspot", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Process.Start receives a variable command",
      desc="Process.Start is called with a variable rather than a fixed executable name.",
      rationale="A variable command can select an unintended program or carry unreviewed command-line content.",
      remediation="Use a fixed executable and add validated arguments through ProcessStartInfo.ArgumentList.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'(?i)\bProcess\.Start\s*\(\s*[a-z_][A-Za-z0-9_]*\s*(?:\)|,)',
      nc='Process.Start(command)',
      c='Process.Start("dotnet", "--info")', effort=30),
    r("inj", id="vb:process-start-concat", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Process.Start command is concatenated",
      desc="Process.Start receives command text assembled with a value.",
      rationale="Command concatenation can make external data executable as command syntax or arguments.",
      remediation="Set FileName to a fixed program and validate each separate argument.",
      source="https://owasp.org/www-community/attacks/Command_Injection",
      re=r'(?i)\bProcess\.Start\s*\(\s*"[^"\r\n]*"\s*(?:&|\+)',
      nc='Process.Start("cmd.exe /c ping " & host)',
      c='Dim startInfo = New ProcessStartInfo("ping") With {.UseShellExecute = False}', effort=30),
    r("inj", id="vb:process-startinfo-arguments-concat", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="ProcessStartInfo Arguments are concatenated",
      desc="A ProcessStartInfo Arguments property combines a literal with a value.",
      rationale="A single command-line string can reinterpret untrusted data as options or shell syntax.",
      remediation="Use ArgumentList with a fixed executable and validated argument values.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist",
      re=r'(?i)\bArguments\s*=\s*"[^"\r\n]*"\s*(?:&|\+)',
      nc='startInfo.Arguments = "/c dir " & folder',
      c='startInfo.ArgumentList.Add("--version")', effort=30),
    r("inj", id="vb:xml-dtd-parse", type="vuln", qual="sec", sev="high", cwe="CWE-611", owasp="A05:2021",
      title="XML DTD processing enabled",
      desc="XmlReaderSettings enables DtdProcessing.Parse.",
      rationale="DTD processing can resolve attacker-controlled external entities to local files or network resources.",
      remediation="Set DtdProcessing to Prohibit and XmlResolver to Nothing for untrusted XML.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r'(?i)\bDtdProcessing\s*=\s*DtdProcessing\.Parse\b',
      nc='settings.DtdProcessing = DtdProcessing.Parse',
      c='settings.DtdProcessing = DtdProcessing.Prohibit', effort=30),
    r("inj", id="vb:binaryformatter-deserialize", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="BinaryFormatter deserialization",
      desc="BinaryFormatter.Deserialize is invoked.",
      rationale="BinaryFormatter payloads can activate dangerous object graphs during deserialization.",
      remediation="Use a data-only serializer with a constrained schema for untrusted input.",
      source="https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide",
      re=r'(?i)\bBinaryFormatter\b[^\r\n]*\.Deserialize\s*\(',
      nc='Dim value = New BinaryFormatter().Deserialize(stream)',
      c='Dim value = JsonSerializer.Deserialize(Of Profile)(json)', effort=60),
    r("inj", id="vb:javascriptserializer-deserialize", type="hotspot", qual="sec", sev="medium", cwe="CWE-502", owasp="A08:2021",
      title="JavaScriptSerializer deserializes dynamic input",
      desc="JavaScriptSerializer.DeserializeObject is called.",
      rationale="Dynamic deserialization needs review for size limits, expected shape, and downstream type handling.",
      remediation="Deserialize into a dedicated DTO and validate its fields before use.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'(?i)\bJavaScriptSerializer\b[^\r\n]*\.DeserializeObject\s*\(',
      nc='Dim value = New JavaScriptSerializer().DeserializeObject(body)',
      c='Dim value = JsonSerializer.Deserialize(Of Settings)(body)', effort=30),
    r("inj", id="vb:response-write-request", type="vuln", qual="sec", sev="high", cwe="CWE-79", owasp="A03:2021",
      title="Response.Write receives request data",
      desc="Response.Write directly renders a Request collection value.",
      rationale="Rendering request data without context-aware encoding can inject markup into an HTML response.",
      remediation="Use framework output encoding or HtmlEncode before writing HTML text.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'(?i)\bResponse\.Write\s*\(\s*Request\.(?:QueryString|Form|Params|Cookies)\s*\(',
      nc='Response.Write(Request.QueryString("message"))',
      c='Response.Write(Server.HtmlEncode(Request.QueryString("message")))', effort=30),
    r("inj", id="vb:redirect-request-url", type="vuln", qual="sec", sev="medium", cwe="CWE-601", owasp="A01:2021",
      title="Redirect target comes from a request value",
      desc="Response.Redirect receives a query-string or form value directly.",
      rationale="An attacker-controlled redirect can send users from a trusted site to a phishing destination.",
      remediation="Redirect to a fixed local route or allowlist known destinations.",
      source="https://cwe.mitre.org/data/definitions/601.html",
      re=r'(?i)\bResponse\.Redirect\s*\(\s*Request\.(?:QueryString|Form|Params)\s*\(',
      nc='Response.Redirect(Request.QueryString("next"))',
      c='Response.Redirect("~/Account/Overview")', effort=30),
    r("inj", id="vb:path-combine-request", type="vuln", qual="sec", sev="high", cwe="CWE-22", owasp="A01:2021",
      title="Path.Combine receives a request value",
      desc="Path.Combine mixes a base directory with request-derived text.",
      rationale="A request path can contain traversal segments that escape the intended directory.",
      remediation="Resolve the path and verify it remains below the approved base directory.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'(?i)\bPath\.Combine\s*\([^\r\n]*Request\.(?:QueryString|Form|Params)\s*\(',
      nc='Dim path = Path.Combine(root, Request.QueryString("file"))',
      c='Dim path = SafeResolve(root, fileName)', effort=30),
    r("inj", id="vb:regex-request-pattern", type="hotspot", qual="sec", sev="medium", cwe="CWE-1333", owasp="A03:2021",
      title="Regular expression is built from request data",
      desc="A Regex constructor receives a request collection value.",
      rationale="Request-controlled patterns can consume excessive CPU or alter expected matching semantics.",
      remediation="Escape literal input, constrain supported syntax, and set a timeout.",
      source="https://cwe.mitre.org/data/definitions/1333.html",
      re=r'(?i)\bNew\s+Regex\s*\(\s*Request\.(?:QueryString|Form|Params)\s*\(',
      nc='Dim pattern = New Regex(Request.QueryString("pattern"))',
      c='Dim pattern = New Regex(Regex.Escape(term), TimeSpan.FromSeconds(1))', effort=30),
    r("inj", id="vb:xpath-request-expression", type="hotspot", qual="sec", sev="high", cwe="CWE-643", owasp="A03:2021",
      title="XPath expression uses request data",
      desc="SelectSingleNode or SelectNodes receives a request collection value.",
      rationale="Request-controlled XPath can change which nodes are selected from an XML document.",
      remediation="Map request choices to fixed XPath expressions or safely encode literal values.",
      source="https://cwe.mitre.org/data/definitions/643.html",
      re=r'(?i)\bSelect(?:SingleNode|Nodes)\s*\(\s*Request\.(?:QueryString|Form|Params)\s*\(',
      nc='Dim node = doc.SelectSingleNode(Request.QueryString("xpath"))',
      c='Dim node = doc.SelectSingleNode("/catalog/item")', effort=30),

    # ---- crypto (10) ----
    r("crypto", id="vb:weak-hash", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Weak MD5 or SHA-1 hash selected",
      desc="MD5 or SHA-1 hashing APIs are referenced.",
      rationale="MD5 and SHA-1 have practical collision attacks and need review before any security use.",
      remediation="Use SHA-256 or stronger for integrity; use a password KDF for passwords.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(?i)\b(?:MD5|SHA1)\.(?:Create|HashData)\s*\(|\bNew\s+(?:MD5|SHA1)(?:CryptoServiceProvider|Managed)\s*\(',
      nc='Dim hash = MD5.Create()',
      c='Dim hash = SHA256.Create()'),
    r("crypto", id="vb:legacy-cipher", type="hotspot", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="Legacy symmetric cipher selected",
      desc="DES, TripleDES, RC2, or RC4 is instantiated.",
      rationale="These legacy algorithms do not provide adequate protection for new sensitive data.",
      remediation="Use an authenticated modern cipher such as AesGcm with unique nonces.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(?i)\b(?:DES|TripleDES|RC2|RC4)\.Create\s*\(|\bNew\s+(?:DESCryptoServiceProvider|TripleDESCryptoServiceProvider|RC2CryptoServiceProvider|RC4CryptoServiceProvider)\s*\(',
      nc='Dim cipher = TripleDES.Create()',
      c='Dim cipher = New AesGcm(key)'),
    r("crypto", id="vb:ecb-mode", type="hotspot", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="ECB cipher mode selected",
      desc="CipherMode.ECB is assigned or referenced.",
      rationale="ECB reveals repeated plaintext blocks because equal blocks encrypt identically.",
      remediation="Use an authenticated encryption mode with a unique nonce per operation.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(?i)\bCipherMode\.ECB\b',
      nc='aes.Mode = CipherMode.ECB',
      c='Dim cipher = New AesGcm(key)', effort=60),
    r("crypto", id="vb:random-security-name", type="hotspot", qual="sec", sev="medium", cwe="CWE-338", owasp="A02:2021",
      title="Random used for a security-named value",
      desc="A token, secret, password, key, or nonce-named variable is assigned from Random.",
      rationale="Random is not a cryptographic generator and can make security values predictable.",
      remediation="Use RandomNumberGenerator to generate security-sensitive bytes.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'(?i)\b\w*(?:token|secret|password|apiKey|nonce)\w*\s*=\s*(?:New\s+)?Random\s*\(\)|\b\w*(?:token|secret|password|apiKey|nonce)\w*\s*=\s*random\.Next',
      nc='Dim resetToken = New Random().Next()',
      c='Dim resetToken = Convert.ToHexString(RandomNumberGenerator.GetBytes(32))'),
    r("crypto", id="vb:hardcoded-crypto-key", type="hotspot", qual="sec", sev="high", cwe="CWE-321", owasp="A02:2021",
      title="Cryptographic key literal in source",
      desc="A key, secret, IV, or nonce-named variable is assigned a string literal.",
      rationale="Key material embedded in source is extractable and difficult to rotate.",
      remediation="Load secret material from a managed secret store at runtime.",
      source="https://cwe.mitre.org/data/definitions/321.html",
      re=r'\b(?:[A-Za-z_]\w*(?:Key|Secret|Nonce)|(?:key|secret|nonce)(?:_[A-Za-z0-9_]+)?)\s*(?:As\s+\w+\s*)?=\s*"[^"\r\n]+"',
      nc='Dim encryptionKey = "0123456789abcdef"',
      c='Dim encryptionKey = secretProvider.GetSecret("encryption-key")', effort=30),
    r("crypto", id="vb:static-iv", type="hotspot", qual="sec", sev="medium", cwe="CWE-329", owasp="A02:2021",
      title="Initialization vector is a literal",
      desc="An IV-named variable is initialized with a literal byte array or string.",
      rationale="A reused IV can reveal relationships between encrypted messages.",
      remediation="Generate a fresh unpredictable IV or nonce for every encryption operation.",
      source="https://cwe.mitre.org/data/definitions/329.html",
      re=r'(?i)\b(?:iv|initializationvector)\s*(?:As\s+\w+\s*)?=\s*(?:New\s+Byte\s*\([^)]*\)\s*\{|"[^"\r\n]+")',
      nc='Dim iv = New Byte() {1, 2, 3, 4}',
      c='Dim iv = RandomNumberGenerator.GetBytes(12)'),
    r("crypto", id="vb:weak-pbkdf2-iterations", type="hotspot", qual="sec", sev="medium", cwe="CWE-916", owasp="A02:2021",
      title="PBKDF2 has a low iteration count",
      desc="Rfc2898DeriveBytes is constructed with a literal iteration count below 10,000.",
      rationale="A low work factor makes password guesses inexpensive for an attacker.",
      remediation="Use a current, reviewed work factor and upgrade stored hashes over time.",
      source="https://cwe.mitre.org/data/definitions/916.html",
      re=r'(?i)\bNew\s+Rfc2898DeriveBytes\s*\([^\r\n]*,\s*(?:[1-9]|[1-9][0-9]{1,3})\s*(?:,|\))',
      nc='Dim kdf = New Rfc2898DeriveBytes(password, salt, 1000)',
      c='Dim kdf = New Rfc2898DeriveBytes(password, salt, 210000, HashAlgorithmName.SHA256)', effort=30),
    r("crypto", id="vb:rsa-small-key", type="hotspot", qual="sec", sev="high", cwe="CWE-326", owasp="A02:2021",
      title="RSA key size below 2048 bits",
      desc="An RSA provider is created with a 512- or 1024-bit key size.",
      rationale="Small RSA keys provide insufficient resistance to modern cryptanalysis.",
      remediation="Generate RSA keys of at least 2048 bits, subject to current policy.",
      source="https://cwe.mitre.org/data/definitions/326.html",
      re=r'(?i)\bNew\s+RSACryptoServiceProvider\s*\(\s*(?:512|1024)\s*\)',
      nc='Dim rsa = New RSACryptoServiceProvider(1024)',
      c='Dim rsa = New RSACryptoServiceProvider(3072)', effort=30),
    r("crypto", id="vb:legacy-tls", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Legacy TLS protocol selected",
      desc="SslProtocols selects SSL 2.0, SSL 3.0, TLS 1.0, or TLS 1.1.",
      rationale="Legacy protocol versions have known weaknesses and no longer meet current transport-security expectations.",
      remediation="Use TLS 1.2 or newer, or let the operating system negotiate secure defaults.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols",
      re=r'(?i)\bSslProtocols\.(?:Ssl2|Ssl3|Tls|Tls11)\b',
      nc='Dim protocols = SslProtocols.Tls11',
      c='Dim protocols = SslProtocols.Tls13'),
    r("crypto", id="vb:cert-validation-true", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="Certificate validation callback always accepts",
      desc="A certificate validation callback is assigned a lambda that returns True.",
      rationale="Accepting every certificate disables server identity verification and permits interception.",
      remediation="Validate the certificate chain, hostname, and policy errors before accepting it.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'(?i)\b(?:ServerCertificateValidationCallback|RemoteCertificateValidationCallback)\s*=\s*(?:Function|Sub)\b[^\r\n]*\bTrue\b',
      nc='ServicePointManager.ServerCertificateValidationCallback = Function(sender, cert, chain, errors) True',
      c='ServicePointManager.ServerCertificateValidationCallback = AddressOf ValidateCertificate', effort=30),

    # ---- authz (6) ----
    r("authz", id="vb:allow-anonymous", type="hotspot", qual="sec", sev="medium", cwe="CWE-862", owasp="A01:2021",
      title="AllowAnonymous attribute exposes an endpoint",
      desc="An ASP.NET endpoint is marked with AllowAnonymous.",
      rationale="The attribute bypasses the surrounding authorization policy and requires an explicit public-access review.",
      remediation="Remove the attribute or confirm the action has no protected data or state change.",
      source="https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.allowanonymousattribute",
      re=r'(?i)<\s*AllowAnonymous(?:Attribute)?\s*>',
      nc='<AllowAnonymous>\nPublic Function AdminExport() As ActionResult',
      c='<Authorize(Roles := "Administrator")>\nPublic Function AdminExport() As ActionResult'),
    r("authz", id="vb:skip-authorization", type="hotspot", qual="sec", sev="high", cwe="CWE-862", owasp="A01:2021",
      title="HTTP authorization is skipped",
      desc="HttpContext.SkipAuthorization is set to True.",
      rationale="Skipping authorization bypasses URL authorization checks for the current request.",
      remediation="Remove the bypass and model any intended public route with an explicit, tested policy.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.web.httpcontext.skipauthorization",
      re=r'(?i)\b(?:HttpContext\.Current\.)?SkipAuthorization\s*=\s*True\b',
      nc='HttpContext.Current.SkipAuthorization = True',
      c='HttpContext.Current.SkipAuthorization = False', effort=30),
    r("authz", id="vb:principal-permission-unrestricted", type="hotspot", qual="sec", sev="high", cwe="CWE-269", owasp="A01:2021",
      title="PrincipalPermission demand is unrestricted",
      desc="A PrincipalPermission attribute declares Unrestricted := True.",
      rationale="An unrestricted demand does not constrain which principal may invoke the member.",
      remediation="Require a named role or replace legacy declarative checks with an explicit authorization policy.",
      source="https://cwe.mitre.org/data/definitions/269.html",
      re=r'(?i)<\s*PrincipalPermission(?:Attribute)?\s*\([^\r\n]*\bUnrestricted\s*:=\s*True',
      nc='<PrincipalPermission(SecurityAction.Demand, Unrestricted := True)>',
      c='<PrincipalPermission(SecurityAction.Demand, Role := "Administrator")>', effort=30),
    r("authz", id="vb:request-admin-role-grant", type="vuln", qual="sec", sev="high", cwe="CWE-269", owasp="A01:2021",
      title="Request value is granted the Administrator role",
      desc="A role API adds a request-derived user value to the Administrator role.",
      rationale="Binding a privileged role grant directly to request data can let callers elevate an unintended account.",
      remediation="Authorize the acting administrator, resolve the target account, and validate a fixed role allowlist.",
      source="https://cwe.mitre.org/data/definitions/269.html",
      re=r'(?i)\bRoles\.AddUserToRole\s*\(\s*Request\.(?:QueryString|Form|Params)\s*\([^)]*\)\s*,\s*"Administrator"\s*\)',
      nc='Roles.AddUserToRole(Request.Form("user"), "Administrator")',
      c='Roles.AddUserToRole(targetUser.Name, approvedRole)', effort=30),
    r("authz", id="vb:request-role-assignment", type="vuln", qual="sec", sev="high", cwe="CWE-915", owasp="A01:2021",
      title="Request value controls an assigned role",
      desc="A role-assignment API receives a role directly from a request collection.",
      rationale="A request-controlled role name can grant privileges outside the caller's intended authority.",
      remediation="Map approved request choices to a closed role allowlist after authorization.",
      source="https://cwe.mitre.org/data/definitions/915.html",
      re=r'(?i)\bRoles\.AddUserToRole\s*\([^\r\n]*,\s*Request\.(?:QueryString|Form|Params)\s*\(',
      nc='Roles.AddUserToRole(user.Name, Request.Form("role"))',
      c='Roles.AddUserToRole(user.Name, AllowedRoles(roleName))', effort=30),
    r("authz", id="vb:authorization-allow-all", type="hotspot", qual="sec", sev="medium", cwe="CWE-862", owasp="A01:2021",
      title="Endpoint authorization policy allows every user",
      desc="A VB source attribute applies an Authorize policy with Users := \"*\".",
      rationale="An allow-all endpoint policy can override an expected restricted action and needs review in its route scope.",
      remediation="Use an explicit role or a named policy for protected endpoints.",
      source="https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizeattribute",
      re=r'(?i)<\s*Authorize(?:Attribute)?\s*\([^\r\n]*\bUsers\s*:=\s*"\*"',
      nc='<Authorize(Users := "*")>\nPublic Function Export() As ActionResult',
      c='<Authorize(Roles := "Administrators")>\nPublic Function Export() As ActionResult'),

    # ---- hotspot (12) ----
    r("hotspot", id="vb:hardcoded-conn-string", type="hotspot", qual="sec", sev="high", cwe="CWE-798", owasp="A07:2021",
      title="Connection string contains an inline password",
      desc="A connection string literal includes a Password or Pwd value.",
      rationale="Credentials committed in source can be disclosed through repositories, logs, or compiled artifacts.",
      remediation="Load the connection string from configuration backed by a secret store.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'(?i)"[^"\r\n]*(?:Password|Pwd)\s*=\s*[^;"\s][^"\r\n]*"',
      nc='Dim cs = "Server=db;User Id=app;Password=secret;"',
      c='Dim cs = configuration.GetConnectionString("Primary")', effort=30),
    r("hotspot", id="vb:hardcoded-password", type="hotspot", qual="sec", sev="high", cwe="CWE-798", owasp="A07:2021",
      title="Password literal in source",
      desc="A password-named variable is assigned a non-empty string literal.",
      rationale="A source-embedded password is difficult to rotate and visible to anyone who can read the code or binary.",
      remediation="Retrieve credentials from a secret manager or protected runtime configuration.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'(?i)\b\w*password\w*\s*(?:As\s+String\s*)?=\s*"[^"\r\n]+"',
      nc='Dim smtpPassword = "secret"',
      c='Dim smtpPassword = secretProvider.GetSecret("smtp-password")', effort=30),
    r("hotspot", id="vb:assembly-load-var", type="hotspot", qual="sec", sev="high", cwe="CWE-114", owasp="A03:2021",
      title="Assembly.LoadFrom uses a variable path",
      desc="Assembly.LoadFrom receives a non-literal path.",
      rationale="Loading an assembly from a variable location needs review for path control and code trust.",
      remediation="Load only signed assemblies from an application-controlled allowlist.",
      source="https://cwe.mitre.org/data/definitions/114.html",
      re=r'(?i)\bAssembly\.LoadFrom\s*\(\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim plugin = Assembly.LoadFrom(pluginPath)',
      c='Dim plugin = Assembly.Load("Trusted.Plugin")', effort=30),
    r("hotspot", id="vb:type-gettype-var", type="hotspot", qual="sec", sev="medium", cwe="CWE-470", owasp="A03:2021",
      title="Type.GetType uses a variable name",
      desc="Type.GetType receives a non-literal type name.",
      rationale="Externally influenced type selection can expose unreviewed code paths through reflection.",
      remediation="Map external identifiers to a closed set of allowed types.",
      source="https://cwe.mitre.org/data/definitions/470.html",
      re=r'(?i)\bType\.GetType\s*\(\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim handlerType = Type.GetType(typeName)',
      c='Dim handlerType = AllowedTypes(typeName)', effort=30),
    r("hotspot", id="vb:activator-createinstance-var", type="hotspot", qual="sec", sev="medium", cwe="CWE-470", owasp="A03:2021",
      title="Activator.CreateInstance uses a variable type",
      desc="Activator.CreateInstance receives a variable type expression.",
      rationale="Reflective construction can instantiate code paths not intended for the current request or workflow.",
      remediation="Instantiate a fixed type or select from an explicit factory map.",
      source="https://cwe.mitre.org/data/definitions/470.html",
      re=r'(?i)\bActivator\.CreateInstance\s*\(\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim handler = Activator.CreateInstance(handlerType)',
      c='Dim handler = New InvoiceHandler()', effort=30),
    r("hotspot", id="vb:regex-variable-pattern", type="hotspot", qual="sec", sev="medium", cwe="CWE-1333", owasp="A03:2021",
      title="Regex constructor uses a variable pattern",
      desc="New Regex receives a variable as its pattern.",
      rationale="Variable regular expressions need review for attacker control, complexity, and timeout behavior.",
      remediation="Use fixed patterns where possible; otherwise apply a timeout and constrain pattern input.",
      source="https://cwe.mitre.org/data/definitions/1333.html",
      re=r'(?i)\bNew\s+Regex\s*\(\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim matcher = New Regex(pattern)',
      c='Dim matcher = New Regex("^[A-Z]{2}-[0-9]{4}$", TimeSpan.FromSeconds(1))', effort=30),
    r("hotspot", id="vb:webclient-variable-url", type="hotspot", qual="sec", sev="high", cwe="CWE-918", owasp="A10:2021",
      title="WebClient fetches a variable URL",
      desc="WebClient.DownloadString or DownloadData receives a variable URL.",
      rationale="A variable URL needs review for SSRF, redirects, and access to internal network services.",
      remediation="Allowlist schemes, hosts, ports, redirects, and resolved IP ranges before fetching.",
      source="https://cwe.mitre.org/data/definitions/918.html",
      re=r'(?i)\b\w+\.(?:DownloadString|DownloadData)\s*\(\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim body = client.DownloadString(url)',
      c='Dim body = client.DownloadString("https://api.example.test")', effort=60),
    r("hotspot", id="vb:useshellexecute-true", type="hotspot", qual="sec", sev="medium", cwe="CWE-78", owasp="A03:2021",
      title="ProcessStartInfo enables shell execution",
      desc="UseShellExecute is set to True.",
      rationale="Shell execution can change how a file name or arguments are interpreted and needs a narrow trust boundary.",
      remediation="Set UseShellExecute to False and invoke a fixed executable directly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute",
      re=r'(?i)\bUseShellExecute\s*=\s*True\b',
      nc='Dim info = New ProcessStartInfo() With {.UseShellExecute = True}',
      c='Dim info = New ProcessStartInfo("dotnet") With {.UseShellExecute = False}', effort=30),
    r("hotspot", id="vb:cleartext-http", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021",
      title="Cleartext HTTP endpoint",
      desc="A string literal begins with an HTTP URL.",
      rationale="Cleartext HTTP exposes data and cookies to network observers unless a controlled local exception applies.",
      remediation="Use HTTPS and validate the server certificate.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'(?i)"http://[A-Za-z][^"\r\n]*"',
      nc='Dim endpoint = "http://api.example.test/v1"',
      c='Dim endpoint = "https://api.example.test/v1"'),
    r("hotspot", id="vb:xmlresolver-set", type="hotspot", qual="sec", sev="medium", cwe="CWE-611", owasp="A05:2021",
      title="XML resolver is assigned",
      desc="An XmlResolver property is set to a non-Nothing value.",
      rationale="An active XML resolver may fetch external entities and should be reviewed with the parser settings.",
      remediation="Set XmlResolver to Nothing for untrusted XML unless a controlled resolver is required.",
      source="https://learn.microsoft.com/en-us/dotnet/standard/serialization/how-to-protect-xml-data-from-entity-expansion",
      re=r'(?i)\bXmlResolver\s*=\s*New\s+[A-Za-z_][A-Za-z0-9_]*',
      nc='settings.XmlResolver = New XmlUrlResolver()',
      c='settings.XmlResolver = Nothing', effort=30),
    r("hotspot", id="vb:directory-getfiles-variable-pattern", type="hotspot", qual="sec", sev="medium", cwe="CWE-22", owasp="A01:2021",
      title="Directory search uses a variable pattern",
      desc="Directory.GetFiles receives a variable search pattern.",
      rationale="A variable pattern can enumerate unexpected files and needs review when it crosses a trust boundary.",
      remediation="Use a fixed pattern or validate allowed extensions and the resolved base directory.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'(?i)\bDirectory\.GetFiles\s*\(\s*[^,\r\n]+,\s*[a-z_][A-Za-z0-9_]*\s*\)',
      nc='Dim files = Directory.GetFiles(root, pattern)',
      c='Dim files = Directory.GetFiles(root, "*.json")'),
    r("hotspot", id="vb:unmanaged-dllimport", type="hotspot", qual="sec", sev="medium", cwe="CWE-111", owasp="A03:2021",
      title="P/Invoke declaration",
      desc="A method declares the DllImport attribute.",
      rationale="Native interoperation depends on an unchecked ABI contract and warrants focused review.",
      remediation="Validate the native signature, marshal types explicitly, and wrap the call behind a small safe API.",
      source="https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke",
      re=r'(?i)<\s*DllImport(?:Attribute)?\s*\(',
      nc='<DllImport("kernel32.dll")>\nPrivate Shared Function CloseHandle(handle As IntPtr) As Boolean',
      c='Private Shared Function CloseHandle(handle As SafeHandle) As Boolean'),
]
