# Java language-pack rule specs (#196). Java-specific, line-detectable patterns not already
# covered by the language-agnostic security core. Cross-procedural / type-flow rules are AST-tier.
CC = "commentOnlyLine"

def r(**k):
    k.setdefault("lang", "java")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "java"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k

RULES = [
    r(id="java-string-ref-equality", type="bug", qual="rel", sev="high", cwe="",
      title="Reference equality on a String literal",
      desc="Comparing a String with == tests reference identity, not contents.",
      rationale="== on String (or boxed) operands compares object references, not values, so it fails for equal-but-distinct instances. Use equals().",
      remediation="Compare strings with .equals() (or Objects.equals for null-safety).",
      source="https://errorprone.info/bugpattern/ReferenceEquality",
      re=r'((==|!=)\s*"|"\s*(==|!=))', nc='if (role == "admin") { grant(); }', c='if (role.equals("admin")) { grant(); }'),
    r(id="java-empty-catch", type="bug", qual="rel", sev="medium", cwe="CWE-390",
      title="Empty catch block (Java)",
      desc="An empty catch swallows the exception silently.",
      rationale="Silently swallowing an exception hides failures and makes debugging hard (CWE-390).",
      remediation="Handle, log, or rethrow the caught exception.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r"catch\s*\([^)]*\)\s*\{\s*\}", nc="try { load(); } catch (IOException e) {}", c="try { load(); } catch (IOException e) { log.warn(\"load failed\", e); }"),
    r(id="java-catch-generic", type="smell", qual="maint", sev="low", cwe="",
      title="Catching a generic exception type",
      desc="Catching Exception/Throwable/RuntimeException hides which failures are handled.",
      rationale="A broad catch obscures the failures actually being handled and can accidentally swallow programming errors; catch the specific types.",
      remediation="Catch the specific checked exceptions the code can recover from.",
      source="https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors",
      re=r"catch\s*\(\s*(Exception|Throwable|RuntimeException)\s+", nc="try { work(); } catch (Exception e) { handle(e); }", c="try { work(); } catch (SQLException e) { handle(e); }"),
    r(id="java-catch-npe", type="smell", qual="maint", sev="medium", cwe="",
      title="Catching NullPointerException",
      desc="Catching NPE masks a programming error that should be prevented, not caught.",
      rationale="A NullPointerException indicates a bug (a missing null check); catching it hides the defect rather than fixing it (SEI CERT ERR08-J).",
      remediation="Add the missing null check or precondition instead of catching NPE.",
      source="https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors",
      re=r"catch\s*\(\s*NullPointerException", nc="try { f(x); } catch (NullPointerException e) { skip(); }", c="if (x != null) { f(x); }"),
    r(id="java-printstacktrace", type="smell", qual="maint", sev="low", cwe="",
      title="Throwable.printStackTrace() used",
      desc="printStackTrace writes to stderr and bypasses the logging framework.",
      rationale="printStackTrace() sends output to stderr outside the logging configuration, so the trace is lost in production and cannot be routed or leveled.",
      remediation="Log the exception through the application logger.",
      source="https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html",
      re=r"\.printStackTrace\s*\(\s*\)", nc="} catch (IOException e) { e.printStackTrace(); }", c="} catch (IOException e) { log.error(\"io\", e); }"),
    r(id="java-system-exit", type="smell", qual="maint", sev="medium", cwe="",
      title="System.exit() in library code",
      desc="System.exit terminates the entire JVM, which library code must not do.",
      rationale="Calling System.exit from library code shuts down the whole JVM, including unrelated components and cleanup handlers (SEI CERT ERR09-J).",
      remediation="Throw an exception and let the application decide how to terminate.",
      source="https://wiki.sei.cmu.edu/confluence/display/java/ERR09-J.+Do+not+allow+untrusted+code+to+terminate+the+JVM",
      re=r"System\.exit\s*\(", nc="if (fatal) System.exit(1);", c="if (fatal) throw new IllegalStateException(\"fatal\");"),
    r(id="java-explicit-gc", type="smell", qual="maint", sev="medium", cwe="",
      title="Explicit System.gc() call",
      desc="Calling System.gc() forces a full collection and hurts performance.",
      rationale="An explicit garbage-collection request can trigger an expensive stop-the-world collection and rarely helps; the JVM manages this better.",
      remediation="Remove the System.gc() call and let the JVM manage collection.",
      source="https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html",
      re=r"System\.gc\s*\(\s*\)", nc="cleanup(); System.gc();", c="cleanup();"),
    r(id="java-finalize-override", type="smell", qual="maint", sev="medium", cwe="",
      title="Overriding finalize()",
      desc="finalize() is deprecated, runs unpredictably, and can resurrect objects.",
      rationale="finalize() runs at an unpredictable time (or never), can slow collection, and is deprecated for removal; it is not a reliable cleanup mechanism.",
      remediation="Use try-with-resources / AutoCloseable or a java.lang.ref.Cleaner instead.",
      source="https://errorprone.info/bugpattern/Finalize",
      re=r"\bprotected\s+void\s+finalize\s*\(", nc="protected void finalize() throws Throwable { free(); }", c="public void close() { free(); }"),
    r(id="java-legacy-collection", type="smell", qual="maint", sev="low", cwe="",
      title="Legacy synchronized collection",
      desc="Vector/Hashtable/Stack synchronize every call; prefer modern collections.",
      rationale="Vector, Hashtable, and Stack lock on every operation even when no sharing occurs, and their APIs are dated; ArrayList/HashMap/ArrayDeque are preferred.",
      remediation="Use ArrayList/HashMap/ArrayDeque, with explicit synchronization only where needed.",
      source="https://docs.oracle.com/javase/8/docs/api/java/util/Vector.html",
      re=r"\bnew\s+(Vector|Hashtable|Stack)\s*[<(]", nc="List<String> items = new Vector<>();", c="List<String> items = new ArrayList<>();"),
    r(id="java-simpledateformat-static", type="bug", qual="rel", sev="medium", cwe="",
      title="Static SimpleDateFormat field",
      desc="SimpleDateFormat is not thread-safe; a shared static instance corrupts output under concurrency.",
      rationale="SimpleDateFormat holds mutable calendar state, so a static (shared) instance produces wrong results or exceptions when used by multiple threads.",
      remediation="Use a local instance, or the thread-safe java.time.format.DateTimeFormatter.",
      source="https://errorprone.info/bugpattern/StaticAssignmentOfThrowable",
      re=r"\bstatic\b[^;=]*\bSimpleDateFormat\b", nc="private static SimpleDateFormat FMT = new SimpleDateFormat(\"yyyy\");", c="private final DateTimeFormatter fmt = DateTimeFormatter.ISO_DATE;"),
    r(id="java-empty-if", type="bug", qual="rel", sev="low", cwe="",
      title="Empty if body via stray semicolon",
      desc="`if (cond);` has an empty body; the following block runs unconditionally.",
      rationale="A semicolon right after the if condition makes the body empty, so the intended statement executes regardless of the condition.",
      remediation="Remove the stray semicolon and use a block body.",
      source="https://errorprone.info/bugpattern/EmptyIf",
      re=r"\bif\s*\([^)]*\)\s*;", nc="if (count > 0);", c="if (count > 0) { process(); }"),
    r(id="java-empty-while", type="bug", qual="rel", sev="medium", cwe="",
      title="Empty while loop (busy-wait)",
      desc="`while (cond);` spins with an empty body, burning CPU.",
      rationale="An empty-bodied while loop busy-waits, consuming a core, and often signals a misplaced semicolon.",
      remediation="Use a proper wait/condition, or add the intended loop body.",
      source="https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html",
      re=r"\bwhile\s*\([^)]*\)\s*;", nc="while (!ready);", c="while (!ready) { Thread.sleep(10); }"),
    r(id="java-return-in-finally", type="bug", qual="rel", sev="medium", cwe="",
      title="return inside a finally block",
      desc="A return in finally discards any exception thrown in the try/catch.",
      rationale="A return (or throw) in finally overrides a pending exception or return from the try block, silently swallowing errors.",
      remediation="Move the return out of finally; use finally only for cleanup.",
      source="https://wiki.sei.cmu.edu/confluence/display/java/ERR04-J.+Do+not+complete+abruptly+from+a+finally+block",
      re=r"finally\s*\{[^}]*\breturn\b", nc="} finally { return result; }", c="} finally { stream.close(); }"),
    r(id="java-boolean-return-ternary", type="smell", qual="maint", sev="low", cwe="",
      title="Redundant boolean ternary",
      desc="`cond ? true : false` is just `cond`.",
      rationale="Returning a boolean via a ternary that yields true/false is redundant and harder to read than the condition itself.",
      remediation="Return the boolean expression directly.",
      source="https://errorprone.info/bugpattern/RedundantConditional",
      re=r"\?\s*true\s*:\s*false", nc="return active ? true : false;", c="return active;"),
    r(id="java-runtime-exec-var", type="hotspot", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Runtime.exec with a non-literal command",
      desc="Runtime.getRuntime().exec on a variable can run attacker-controlled commands.",
      rationale="Passing a dynamically built string to Runtime.exec allows OS command injection if any part derives from input; use a fixed argv and validate inputs.",
      remediation="Use ProcessBuilder with a fixed argument list and validate inputs; avoid a shell.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r"Runtime\.getRuntime\(\)\.exec\s*\(\s*[A-Za-z_$]", nc="Runtime.getRuntime().exec(userCommand);", c="Runtime.getRuntime().exec(\"/usr/bin/id\");"),
]
