CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","js");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","javascript"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
def sq(**k):  # javascript source-quality shorthand
    return r(**k)
RULES=[
 r(id="js-no-proto",type="bug",qual="rel",sev="medium",cwe="",title="__proto__ mutation",
   desc="Assigning __proto__ mutates the prototype chain and hurts performance.",
   rationale="Writing __proto__ changes an object's prototype at runtime, deoptimizing the object and risking prototype-pollution bugs.",
   remediation="Use Object.create / Object.setPrototypeOf deliberately, or restructure to avoid it.",
   source="https://eslint.org/docs/latest/rules/no-proto",
   re=r"\.__proto__\b",nc="obj.__proto__ = base;",c="Object.setPrototypeOf(obj, base);"),
 r(id="js-no-iterator",type="smell",qual="maint",sev="low",cwe="",title="Legacy __iterator__ property",
   desc="__iterator__ is a non-standard legacy property; use Symbol.iterator.",
   rationale="__iterator__ was a SpiderMonkey extension and is not standard; the iteration protocol uses Symbol.iterator.",
   remediation="Implement [Symbol.iterator] instead.",
   source="https://eslint.org/docs/latest/rules/no-iterator",
   re=r"\.__iterator__\b",nc="coll.__iterator__ = gen;",c="coll[Symbol.iterator] = gen;"),
 r(id="js-no-extend-native",type="bug",qual="rel",sev="medium",cwe="",title="Extending a native prototype",
   desc="Adding to Array/Object/String prototypes can collide with other code and future APIs.",
   rationale="Monkey-patching built-in prototypes creates global side effects that break other libraries and can clash with new language features.",
   remediation="Use a standalone helper function instead of extending the native prototype.",
   source="https://eslint.org/docs/latest/rules/no-extend-native",
   re=r"\b(Array|Object|String|Number|Function|Boolean)\.prototype\.[A-Za-z_$][\w$]*\s*=",
   nc="Array.prototype.first = function () { return this[0]; };",c="function first(a) { return a[0]; }"),
 r(id="js-no-double-negation",type="smell",qual="maint",sev="low",cwe="",title="Double-negation boolean cast",
   desc="`!!x` is an obscure way to coerce to boolean.",
   rationale="!! works but is cryptic; Boolean(x) states the intent to coerce.",
   remediation="Use Boolean(x), or rely on the truthiness directly.",
   source="https://eslint.org/docs/latest/rules/no-implicit-coercion",
   re=r"!!\s*[A-Za-z_$(]",nc="const ok = !!value;",c="const ok = Boolean(value);"),
 r(id="js-no-new-object",type="smell",qual="maint",sev="low",cwe="",title="Object constructor",
   desc="`new Object()` is verbose; use an object literal.",
   rationale="An object literal {} is clearer and avoids the rarely-intended Object() coercion behavior.",
   remediation="Use an object literal {} instead of the Object constructor.",
   source="https://eslint.org/docs/latest/rules/no-new-object",
   re=r"\bnew\s+Object\s*\(",nc="const o = new Object();",c="const o = {};"),
 r(id="js-no-useless-concat",type="smell",qual="maint",sev="info",cwe="",title="Concatenation of two literals",
   desc="Concatenating two string literals should be a single literal.",
   rationale="\"a\" + \"b\" can be written \"ab\"; the concatenation is dead work and noise.",
   remediation="Merge the adjacent string literals.",
   source="https://eslint.org/docs/latest/rules/no-useless-concat",
   re=r"['\"]\s*\+\s*['\"]",nc='const s = "foo" + "bar";',c='const s = "foobar";'),
 r(id="js-no-constant-condition",type="bug",qual="rel",sev="medium",cwe="",title="Constant condition",
   desc="`if (true)` / `while (false)` has a constant test and dead branches.",
   rationale="A literal boolean condition means one branch is dead code; it is usually a leftover from debugging.",
   remediation="Use a real condition, or remove the dead branch.",
   source="https://eslint.org/docs/latest/rules/no-constant-condition",
   re=r"\b(if|while)\s*\(\s*(true|false)\s*\)",nc="if (true) { render(); }",c="if (ready) { render(); }"),
 r(id="js-use-isnan",type="bug",qual="rel",sev="high",cwe="",title="Comparison with NaN",
   desc="`x === NaN` is always false; use Number.isNaN.",
   rationale="NaN is not equal to anything including itself, so any == / === comparison with NaN is always false.",
   remediation="Use Number.isNaN(x).",
   source="https://eslint.org/docs/latest/rules/use-isnan",
   re=r"[!=]==?\s*NaN\b|\bNaN\s*[!=]==?",nc="if (total === NaN) return;",c="if (Number.isNaN(total)) return;"),
 r(id="js-no-compare-neg-zero",type="bug",qual="rel",sev="low",cwe="",title="Comparison with -0",
   desc="`x === -0` does not distinguish -0 from 0; use Object.is.",
   rationale="=== treats -0 and 0 as equal, so comparing to -0 never detects negative zero; Object.is does.",
   remediation="Use Object.is(x, -0) if you truly need to detect negative zero.",
   source="https://eslint.org/docs/latest/rules/no-compare-neg-zero",
   re=r"[!=]==?\s*-0\b",nc="if (delta === -0) reset();",c="if (Object.is(delta, -0)) reset();"),
 r(id="js-no-async-promise-executor",type="bug",qual="rel",sev="medium",cwe="",title="async Promise executor",
   desc="An async function passed to new Promise swallows rejections.",
   rationale="Errors thrown in an async executor reject the async function's own promise, not the constructed one, so they are lost.",
   remediation="Use a synchronous executor, or wrap the async logic differently.",
   source="https://eslint.org/docs/latest/rules/no-async-promise-executor",
   re=r"new\s+Promise\s*\(\s*async\b",nc="new Promise(async (resolve) => { resolve(await f()); });",c="new Promise((resolve) => { f().then(resolve); });"),
 r(id="js-no-template-in-regular-string",type="bug",qual="rel",sev="low",cwe="",title="Template placeholder in a normal string",
   desc="`${...}` inside a single/double-quoted string is a literal, not interpolation.",
   rationale="Template placeholders only work in backtick strings; in a quoted string the ${...} is emitted verbatim, usually a mistake.",
   remediation="Use a backtick template literal, or build the string explicitly.",
   source="https://eslint.org/docs/latest/rules/no-template-curly-in-string",
   re=r"['\"][^'\"]*\$\{[^'\"]*['\"]",nc='const m = "Hi ${name}";',c="const m = `Hi ${name}`;"),
 r(id="js-no-void",type="smell",qual="maint",sev="low",cwe="",title="void 0 for undefined",
   desc="`void 0` is an obscure way to write undefined.",
   rationale="void 0 evaluates to undefined but is cryptic; the undefined literal is clearer and, since ES5, safe.",
   remediation="Use undefined.",
   source="https://eslint.org/docs/latest/rules/no-void",
   re=r"\bvoid\s+0\b",nc="return void 0;",c="return undefined;"),
 r(id="js-dot-notation",type="smell",qual="maint",sev="info",cwe="",title="Bracket access with a literal key",
   desc="`obj[\"name\"]` for a valid identifier reads better as `obj.name`.",
   rationale="Bracket notation with a constant identifier string is noisier than dot notation and defeats some tooling.",
   remediation="Use dot notation for identifier keys.",
   source="https://eslint.org/docs/latest/rules/dot-notation",
   re=r"\[\s*['\"][A-Za-z_$][\w$]*['\"]\s*\]",nc='const v = cfg["timeout"];',c="const v = cfg.timeout;"),
 r(id="js-prefer-exponentiation",type="smell",qual="maint",sev="info",cwe="",title="Math.pow over ** operator",
   desc="`Math.pow(x, y)` can be the ** operator.",
   rationale="The exponentiation operator ** is more concise and readable than Math.pow.",
   remediation="Use x ** y.",
   source="https://eslint.org/docs/latest/rules/prefer-exponentiation-operator",
   re=r"\bMath\.pow\s*\(",nc="const area = Math.pow(r, 2);",c="const area = r ** 2;"),
 r(id="js-no-new-symbol",type="bug",qual="rel",sev="medium",cwe="",title="new Symbol()",
   desc="Symbol is not a constructor; `new Symbol()` throws.",
   rationale="Symbol must be called as a function; new Symbol() throws a TypeError at runtime.",
   remediation="Call Symbol() without new.",
   source="https://eslint.org/docs/latest/rules/no-new-symbol",
   re=r"\bnew\s+Symbol\s*\(",nc='const s = new Symbol("id");',c='const s = Symbol("id");'),
 r(id="js-no-obj-calls",type="bug",qual="rel",sev="high",cwe="",title="Calling a non-callable global",
   desc="Math/JSON/Reflect/Atomics are namespaces, not functions; calling them throws.",
   rationale="Math(), JSON(), Reflect(), and Atomics() are not callable and throw a TypeError.",
   remediation="Call a method on the namespace, e.g. Math.max(...).",
   source="https://eslint.org/docs/latest/rules/no-obj-calls",
   re=r"\b(Math|JSON|Reflect|Atomics)\s*\(",nc="const x = Math();",c="const x = Math.max(a, b);"),
 r(id="js-no-global-assign",type="bug",qual="rel",sev="medium",cwe="",title="Assignment to a read-only global",
   desc="Assigning to undefined/NaN/Infinity is a bug (no-op or error).",
   rationale="undefined, NaN, and Infinity are read-only globals; assigning to them silently fails or throws in strict mode.",
   remediation="Use a differently named variable.",
   source="https://eslint.org/docs/latest/rules/no-global-assign",
   re=r"\b(undefined|NaN|Infinity)\s*=\s*[^=]",nc="undefined = 0;",c="const missing = 0;"),
 r(id="ts-no-nocheck",type="smell",qual="maint",sev="low",cwe="",title="@ts-nocheck directive",
   desc="`@ts-nocheck` disables type checking for the whole file.",
   rationale="@ts-nocheck turns off all type checking in the file, hiding real errors indefinitely.",
   remediation="Remove @ts-nocheck and fix the underlying type errors.",
   source="https://typescript-eslint.io/rules/ban-ts-comment/",
   re=r"@ts-nocheck\b",nc="// @ts-nocheck",c="// @ts-check",tags=["sast","typescript"],skip=""),
 r(id="ts-no-inferrable-types",type="smell",qual="maint",sev="low",cwe="",title="Inferrable type annotation",
   desc="An explicit primitive type on a literal initializer is redundant.",
   rationale="TypeScript infers the type of a literal initializer; annotating it adds noise without value.",
   remediation="Drop the annotation and let inference apply.",
   source="https://typescript-eslint.io/rules/no-inferrable-types/",
   re=r":\s*(number|string|boolean)\s*=\s*(\d|['\"]|true|false)",nc="let retries: number = 3;",c="let retries = 3;",tags=["sast","typescript"]),
 r(id="ts-no-empty-interface",type="smell",qual="maint",sev="low",cwe="",title="Empty interface",
   desc="An empty interface `{}` is equivalent to any object and usually a mistake.",
   rationale="An interface with no members imposes no constraints and behaves like {} or a supertype alias, which is rarely intended.",
   remediation="Add members, use a type alias, or extend the intended type.",
   source="https://typescript-eslint.io/rules/no-empty-interface/",
   re=r"\binterface\s+\w+\s*\{\s*\}",nc="interface Opts {}",c="interface Opts { retries: number; }",tags=["sast","typescript"]),
 r(id="ts-array-type-generic",type="smell",qual="maint",sev="info",cwe="",title="Array<T> over T[]",
   desc="`Array<T>` reads more heavily than the shorthand `T[]`.",
   rationale="For simple element types the T[] shorthand is the idiomatic, more readable form.",
   remediation="Use T[] for simple element types.",
   source="https://typescript-eslint.io/rules/array-type/",
   re=r"\bArray<",nc="const ids: Array<string> = [];",c="const ids: string[] = [];",tags=["sast","typescript"]),
]
