# Clean-room PHP language-pack rules. Each pattern is intentionally limited to a single,
# reviewable source-line shape; rules that require data flow remain outside this pack.
CC = "commentOnlyLine"

SOURCES = {
    "bugs": "https://www.php.net/manual/en/language.operators.comparison.php",
    "err": "https://www.php.net/manual/en/language.exceptions.php",
    "res": "https://www.php.net/manual/en/language.oop5.decon.php",
    "inj": "https://owasp.org/www-community/attacks/SQL_Injection",
    "crypto": "https://www.php.net/manual/en/book.password.php",
    "authz": "https://owasp.org/www-project-top-ten/",
    "hotspot": "https://www.php.net/manual/en/security.php",
    "api": "https://www.php.net/manual/en/funcref.php",
    "types": "https://www.php.net/manual/en/language.types.declarations.php",
    "perf": "https://www.php.net/manual/en/language.generators.overview.php",
    "maint": "https://www.php-fig.org/psr/psr-12/",
}

DEFAULTS = {
    "bugs": ("bug", "rel", "medium", "CWE-682"),
    "err": ("smell", "maint", "medium", ""),
    "res": ("smell", "maint", "medium", "CWE-404"),
    "inj": ("vuln", "sec", "high", "CWE-74"),
    "crypto": ("hotspot", "sec", "high", "CWE-327"),
    "authz": ("hotspot", "sec", "high", "CWE-862"),
    "hotspot": ("hotspot", "sec", "medium", "CWE-489"),
    "api": ("smell", "maint", "low", ""),
    "types": ("smell", "maint", "medium", ""),
    "perf": ("smell", "maint", "low", ""),
    "maint": ("smell", "maint", "low", ""),
}

RATIONALES = {
    "bugs": "This construct can yield a surprising result or fail independently of the surrounding business logic.",
    "err": "This error-handling form loses information or obscures the program's recovery behavior.",
    "res": "This resource-ownership form makes prompt and deterministic cleanup easy to omit.",
    "inj": "This line crosses an interpreter or I/O boundary with dynamic data and needs a structured alternative.",
    "crypto": "This security-sensitive primitive or parameter requires review against the intended protection goal.",
    "authz": "This authorization boundary needs an explicit least-privilege decision.",
    "hotspot": "This line changes a security-sensitive runtime behavior and requires deliberate review.",
    "api": "This API has a clearer or safer PHP alternative for ordinary application code.",
    "types": "This form weakens PHP's useful type guarantees or defers a mismatch until runtime.",
    "perf": "This form performs avoidable work or allocation for a common PHP operation.",
    "maint": "This syntax increases reading or maintenance cost without conveying additional intent.",
}

REMEDIATIONS = {
    "bugs": "Use the explicit, checked PHP form demonstrated by the compliant example.",
    "err": "Preserve the throwable or make the failure path explicit.",
    "res": "Close or release the resource through a bounded owner on every path.",
    "inj": "Use a structured API for the sink, validate untrusted values, and apply context-appropriate encoding or binding.",
    "crypto": "Use a current password or cryptographic API with reviewed parameters.",
    "authz": "Check the authenticated actor's required role, capability, tenant, or ownership before acting.",
    "hotspot": "Restrict the behavior or document and review the boundary before enabling it.",
    "api": "Use the modern PHP API shown in the compliant example.",
    "types": "Declare and preserve the narrowest useful type at this boundary.",
    "perf": "Use the direct operation shown in the compliant example.",
    "maint": "Prefer the simpler, explicit PHP form shown in the compliant example.",
}


def r(fam, ident, title, regex, nc, c, *, cwe=None, source=None, remediation=None, type=None, qual=None, sev=None):
    dt, dq, ds, dc = DEFAULTS[fam]
    weakness = dc if cwe is None else cwe
    concept_source = source or ("https://cwe.mitre.org/data/definitions/" + weakness[4:] + ".html" if weakness else SOURCES[fam])
    return {
        "id": "php:" + ident, "lang": "php", "type": type or dt, "qual": qual or dq,
        "sev": sev or ds, "cwe": weakness, "owasp": "",
        "tags": ["sast", "php", fam], "effort": 15, "title": title,
        "desc": "Detects " + title.lower() + " in PHP source.",
        "cat_desc": "Detects " + title.lower() + " in PHP source.",
        "rationale": RATIONALES[fam], "remediation": remediation or REMEDIATIONS[fam],
        "source": concept_source, "re": regex, "nc": nc, "c": c, "skip": CC,
        "detection": "pattern",
    }


RULES = [
    # bugs (30)
    r("bugs", "loose-comparison", "Loose comparison", r"[^=!]\s*==\s*[^=]", '$ok = $input == "1";', '$ok = $input === "1";', cwe="CWE-704"),
    r("bugs", "loose-inequality", "Loose inequality", r"[^=!]\s*!=\s*[^=]", '$ok = $input != "1";', '$ok = $input !== "1";', cwe="CWE-704"),
    r("bugs", "assignment-in-condition", "Assignment in condition", r"\b(if|while)\s*\(\s*\$[A-Za-z_]\w*\s*=[^=]", 'if ($ready = load()) work();', 'if (($ready = load()) !== null) work();'),
    r("bugs", "constant-true-condition", "Constant true condition", r"\b(if|while)\s*\(\s*true\s*\)", 'if (true) work();', 'if ($ready) work();'),
    r("bugs", "constant-false-condition", "Constant false condition", r"\b(if|while)\s*\(\s*false\s*\)", 'while (false) work();', 'while ($pending) work();'),
    r("bugs", "self-assignment", "Self assignment", r"(?:\$count\s*=\s*\$count|\$value\s*=\s*\$value|\$result\s*=\s*\$result)\s*;", '$count = $count;', '$this->count = $count;'),
    r("bugs", "self-comparison", "Self equality comparison", r"(?:\$value\s*={2,3}\s*\$value|\$count\s*={2,3}\s*\$count|\$result\s*={2,3}\s*\$result)", 'if ($value === $value) work();', 'if ($value === $expected) work();'),
    r("bugs", "division-by-zero", "Literal division by zero", r"/\s*0(?:\.0)?\b", '$ratio = $total / 0;', '$ratio = $total / $count;'),
    r("bugs", "modulo-by-zero", "Literal modulo by zero", r"%\s*0\b", '$bucket = $id % 0;', '$bucket = $id % $size;'),
    r("bugs", "negative-array-index", "Negative array index", r"\[\s*-\s*\d+\s*\]", '$first = $items[-1];', '$last = $items[count($items) - 1];'),
    r("bugs", "array-key-exists-null", "array_key_exists called with null array", r"array_key_exists\s*\([^,]+,\s*null\s*\)", 'array_key_exists("id", null);', 'array_key_exists("id", $input);'),
    r("bugs", "in-array-loose", "in_array without strict comparison", r"in_array\s*\([^,]+,\s*[^,\)]+\s*\)", 'in_array($id, $ids);', 'in_array($id, $ids, true);'),
    r("bugs", "array-search-loose", "array_search without strict comparison", r"array_search\s*\([^,]+,\s*[^,\)]+\s*\)", 'array_search($id, $ids);', 'array_search($id, $ids, true);'),
    r("bugs", "strpos-truthiness", "strpos result used as truth value", r"\bif\s*\(\s*strpos\s*\([^)]*\)\s*\)", 'if (strpos($path, "/admin")) allow();', 'if (strpos($path, "/admin") !== false) allow();'),
    r("bugs", "array-search-truthiness", "array_search result used as truth value", r"\bif\s*\(\s*array_search\s*\([^)]*\)\s*\)", 'if (array_search($id, $ids)) remove();', 'if (array_search($id, $ids, true) !== false) remove();'),
    r("bugs", "empty-string-zero", "empty called on numeric zero", r"empty\s*\(\s*0\s*\)", 'if (empty(0)) fail();', 'if (0 === 0) pass();'),
    r("bugs", "switch-loose-case", "Switch statement uses loose matching", r"\bswitch\s*\(", 'switch ($state) { case "1": work(); }', 'match ($state) { "1" => work() };'),
    r("bugs", "float-equality", "Floating-point equality comparison", r"\$[A-Za-z_]\w*\s*={2,3}\s*\d+\.\d+", 'if ($ratio === 0.1) work();', 'if (abs($ratio - 0.1) < 0.0001) work();'),
    r("bugs", "count-null", "count called on null", r"count\s*\(\s*null\s*\)", '$size = count(null);', '$size = count($items);'),
    r("bugs", "implode-legacy-order", "Legacy implode argument order", r"implode\s*\(\s*\$[A-Za-z_]\w*\s*,\s*['\"]", '$text = implode($items, ",");', '$text = implode(",", $items);'),
    r("bugs", "substr-offset-outside-literal", "substr offset outside literal", r"substr\s*\(\s*['\"][^'\"]{1,4}['\"]\s*,\s*(?:[5-9]|[1-9]\d+)", '$name = substr("abc", 5);', '$name = substr("abc", 1);'),
    r("bugs", "range-zero-step", "Range with zero step", r"range\s*\([^,]+,\s*[^,]+,\s*0\s*\)", '$values = range(1, 5, 0);', '$values = range(1, 5, 1);'),
    r("bugs", "array-rand-empty", "array_rand called on literal empty array", r"array_rand\s*\(\s*\[\s*\]\s*\)", '$key = array_rand([]);', '$key = array_rand($items);'),
    r("bugs", "json-last-error-ignored", "json_decode result checked without JSON_THROW_ON_ERROR", r"json_decode\s*\(\s*\$[A-Za-z_]\w*\s*\)\s*;", '$data = json_decode($body);', '$data = json_decode($body, true, 512, JSON_THROW_ON_ERROR);'),
    r("bugs", "unreachable-after-return", "Statement after return", r"\breturn\b[^;]*;\s*\S+", 'return $value; save();', 'save(); return $value;'),
    r("bugs", "duplicate-array-key", "Duplicate literal array key", r"(?:['\"]host['\"]\s*=>[^,]+,\s*['\"]host['\"]\s*=>|['\"]id['\"]\s*=>[^,]+,\s*['\"]id['\"]\s*=>)", '$cfg = ["host" => $a, "host" => $b];', '$cfg = ["host" => $a, "port" => $b];'),
    r("bugs", "break-zero-level", "Break with zero level", r"\bbreak\s+0\s*;", 'while ($ready) { break 0; }', 'while ($ready) { break; }'),
    r("bugs", "continue-zero-level", "Continue with zero level", r"\bcontinue\s+0\s*;", 'while ($ready) { continue 0; }', 'while ($ready) { continue; }'),
    r("bugs", "assert-false", "Assertion with constant false", r"assert\s*\(\s*false\s*\)", 'assert(false);', 'assert($valid);'),
    r("bugs", "isset-array-key-typo", "isset used with literal empty key", r"isset\s*\(\s*\$[A-Za-z_]\w*\[['\"]{2}\]\s*\)", 'isset($data[""]);', 'isset($data["id"]);'),

    # err (10)
    r("err", "empty-catch", "Empty catch block", r"catch\s*\([^)]*\)\s*\{\s*\}", 'try { work(); } catch (Throwable $e) {}', 'try { work(); } catch (Throwable $e) { throw $e; }'),
    r("err", "catch-throwable", "Catch of Throwable", r"catch\s*\(\s*Throwable\s+\$", 'catch (Throwable $error) { recover(); }', 'catch (RuntimeException $error) { recover(); }'),
    r("err", "catch-error", "Catch of Error", r"catch\s*\(\s*Error\s+\$", 'catch (Error $error) { recover(); }', 'catch (Exception $error) { recover(); }'),
    r("err", "error-suppression", "Error suppression operator", r"@\s*[A-Za-z_]\w*\s*\(", '$data = @file_get_contents($path);', '$data = file_get_contents($path);'),
    r("err", "die-in-library", "die call in application code", r"\bdie\s*\(", 'die("failed");', 'throw new RuntimeException("failed");'),
    r("err", "exit-in-library", "exit call in application code", r"\bexit\s*(\(|;)", 'exit(1);', 'throw new RuntimeException("failed");'),
    r("err", "throw-message-only", "Exception wrapping loses previous throwable", r"throw\s+new\s+\w+Exception\s*\(\s*\$[A-Za-z_]\w*->getMessage\s*\(", 'throw new RuntimeException($error->getMessage());', 'throw new RuntimeException("load failed", 0, $error);'),
    r("err", "return-in-finally", "Return from finally block", r"finally\s*\{[^}]*\breturn\b", 'try { load(); } finally { return $fallback; }', 'try { load(); } finally { close(); }'),
    r("err", "trigger-error", "User-triggered PHP error", r"trigger_error\s*\(", 'trigger_error("bad input");', 'throw new InvalidArgumentException("bad input");'),
    r("err", "set-error-handler-empty", "Empty custom error handler", r"set_error_handler\s*\(\s*function\s*\([^)]*\)\s*\{\s*\}", 'set_error_handler(function ($n) {});', 'set_error_handler(function ($n) { throw new ErrorException(); });'),

    # res (6)
    r("res", "fopen-handle-review", "File handle acquisition", r"^\s*\$[A-Za-z_]\w*\s*=\s*fopen\s*\(", '$handle = fopen($path, "rb");', 'file_get_contents($path);', type="hotspot", qual="sec", cwe="CWE-404"),
    r("res", "curl-handle-review", "cURL handle acquisition", r"^\s*\$[A-Za-z_]\w*\s*=\s*curl_init\s*\(", '$curl = curl_init($url);', '$body = file_get_contents($validatedUrl);', type="hotspot", qual="sec", cwe="CWE-404"),
    r("res", "socket-handle-review", "Socket handle acquisition", r"^\s*\$[A-Za-z_]\w*\s*=\s*socket_create\s*\(", '$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);', '$client = new ManagedSocket($address);', type="hotspot", qual="sec", cwe="CWE-404"),
    r("res", "mysqli-connection-review", "MySQLi connection acquisition", r"^\s*\$[A-Za-z_]\w*\s*=\s*new\s+mysqli\s*\(", '$db = new mysqli($host, $user, $pass);', '$db = $pool->connection();', type="hotspot", qual="sec", cwe="CWE-404"),
    r("res", "pdo-cursor-review", "PDO cursor acquisition", r"\$[A-Za-z_]\w*\s*=\s*\$[A-Za-z_]\w*->query\s*\([^;]*\);\s*$", '$rows = $pdo->query($sql);', '$rows = $repository->all();', type="hotspot", qual="sec", cwe="CWE-404"),
    r("res", "tempnam-direct-write", "Temporary path used without atomic creation", r"file_put_contents\s*\(\s*tempnam\s*\(", 'file_put_contents(tempnam("/tmp", "job"), $body);', '$path = tempnam(sys_get_temp_dir(), "job"); file_put_contents($path, $body);'),

    # inj (25)
    r("inj", "sql-concat", "SQL statement built by concatenation", r"(?i)(query|exec|prepare)\s*\([^;]*(SELECT|INSERT|UPDATE|DELETE)[^;]*\.\s*\$", '$db->query("SELECT * FROM users WHERE id=" . $id);', '$stmt = $db->prepare("SELECT * FROM users WHERE id = ?");', cwe="CWE-89"),
    r("inj", "sql-interpolation", "SQL statement interpolates a variable", r"(?i)(query|exec|prepare)\s*\([^;]*\"(SELECT|INSERT|UPDATE|DELETE)[^\"]*\$", '$db->query("SELECT * FROM users WHERE id=$id");', '$stmt = $db->prepare("SELECT * FROM users WHERE id = ?");', cwe="CWE-89"),
    r("inj", "mysqli-query-request", "mysqli query uses request input", r"mysqli_query\s*\([^;]*\$_(GET|POST|REQUEST)", 'mysqli_query($db, $_GET["sql"]);', '$stmt = $db->prepare("SELECT * FROM users WHERE id = ?");', cwe="CWE-89"),
    r("inj", "pdo-query-request", "PDO query uses request input", r"->query\s*\(\s*\$_(GET|POST|REQUEST)", '$pdo->query($_GET["sql"]);', '$pdo->prepare("SELECT * FROM users");', cwe="CWE-89"),
    r("inj", "eval-usage", "Dynamic code evaluation", r"\beval\s*\(", 'eval($source);', '$data = json_decode($source, true, 512, JSON_THROW_ON_ERROR);', cwe="CWE-95", sev="critical"),
    r("inj", "assert-string", "Concatenated assertion expression", r"assert\s*\(\s*\$[A-Za-z_]\w*(?:\s*\.\s*\$[A-Za-z_]\w*)+", 'assert($prefix . $expression);', 'assert($ready);', cwe="", type="smell", qual="maint", sev="low", source="https://www.php.net/manual/en/function.assert.php", remediation="Pass a Boolean invariant to assert instead of a concatenated string."),
    r("inj", "command-exec", "Dynamic shell command execution", r"\b(shell_exec|exec|system|passthru)\s*\(\s*(?:\$_(?:GET|POST|REQUEST)|\$[A-Za-z_]\w*)", 'shell_exec($command);', 'exec("/usr/bin/id");', cwe="CWE-78", sev="high"),
    r("inj", "backtick-command", "Backtick shell execution", r"`[^`]+`", '$output = `$command`;', '$output = runCommand($command);', cwe="CWE-78", sev="critical"),
    r("inj", "proc-open-string", "proc_open receives command string", r"proc_open\s*\(\s*\$", 'proc_open($command, $spec, $pipes);', 'proc_open(["/usr/bin/convert", $path], $spec, $pipes);', cwe="CWE-78"),
    r("inj", "dynamic-include", "Dynamic include path", r"\b(include|include_once|require|require_once)\s*\(?\s*\$", 'include $page;', 'include __DIR__ . "/pages/home.php";', cwe="CWE-98", sev="critical"),
    r("inj", "include-request", "Include path from request", r"\b(include|require)(_once)?\s*\(?\s*\$_(GET|POST|REQUEST)", 'require $_GET["page"];', 'require __DIR__ . "/config.php";', cwe="CWE-98", sev="critical"),
    r("inj", "unserialize-untrusted", "Unserialize of untrusted input", r"unserialize\s*\(\s*\$_(GET|POST|REQUEST)", '$data = unserialize($_POST["payload"]);', '$data = json_decode($_POST["payload"], true, 512, JSON_THROW_ON_ERROR);', cwe="CWE-502", sev="critical"),
    r("inj", "unserialize-usage", "Native PHP unserialize usage", r"\bunserialize\s*\(", '$data = unserialize($payload);', '$data = json_decode($payload, true, 512, JSON_THROW_ON_ERROR);', cwe="CWE-502"),
    r("inj", "echo-unescaped", "Raw request value echoed", r"\becho\s+\$_(GET|POST|REQUEST)", 'echo $_GET["name"];', 'echo htmlspecialchars($_GET["name"], ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");', cwe="CWE-79"),
    r("inj", "print-unescaped", "Raw request value printed", r"\bprint\s+\$_(GET|POST|REQUEST)", 'print $_GET["name"];', 'print htmlspecialchars($_GET["name"], ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");', cwe="CWE-79"),
    r("inj", "header-injection", "HTTP header built from request input", r"header\s*\([^;]*\$_(GET|POST|REQUEST)", 'header("Location: " . $_GET["next"]);', 'header("Location: /account");', cwe="CWE-113"),
    r("inj", "unvalidated-upload", "Uploaded file movement requires review", r"move_uploaded_file\s*\(\s*\$_FILES", 'move_uploaded_file($_FILES["avatar"]["tmp_name"], $target);', 'move_uploaded_file($validatedUpload->temporaryPath(), $safeTarget);', cwe="CWE-434", type="hotspot", qual="sec"),
    r("inj", "file-read-request-path", "Local file read uses request path", r"(fopen|readfile)\s*\(\s*\$_(GET|POST|REQUEST)", 'readfile($_GET["path"]);', 'readfile($safePath);', cwe="CWE-22"),
    r("inj", "file-write-request-path", "File write uses request path", r"file_put_contents\s*\(\s*\$_(GET|POST|REQUEST)", 'file_put_contents($_POST["path"], $body);', 'file_put_contents($safePath, $body);', cwe="CWE-22"),
    r("inj", "ssrf-file-get-contents", "Request value passed to URL-capable read", r"file_get_contents\s*\(\s*\$_(GET|POST|REQUEST)", 'file_get_contents($_GET["url"]);', 'file_get_contents("https://api.example.test/status");', cwe="CWE-918", type="hotspot", qual="sec"),
    r("inj", "curl-url-request", "cURL URL uses request input", r"CURLOPT_URL\s*,\s*\$_(GET|POST|REQUEST)", 'curl_setopt($curl, CURLOPT_URL, $_GET["url"]);', 'curl_setopt($curl, CURLOPT_URL, $allowedUrl);', cwe="CWE-918"),
    r("inj", "xpath-concat", "XPath expression built by concatenation", r"xpath\s*\([^;]*\.\s*\$", '$query = xpath("//user[name=" . $name . "]");', '$query = xpath("//user");', cwe="CWE-643"),
    r("inj", "ldap-filter-concat", "LDAP filter built by concatenation", r"ldap_search\s*\([^;]*\.\s*\$", 'ldap_search($conn, $base, "(uid=" . $uid . ")");', 'ldap_search($conn, $base, "(objectClass=person)");', cwe="CWE-90"),
    r("inj", "preg-replace-e", "preg_replace with eval modifier", r"preg_replace\s*\([^,]*['\"][^'\"]*/e", 'preg_replace("/x/e", $replacement, $text);', 'preg_replace("/x/", $replacement, $text);', cwe="CWE-95"),
    r("inj", "open-redirect-request", "Redirect uses request target", r"header\s*\([^;]*Location:[^;]*\$_(GET|POST|REQUEST)", 'header("Location: " . $_GET["next"]);', 'header("Location: /home");', cwe="CWE-601"),

    # crypto (12)
    r("crypto", "weak-password-hash", "Weak password hash", r"\b(md5|sha1|crypt)\s*\(\s*\$?(password|pass|pwd)", '$hash = md5($password);', '$hash = password_hash($password, PASSWORD_ARGON2ID);', cwe="CWE-916"),
    r("crypto", "md5-usage", "MD5 digest usage", r"\bmd5\s*\(", '$digest = md5($data);', '$digest = hash("sha256", $data);', cwe="CWE-327"),
    r("crypto", "sha1-usage", "SHA-1 digest usage", r"\bsha1\s*\(", '$digest = sha1($data);', '$digest = hash("sha256", $data);', cwe="CWE-327"),
    r("crypto", "weak-hash-algorithm", "Weak hash algorithm string", r"hash\s*\(\s*['\"](md5|sha1)['\"]", '$digest = hash("sha1", $data);', '$digest = hash("sha256", $data);', cwe="CWE-327"),
    r("crypto", "weak-cipher", "Weak symmetric cipher", r"openssl_encrypt\s*\([^,]+,\s*['\"](des|rc2|rc4|bf-)", '$cipher = openssl_encrypt($data, "des-ede3-cbc", $key);', '$cipher = openssl_encrypt($data, "aes-256-gcm", $key, 0, $iv, $tag);', cwe="CWE-327"),
    r("crypto", "ecb-mode", "ECB encryption mode", r"openssl_encrypt\s*\([^,]+,\s*['\"]aes-\d+-ecb['\"]", '$cipher = openssl_encrypt($data, "aes-128-ecb", $key);', '$cipher = openssl_encrypt($data, "aes-256-gcm", $key, 0, $iv, $tag);', cwe="CWE-327"),
    r("crypto", "insecure-random", "Predictable random source", r"\b(rand|mt_rand|lcg_value)\s*\(", '$token = mt_rand();', '$token = bin2hex(random_bytes(32));', cwe="CWE-338"),
    r("crypto", "openssl-random-pseudo", "Legacy OpenSSL pseudo-random bytes", r"openssl_random_pseudo_bytes\s*\(", '$token = openssl_random_pseudo_bytes(32);', '$token = random_bytes(32);', cwe="CWE-338"),
    r("crypto", "static-iv", "Static encryption IV", r"openssl_encrypt\s*\([^;]*['\"][^'\"]{8,}['\"]\s*\)", '$cipher = openssl_encrypt($data, "aes-256-cbc", $key, 0, "fixed-vector-123");', '$cipher = openssl_encrypt($data, "aes-256-gcm", $key, 0, $iv, $tag);', cwe="CWE-329"),
    r("crypto", "password-verify-loose", "Password verification uses loose comparison", r"password_verify\s*\([^)]*\)\s*==", 'if (password_verify($pass, $hash) == true) allow();', 'if (password_verify($pass, $hash)) allow();', cwe="CWE-697"),
    r("crypto", "password-hash-bcrypt-low-cost", "Bcrypt cost below ten", r"password_hash\s*\([^;]*PASSWORD_BCRYPT[^;]*['\"]cost['\"]\s*=>\s*[1-9]\b", '$hash = password_hash($pass, PASSWORD_BCRYPT, ["cost" => 8]);', '$hash = password_hash($pass, PASSWORD_ARGON2ID);', cwe="CWE-916"),
    r("crypto", "tls-peer-verification-off", "TLS peer verification disabled", r"CURLOPT_SSL_VERIFYPEER\s*,\s*(false|0)", 'curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);', 'curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, true);', cwe="CWE-295"),

    # authz (10)
    r("authz", "allow-all-role", "Wildcard authorization role", r"(hasRole|hasPermission)\s*\(\s*['\"]\*['\"]", 'if ($user->hasRole("*")) allow();', 'if ($user->hasRole("admin")) allow();'),
    r("authz", "admin-name-check", "Authorization by admin user name", r"\$[A-Za-z_]\w*->(name|username)\s*={2,3}\s*['\"]admin['\"]", 'if ($user->name === "admin") allow();', 'if ($user->hasRole("admin")) allow();'),
    r("authz", "request-role-trust", "Role trusted from request", r"\$_(GET|POST|REQUEST)\[['\"]role['\"]\]", '$role = $_POST["role"];', '$role = $session->user()->role();'),
    r("authz", "request-user-id-trust", "User identifier trusted from request", r"\$_(GET|POST|REQUEST)\[['\"]user_?id['\"]\]", '$userId = $_GET["user_id"];', '$userId = $session->userId();'),
    r("authz", "is-admin-default-true", "Administrator flag defaults to true", r"\$isAdmin\s*=\s*true", '$isAdmin = true;', '$isAdmin = $user->hasRole("admin");'),
    r("authz", "authorization-disabled", "Authorization explicitly disabled", r"(authorize|authorization|authz)\s*=\s*false", '$authorization = false;', '$authorization = $policy->allows($user, $action);'),
    r("authz", "ownership-check-missing", "Object loaded by request id", r"(find|load|get)\w*\s*\(\s*\$_(GET|POST|REQUEST)\[['\"]id['\"]\]", '$order = $repo->find($_GET["id"]);', '$order = $repo->findForUser($session->userId(), $id);', cwe="CWE-639"),
    r("authz", "mass-assignment-request", "Mass assignment from request", r"(fill|update|create)\s*\(\s*\$_(POST|REQUEST)", '$user->fill($_POST);', '$user->fill(["displayName" => $name]);', cwe="CWE-915"),
    r("authz", "guard-bypass", "Route guard bypass", r"->withoutMiddleware\s*\(", 'Route::get("/admin", $handler)->withoutMiddleware("auth");', 'Route::get("/admin", $handler)->middleware("auth");'),
    r("authz", "public-admin-route", "Public admin route", r"Route::(get|post|put|delete)\s*\(\s*['\"]/admin[^;]*\);\s*$", 'Route::get("/admin", $handler);', 'Route::get($adminPath, $handler)->middleware("auth");'),

    # hotspot (15)
    r("hotspot", "display-errors-on", "Display errors enabled", r"ini_set\s*\(\s*['\"]display_errors['\"]\s*,\s*['\"]?(1|on|true)", 'ini_set("display_errors", "1");', 'ini_set("display_errors", "0");', cwe="CWE-209"),
    r("hotspot", "display-startup-errors-on", "Startup error display enabled", r"ini_set\s*\(\s*['\"]display_startup_errors['\"]\s*,\s*['\"]?(1|on|true)", 'ini_set("display_startup_errors", "1");', 'ini_set("display_startup_errors", "0");', cwe="CWE-209"),
    r("hotspot", "phpinfo-usage", "phpinfo output", r"\bphpinfo\s*\(", 'phpinfo();', 'renderHealthCheck();', cwe="CWE-200"),
    r("hotspot", "var-dump-output", "var_dump output", r"\bvar_dump\s*\(", 'var_dump($config);', 'logger()->debug("config loaded");', cwe="CWE-532"),
    r("hotspot", "print-r-output", "print_r output", r"\bprint_r\s*\(", 'print_r($config);', 'logger()->debug("config loaded");', cwe="CWE-532"),
    r("hotspot", "extract-usage", "extract imports dynamic variables", r"\bextract\s*\(", 'extract($_GET);', '$name = $_GET["name"];', cwe="CWE-749"),
    r("hotspot", "register-globals", "register_globals enabled", r"register_globals\s*=\s*(On|1|true)", 'register_globals = On;', 'register_globals = Off;', cwe="CWE-749"),
    r("hotspot", "allow-url-include", "URL include enabled", r"allow_url_include\s*=\s*(On|1|true)", 'allow_url_include = On;', 'allow_url_include = Off;', cwe="CWE-98"),
    r("hotspot", "allow-url-fopen", "URL fopen enabled", r"allow_url_fopen\s*=\s*(On|1|true)", 'allow_url_fopen = On;', 'allow_url_fopen = Off;', cwe="CWE-939"),
    r("hotspot", "session-cookie-secure-off", "Secure session cookie disabled", r"ini_set\s*\(\s*['\"]session\.cookie_secure['\"]\s*,\s*(false|0)", 'ini_set("session.cookie_secure", false);', 'ini_set("session.cookie_secure", true);', cwe="CWE-614"),
    r("hotspot", "session-cookie-httponly-off", "HttpOnly session cookie disabled", r"ini_set\s*\(\s*['\"]session\.cookie_httponly['\"]\s*,\s*(false|0)", 'ini_set("session.cookie_httponly", false);', 'ini_set("session.cookie_httponly", true);', cwe="CWE-1004"),
    r("hotspot", "session-use-strict-off", "Strict session mode disabled", r"ini_set\s*\(\s*['\"]session\.use_strict_mode['\"]\s*,\s*(false|0)", 'ini_set("session.use_strict_mode", false);', 'ini_set("session.use_strict_mode", true);', cwe="CWE-384"),
    r("hotspot", "ini-set-runtime", "Runtime PHP configuration change", r"\bini_set\s*\(", 'ini_set("memory_limit", "-1");', '$limit = ini_get("memory_limit");'),
    r("hotspot", "putenv-usage", "Process environment mutation", r"\bputenv\s*\(", 'putenv("PATH=/tmp");', '$path = getenv("PATH");'),
    r("hotspot", "sensitive-log", "Sensitive value written to log", r"(?i)(error_log|logger\(\)->\w+)\s*\([^;]*(password|token|secret|credential)", 'error_log("token=" . $token);', 'error_log("authentication complete");', cwe="CWE-532"),

    # api (30)
    r("api", "mysql-connect", "Removed mysql_connect API", r"\bmysql_connect\s*\(", '$db = mysql_connect($host, $user, $pass);', '$db = new PDO($dsn, $user, $pass);'),
    r("api", "mysql-query", "Removed mysql_query API", r"\bmysql_query\s*\(", 'mysql_query($sql);', '$stmt = $pdo->prepare($sql);'),
    r("api", "each-usage", "Removed each API", r"\beach\s*\(", 'while (each($items)) work();', 'foreach ($items as $item) work();'),
    r("api", "create-function", "Removed create_function API", r"\bcreate_function\s*\(", '$fn = create_function("$x", "return $x;");', '$fn = static fn ($x) => $x;'),
    r("api", "utf8-encode", "Deprecated utf8_encode API", r"\butf8_encode\s*\(", '$text = utf8_encode($text);', '$text = mb_convert_encoding($text, "UTF-8", "ISO-8859-1");'),
    r("api", "utf8-decode", "Deprecated utf8_decode API", r"\butf8_decode\s*\(", '$text = utf8_decode($text);', '$text = mb_convert_encoding($text, "ISO-8859-1", "UTF-8");'),
    r("api", "money-format", "Removed money_format API", r"\bmoney_format\s*\(", '$price = money_format("%i", $amount);', '$price = number_format($amount, 2);'),
    r("api", "split-usage", "Removed split API", r"\bsplit\s*\(", '$parts = split("/", $path);', '$parts = explode("/", $path);'),
    r("api", "ereg-usage", "Removed ereg API", r"\bereg\s*\(", 'ereg("^[a-z]+$", $name);', 'preg_match("/^[a-z]+$/", $name);'),
    r("api", "eregi-usage", "Removed eregi API", r"\beregi\s*\(", 'eregi("^[a-z]+$", $name);', 'preg_match("/^[a-z]+$/i", $name);'),
    r("api", "mcrypt-usage", "Removed mcrypt API", r"\bmcrypt_\w+\s*\(", '$cipher = mcrypt_encrypt($algo, $key, $data, $mode);', '$cipher = openssl_encrypt($data, "aes-256-gcm", $key, 0, $iv, $tag);'),
    r("api", "get-magic-quotes", "Removed magic quotes API", r"\bget_magic_quotes_gpc\s*\(", 'if (get_magic_quotes_gpc()) clean();', '$value = filter_input(INPUT_GET, "name");'),
    r("api", "set-magic-quotes", "Removed magic quotes API", r"\bset_magic_quotes_runtime\s*\(", 'set_magic_quotes_runtime(true);', '$value = filter_input(INPUT_GET, "name");'),
    r("api", "session-register", "Removed session_register API", r"\bsession_register\s*\(", 'session_register("user");', '$_SESSION["user"] = $user;'),
    r("api", "session-unregister", "Removed session_unregister API", r"\bsession_unregister\s*\(", 'session_unregister("user");', 'unset($_SESSION["user"]);'),
    r("api", "session-is-registered", "Removed session_is_registered API", r"\bsession_is_registered\s*\(", 'session_is_registered("user");', 'isset($_SESSION["user"]);'),
    r("api", "get-current-user", "Misleading get_current_user API", r"\bget_current_user\s*\(", '$user = get_current_user();', '$user = posix_getpwuid(posix_geteuid())["name"];'),
    r("api", "date-default-timezone-set", "Global default timezone mutation", r"\bdate_default_timezone_set\s*\(", 'date_default_timezone_set("UTC");', '$clock = new DateTimeZone("UTC");'),
    r("api", "strftime-usage", "Deprecated strftime API", r"\bstrftime\s*\(", '$label = strftime("%Y-%m-%d");', '$label = (new DateTimeImmutable())->format("Y-m-d");'),
    r("api", "gmstrftime-usage", "Deprecated gmstrftime API", r"\bgmstrftime\s*\(", '$label = gmstrftime("%Y-%m-%d");', '$label = (new DateTimeImmutable("now", new DateTimeZone("UTC")))->format("Y-m-d");'),
    r("api", "serialize-usage", "Native serialize API", r"\bserialize\s*\(", '$payload = serialize($data);', '$payload = json_encode($data, JSON_THROW_ON_ERROR);'),
    r("api", "parse-str-no-target", "parse_str without output target", r"\bparse_str\s*\(\s*[^,]+\s*\)", 'parse_str($query);', 'parse_str($query, $params);'),
    r("api", "compact-usage", "compact creates implicit array keys", r"\bcompact\s*\(", '$view = compact("user", "items");', '$view = ["user" => $user, "items" => $items];'),
    r("api", "get-defined-vars", "get_defined_vars exposes ambient state", r"\bget_defined_vars\s*\(", '$values = get_defined_vars();', '$values = ["user" => $user];'),
    r("api", "func-get-args", "func_get_args obscures function signature", r"\bfunc_get_args\s*\(", '$args = func_get_args();', 'function run(string ...$args): void {}'),
    r("api", "debug-backtrace", "debug_backtrace used in application logic", r"\bdebug_backtrace\s*\(", '$trace = debug_backtrace();', '$context = requestContext();'),
    r("api", "get-included-files", "get_included_files used in application logic", r"\bget_included_files\s*\(", '$files = get_included_files();', '$files = $loader->loadedFiles();'),
    r("api", "error-log", "Direct error_log call", r"\berror_log\s*\(", 'error_log("request failed");', 'logger()->error("request failed");'),
    r("api", "set-time-limit", "Runtime execution time change", r"\bset_time_limit\s*\(", 'set_time_limit(0);', '$deadline = $clock->now()->modify("+30 seconds");'),
    r("api", "ignore-user-abort", "Ignore client disconnect", r"\bignore_user_abort\s*\(", 'ignore_user_abort(true);', 'if (connection_aborted()) return;'),

    # types (12)
    r("types", "mixed-parameter", "Mixed function parameter", r"function\s+\w+\s*\([^)]*\bmixed\s+\$", 'function save(mixed $value): void {}', 'function save(string $value): void {}'),
    r("types", "mixed-return", "Mixed function return", r"function\s+\w+\s*\([^)]*\)\s*:\s*mixed\b", 'function load(): mixed {}', 'function load(): User {}'),
    r("types", "untyped-parameter", "Untyped function parameter", r"function\s+\w+\s*\(\s*\$[A-Za-z_]\w*", 'function save($value): void {}', 'function save(string $value): void {}'),
    r("types", "untyped-return", "Function without return type", r"function\s+\w+\s*\([^)]*\)\s*\{", 'function load() { return $user; }', 'function load(): User { return $user; }'),
    r("types", "nullable-bool", "Nullable Boolean state", r"\?bool\s+\$", 'function enabled(?bool $flag): void {}', 'function enabled(bool $flag): void {}'),
    r("types", "nullable-array", "Nullable array parameter", r"\?array\s+\$", 'function save(?array $items): void {}', 'function save(array $items): void {}'),
    r("types", "object-type", "Overly broad object type", r"\bobject\s+\$", 'function handle(object $request): void {}', 'function handle(Request $request): void {}'),
    r("types", "array-type", "Generic array parameter", r"\barray\s+\$", 'function save(array $items): void {}', 'function save(UserList $items): void {}'),
    r("types", "bool-string-union", "Boolean and string union", r"\b(bool\|string|string\|bool)\s+\$", 'function parse(bool|string $value): void {}', 'function parse(string $value): void {}'),
    r("types", "false-union", "False used in return union", r"\)\s*:\s*[A-Za-z_\\]+\|false\b", 'function load(): User|false {}', 'function load(): ?User {}'),
    r("types", "numeric-string-cast", "Numeric request value cast directly", r"\(int\)\s*\$_(GET|POST|REQUEST)", '$id = (int) $_GET["id"];', '$id = filter_input(INPUT_GET, "id", FILTER_VALIDATE_INT);'),
    r("types", "dynamic-property", "Dynamic object property assignment", r"\$[A-Za-z_]\w*->\$[A-Za-z_]\w*\s*=", '$user->$field = $value;', '$user->setDisplayName($value);'),

    # perf (8)
    r("perf", "count-in-loop", "count evaluated in loop condition", r"for\s*\([^;]*;\s*[^;]*count\s*\(", 'for ($i = 0; $i < count($items); $i++) work();', '$count = count($items); for ($i = 0; $i < $count; $i++) work();'),
    r("perf", "array-merge-loop", "array_merge in loop", r"\b(for|foreach|while)\b[^\n]*array_merge\s*\(", 'foreach ($parts as $part) { $all = array_merge($all, $part); }', '$all[] = $part;'),
    r("perf", "in-array-loop", "in_array searched inside loop", r"\b(for|foreach|while)\b[^\n]*in_array\s*\(", 'foreach ($items as $item) { in_array($item, $allowed); }', '$allowedSet = array_flip($allowed);'),
    r("perf", "preg-match-loop", "Regular expression evaluated in loop", r"\b(for|foreach|while)\b[^\n]*preg_match\s*\(", 'foreach ($lines as $line) { preg_match($pattern, $line); }', '$regex = $pattern;'),
    r("perf", "file-get-contents-loop", "File read inside loop", r"\b(for|foreach|while)\b[^\n]*file_get_contents\s*\(", 'foreach ($paths as $path) { file_get_contents($path); }', '$contents = array_map("file_get_contents", $paths);'),
    r("perf", "json-decode-loop", "JSON decoding inside loop", r"\b(for|foreach|while)\b[^\n]*json_decode\s*\(", 'foreach ($rows as $row) { json_decode($row); }', '$decoded = array_map("json_decode", $rows);'),
    r("perf", "array-keys-in-loop", "array_keys allocated in loop", r"\b(for|foreach|while)\b[^\n]*array_keys\s*\(", 'foreach ($rows as $row) { array_keys($row); }', '$keys = array_keys($rows[0]);'),
    r("perf", "sort-for-first", "Full sort used to select first value", r"\bsort\s*\(\s*\$[A-Za-z_]\w*\s*\)", 'sort($scores); $best = $scores[0];', '$best = min($scores);'),

    # maint (21)
    r("maint", "short-open-tag", "Short PHP opening tag", r"^\s*<\?\s+", '<? echo $name; ?>', '<?php echo $name; ?>'),
    r("maint", "closing-tag", "Closing PHP tag in source-only file", r"\?>\s*$", '<?php echo $name; ?>', '<?php final class User {}'),
    r("maint", "var-property", "Legacy var property declaration", r"\bvar\s+\$", 'var $name;', 'private string $name;'),
    r("maint", "else-if-spacing", "Non-idiomatic else if spelling", r"\belse\s+if\s*\(", 'else if ($ready) work();', 'elseif ($ready) work();'),
    r("maint", "array-long-syntax", "Long array syntax", r"\barray\s*\(", '$items = array(1, 2);', '$items = [1, 2];'),
    r("maint", "array-push-single", "array_push used for one item", r"array_push\s*\(\s*\$[A-Za-z_]\w*\s*,\s*[^,\)]+\)", 'array_push($items, $item);', '$items[] = $item;'),
    r("maint", "boolean-literal-comparison", "Boolean compared to literal", r"={2,3}\s*(true|false)\b", 'if ($enabled === true) work();', 'if ($enabled) work();'),
    r("maint", "empty-array-comparison", "Array compared to empty literal", r"\$[A-Za-z_]\w*\s*={2,3}\s*\[\s*\]", 'if ($items === []) work();', 'if (!$items) work();'),
    r("maint", "nested-ternary", "Nested ternary expression", r"\?[^;\n]*\?[^;\n]*:", '$label = $a ? $b ? "x" : "y" : "z";', '$label = match (true) { $a && $b => "x", default => "z" };'),
    r("maint", "ternary-true", "Ternary returning true", r"\?\s*true\s*:\s*false", '$ok = $ready ? true : false;', '$ok = $ready;'),
    r("maint", "ternary-false", "Ternary returning false", r"\?\s*false\s*:\s*true", '$ok = $ready ? false : true;', '$ok = !$ready;'),
    r("maint", "unnecessary-else-return", "Else after return", r"if\s*\([^)]*\)\s*\{[^}]*return[^}]*\}\s*else", 'if ($bad) { return; } else { work(); }', 'if ($bad) { return; } work();'),
    r("maint", "empty-method", "Empty method body", r"function\s+\w+\s*\([^)]*\)\s*\{\s*\}", 'function refresh() {}', 'function refresh(): void { $this->repo->refresh(); }'),
    r("maint", "empty-class", "Empty class body", r"class\s+\w+[^\{]*\{\s*\}", 'class Empty {}', 'class User { public function name(): string { return "x"; } }'),
    r("maint", "magic-number", "Unexplained large numeric literal", r"\b([2-9][0-9]{2,}|1[0-9]{3,})\b", 'if ($seconds > 86400) expire();', 'if ($seconds > SECONDS_PER_DAY) expire();'),
    r("maint", "too-many-parameters", "Function with many parameters", r"function\s+\w+\s*\([^)]*,[^)]*,[^)]*,[^)]*,[^)]*,[^)]*,[^)]*,", 'function connect($a,$b,$c,$d,$e,$f,$g,$h) {}', 'function connect(ConnectionOptions $options): void {}'),
    r("maint", "single-letter-variable", "Single-letter variable name", r"\$[a-z]\s*=", '$x = loadUser();', '$user = loadUser();'),
    r("maint", "global-keyword", "Global state import", r"\bglobal\s+\$", 'global $config;', '$config = $this->config;'),
    r("maint", "goto-usage", "Goto statement", r"\bgoto\s+\w+\s*;", 'goto retry;', 'while ($retry) retry();'),
    r("maint", "multiple-statements-line", "Multiple statements on one line", r";\s+\$[A-Za-z_]\w*\s*=", '$a = 1; $b = 2;', '$a = 1;'),
    r("maint", "suppress-all-errors", "Broad error reporting suppression", r"error_reporting\s*\(\s*0\s*\)", 'error_reporting(0);', 'error_reporting(E_ALL);'),
]

assert len(RULES) == 179
assert {family: sum(family in rule["tags"] for rule in RULES) for family in DEFAULTS} == {
    "bugs": 30, "err": 10, "res": 6, "inj": 25, "crypto": 12, "authz": 10,
    "hotspot": 15, "api": 30, "types": 12, "perf": 8, "maint": 21,
}
