# VB.NET language-pack bug and error-handling specs (#211).
# Clean-room, line-detectable signals; structure-dependent findings are confirmed by the scanner.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "vb")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "vbnet", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # bugs (25)
    r("bugs", id="vb:on-error-resume-next", type="bug", qual="rel", sev="high", cwe="CWE-390",
      title="Resume execution after every legacy error",
      desc="On Error Resume Next suppresses any runtime error and continues at the following statement.",
      rationale="Continuing after an unknown failure can use invalid state and makes the original fault difficult to locate.",
      remediation="Use Try/Catch around the operation expected to fail and handle only the exception types the code can recover from.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement",
      re=r"(?i)^\s*On\s+Error\s+Resume\s+Next\b",
      nc="On Error Resume Next",
      c="Try\n    LoadSettings()\nCatch ex As IOException\n    ReportFailure(ex)\nEnd Try",
      effort=30),
    r("bugs", id="vb:integer-divide-zero", type="bug", qual="rel", sev="high", cwe="CWE-369",
      title="Integer division uses a zero divisor",
      desc="An integer-division expression divides by the literal zero.",
      rationale="Integer division by zero raises DivideByZeroException whenever the statement executes.",
      remediation="Correct the constant or validate that a variable divisor is nonzero before dividing.",
      source="https://cwe.mitre.org/data/definitions/369.html",
      re=r"(?i)\b\w+\s*\\\s*0\b",
      nc="count = total \\ 0",
      c="count = total \\ divisor"),
    r("bugs", id="vb:modulo-zero", type="bug", qual="rel", sev="high", cwe="CWE-369",
      title="Modulo uses a zero divisor",
      desc="A Mod expression uses the literal zero as its divisor.",
      rationale="Modulo by zero cannot produce a result and raises DivideByZeroException.",
      remediation="Use a nonzero divisor or reject the input before the Mod operation.",
      source="https://cwe.mitre.org/data/definitions/369.html",
      re=r"(?i)\b\w+\s+Mod\s+0\b",
      nc="bucket = value Mod 0",
      c="bucket = value Mod bucketCount"),
    r("bugs", id="vb:and-null-guard", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Null guard uses non-short-circuit And",
      desc="A null check and member access are joined with And, which evaluates both operands.",
      rationale="And evaluates the member access even when the value is Nothing, causing a null-reference failure.",
      remediation="Use AndAlso so the member access runs only after the Nothing check succeeds.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/andalso-operator",
      re=r"(?i)\b\w+\s+IsNot\s+Nothing\s+And\s+\w+\.",
      nc="If customer IsNot Nothing And customer.IsActive Then",
      c="If customer IsNot Nothing AndAlso customer.IsActive Then"),
    r("bugs", id="vb:or-null-guard", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Null fallback uses non-short-circuit Or",
      desc="A Nothing check and member access are joined with Or, which evaluates both operands.",
      rationale="Or evaluates the member access even when the value is Nothing, defeating the intended fallback check.",
      remediation="Use OrElse for a short-circuit fallback condition.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/orelse-operator",
      re=r"(?i)\b\w+\s+Is\s+Nothing\s+Or\s+\w+\.",
      nc="If customer Is Nothing Or customer.IsDeleted Then",
      c="If customer Is Nothing OrElse customer.IsDeleted Then"),
    r("bugs", id="vb:iif-eager-branches", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="IIf evaluates both result expressions",
      desc="The legacy IIf function is used for conditional selection.",
      rationale="IIf evaluates both result expressions before choosing one, so an unused branch can still throw or perform work.",
      remediation="Use the If operator, which evaluates only the selected branch.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/if-operator",
      re=r"(?i)\bIIf\s*\(",
      nc="name = IIf(user Is Nothing, \"guest\", user.Name)",
      c="name = If(user Is Nothing, \"guest\", user.Name)"),
    r("bugs", id="vb:using-variable-reassigned", type="bug", qual="rel", sev="medium", cwe="CWE-672",
      title="Using resource variable is reassigned",
      desc="A Using declaration assigns a resource and another assignment overwrites that variable on the same line.",
      rationale="Reassigning a scoped resource can make ownership and the object that Using will dispose unclear.",
      remediation="Keep the Using variable immutable and use a separately named local for any replacement resource.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/control-flow/using-statement",
      re=r"(?i)^\s*Using\s+[A-Za-z_]\w*[^=]*=.+:\s*[A-Za-z_]\w*\s*=",
      nc="Using reader = OpenReader() : reader = OpenReader()",
      c="Using reader = OpenReader()\n    Consume(reader)\nEnd Using"),
    r("bugs", id="vb:doevents-reentrancy", type="bug", qual="rel", sev="medium", cwe="CWE-362",
      title="Application.DoEvents permits reentrancy",
      desc="Code pumps the UI message loop during an operation with Application.DoEvents.",
      rationale="Processing queued messages mid-operation can reenter handlers before the current state is consistent.",
      remediation="Use asynchronous UI work and return control to the message loop naturally.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.doevents",
      re=r"(?i)\bApplication\.DoEvents\s*\(",
      nc="Application.DoEvents()",
      c="Await Task.Yield()"),
    r("bugs", id="vb:control-checkforillegalcrossthreadcalls", type="bug", qual="rel", sev="high", cwe="CWE-362",
      title="Cross-thread UI checks are disabled",
      desc="Control.CheckForIllegalCrossThreadCalls is assigned False.",
      rationale="Disabling the diagnostic hides unsafe UI access instead of marshaling work to the UI thread.",
      remediation="Use Invoke, BeginInvoke, or asynchronous UI coordination for cross-thread updates.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.checkforillegalcrossthreadcalls",
      re=r"(?i)\bControl\.CheckForIllegalCrossThreadCalls\s*=\s*False\b",
      nc="Control.CheckForIllegalCrossThreadCalls = False",
      c="Control.CheckForIllegalCrossThreadCalls = True"),
    r("bugs", id="vb:thread-abort", type="bug", qual="rel", sev="medium", cwe="CWE-664",
      title="Thread is aborted asynchronously",
      desc="Thread.Abort is used to stop a named thread receiver at an arbitrary execution point.",
      rationale="Asynchronous thread termination can interrupt invariants and leave shared state partially updated.",
      remediation="Use cooperative cancellation with CancellationToken and let the thread exit normally.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort",
      re=r"(?i)\b(?:Thread\.CurrentThread|[A-Za-z_]\w*Thread)\.Abort\s*\(",
      nc="workerThread.Abort()",
      c="cancellationSource.Cancel()"),
    r("bugs", id="vb:sync-lock-me", type="bug", qual="rel", sev="medium", cwe="CWE-667",
      title="SyncLock uses the public instance",
      desc="SyncLock locks Me, exposing the lock object to outside code.",
      rationale="Other code can acquire the same public lock and create unexpected contention or deadlock.",
      remediation="Lock a Private ReadOnly object dedicated to synchronization.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2002",
      re=r"(?i)^\s*SyncLock\s+Me\b",
      nc="SyncLock Me",
      c="SyncLock _gate"),
    r("bugs", id="vb:environment-exit", type="bug", qual="rel", sev="medium", cwe="",
      title="Process termination is invoked directly",
      desc="Environment.Exit terminates the host process from the current code path.",
      rationale="Direct process termination prevents callers from choosing recovery and can bypass normal cleanup.",
      remediation="Return an error or throw an exception for the application boundary to handle.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.environment.exit",
      re=r"(?i)\bEnvironment\.Exit\s*\(",
      nc="Environment.Exit(1)",
      c="Throw New InvalidOperationException(\"fatal startup failure\")"),
    r("bugs", id="vb:end-statement", type="bug", qual="rel", sev="high", cwe="CWE-404",
      title="End statement stops the process immediately",
      desc="The End statement terminates the application without normal stack unwinding.",
      rationale="Immediate termination can skip Finally blocks and resource cleanup, leaving data or external operations incomplete.",
      remediation="Return from the entry point or use structured shutdown and disposal.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/end-statement",
      re=r"(?i)^\s*End\s*(?:'.*)?$",
      nc="End ' Stops the application immediately",
      c="Return ' Caller performs normal shutdown"),
    r("bugs", id="vb:not-implemented-exception", type="bug", qual="rel", sev="medium", cwe="",
      title="Member is left unimplemented",
      desc="A member throws NotImplementedException when invoked.",
      rationale="A released execution path that is explicitly unimplemented fails at runtime instead of delivering its contract.",
      remediation="Implement the member or remove it until the behavior is available.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.notimplementedexception",
      re=r"(?i)\bThrow\s+New\s+NotImplementedException\s*\(",
      nc="Throw New NotImplementedException()",
      c="Return CalculateTotal(items)"),
    r("bugs", id="vb:gc-collect", type="bug", qual="rel", sev="medium", cwe="",
      title="Garbage collection is forced explicitly",
      desc="GC.Collect is called directly.",
      rationale="Forcing collection disrupts the runtime's memory-management heuristics and can stall application work.",
      remediation="Remove the call and release managed resources through normal lifetime and disposal patterns.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.gc.collect",
      re=r"(?i)\bGC\.Collect\s*\(",
      nc="GC.Collect()",
      c="cache.Clear()"),
    r("bugs", id="vb:integer-division-assigned-double", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Integer quotient is widened after truncation",
      desc="A backslash integer-division expression is assigned to a Double value.",
      rationale="The backslash operator discards the fractional portion before the result is widened to Double.",
      remediation="Use / when a fractional result is required, or convert an operand before the calculation.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/integer-division-operator",
      re=r"(?i)\b\w+\s+As\s+Double\s*=\s*\w+\s*\\\s*\w+",
      nc="Dim ratio As Double = hits \\ total",
      c="Dim ratio As Double = hits / total"),
    r("bugs", id="vb:floating-point-equality", type="bug", qual="rel", sev="low", cwe="CWE-1077",
      title="Floating-point value is compared to a decimal literal",
      desc="A value is tested for exact equality with a decimal literal.",
      rationale="Most decimal values cannot be represented exactly as binary floating point, so an equality test can miss an equivalent calculation.",
      remediation="Compare the absolute difference to an application-appropriate tolerance.",
      source="https://cwe.mitre.org/data/definitions/1077.html",
      re=r"(?i)\b(?:If|ElseIf|While|Until|AndAlso|OrElse|And|Or)\s+[A-Za-z_][A-Za-z0-9_.]*(?:\s*[+\-*/]\s*[A-Za-z_][A-Za-z0-9_.]*)?\s*(?:=|<>)\s*\d+\.\d+\b",
      nc="If ratio = 0.1 Then",
      c="If Math.Abs(ratio - 0.1) < tolerance Then"),
    r("bugs", id="vb:random-security-value", type="bug", qual="rel", sev="high", cwe="CWE-338",
      title="General random generator creates a security-named value",
      desc="A token, secret, password, or key-named value is assigned from Random.Next.",
      rationale="Random is not designed to generate unpredictable authentication material and its output may be guessed.",
      remediation="Use RandomNumberGenerator to create cryptographic bytes and encode them for the required token format.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r"(?i)\b\w*(?:token|secret|password|apikey|api_key)\w*\s*=\s*\w+(?:\.\w+)*\.Next\s*\(",
      nc="resetToken = random.Next()",
      c="resetToken = Convert.ToHexString(RandomNumberGenerator.GetBytes(32))",
      effort=30),
    r("bugs", id="vb:val-conversion", type="bug", qual="rel", sev="medium", cwe="CWE-20",
      title="Val converts text with permissive legacy parsing",
      desc="Val is used to convert text to a number.",
      rationale="Val accepts an initial numeric prefix and ignores later characters, allowing malformed input to become a valid-looking number.",
      remediation="Use Integer.TryParse, Decimal.TryParse, or another typed TryParse overload with explicit validation.",
      source="https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.conversion.val",
      re=r"(?i)\bVal\s*\(",
      nc="quantity = Val(rawQuantity)",
      c="If Not Integer.TryParse(rawQuantity, quantity) Then Return"),
    r("bugs", id="vb:date-now-date", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Local current time is converted to a date boundary",
      desc="DateTime.Now is immediately converted to Date, using the host machine's local time zone.",
      rationale="Host-local time can produce the wrong day when business rules use a configured or user-specific time zone.",
      remediation="Obtain time from the intended TimeZoneInfo or pass the business date as an explicit dependency.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.datetime.now",
      re=r"(?i)\bDateTime\.Now\.Date\b",
      nc="reportDate = DateTime.Now.Date",
      c="reportDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, zone).Date"),
    r("bugs", id="vb:dictionary-add-duplicate", type="bug", qual="rel", sev="medium", cwe="CWE-704",
      title="Dictionary Add receives a possibly repeated key",
      desc="Dictionary.Add is used with an identifier-named key and throws if that key already exists.",
      rationale="A duplicate input key causes an exception instead of applying an explicit overwrite, reject, or merge policy.",
      remediation="Check ContainsKey, use TryAdd where available, or assign through the indexer when replacement is intended.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.add",
      re=r"(?i)\b\w+(?:\.\w+)*\.Add\s*\(\s*\w*(?:id|key|name)\w*\s*,",
      nc="users.Add(userId, user)",
      c="users(userId) = user"),
    r("bugs", id="vb:dispose-followed-by-use", type="bug", qual="rel", sev="medium", cwe="CWE-416",
      title="Disposed resource is followed by member use",
      desc="A one-line statement disposes a resource and then dereferences a resource on the same line.",
      rationale="This statement shape is prone to using an object after disposal, which commonly raises ObjectDisposedException or produces invalid I/O behavior.",
      remediation="Move required use before disposal, or create a new object for the subsequent operation.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose",
      re=r"(?i)\b(?:stream|reader|writer|connection)\.Dispose\s*\(\s*\)\s*:\s*(?:stream|reader|writer|connection)\.",
      nc="stream.Dispose() : stream.Read(buffer, 0, buffer.Length)",
      c="stream.Read(buffer, 0, buffer.Length) : stream.Dispose()"),
    r("bugs", id="vb:string-compare-culture", type="bug", qual="rel", sev="medium", cwe="CWE-176",
      title="String comparison omits an explicit comparison rule",
      desc="String.Compare is called with two values and no StringComparison argument.",
      rationale="The default comparison can vary with current culture and can give incorrect results for protocol, identifier, or security decisions.",
      remediation="Pass StringComparison.Ordinal or the explicitly intended culture-aware comparison.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.compare",
      re=r"(?i)\bString\.Compare\s*\(\s*[^,]+\s*,\s*[^,)]+\s*\)",
      nc="If String.Compare(userName, expectedName) = 0 Then",
      c="If String.Equals(userName, expectedName, StringComparison.Ordinal) Then"),
    r("bugs", id="vb:debug-assert-side-effect", type="bug", qual="rel", sev="medium", cwe="CWE-670",
      title="Debug assertion contains an invocation",
      desc="Debug.Assert is passed a method call that may have side effects.",
      rationale="Debug-only assertions are removed from release builds, so side effects inside their conditions disappear in production.",
      remediation="Perform required work before the assertion and assert only the resulting condition.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert",
      re=r"(?i)\bDebug\.Assert\s*\(\s*\w+(?:\.\w+)*\s*\(",
      nc="Debug.Assert(InitializeCache())",
      c="InitializeCache() : Debug.Assert(cache.IsReady)"),
    r("bugs", id="vb:nan-equality", type="bug", qual="rel", sev="medium", cwe="CWE-480",
      title="NaN is compared with equality",
      desc="A floating-point value is compared to Double.NaN or Single.NaN with an equality operator.",
      rationale="NaN is unequal to every value, including itself, so an equality comparison cannot identify it.",
      remediation="Use Double.IsNaN or Single.IsNaN for an explicit NaN test.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.double.isnan",
      re=r"(?i)(?:=|<>)\s*(?:Double|Single)\.NaN\b|\b(?:Double|Single)\.NaN\s*(?:=|<>)",
      nc="If measurement = Double.NaN Then",
      c="If Double.IsNaN(measurement) Then"),

    # err (12)
    r("err", id="vb:empty-catch", type="bug", qual="rel", sev="medium", cwe="CWE-390",
      title="Catch handler has no recovery action",
      desc="A Catch header starts a handler that the contextual pass confirms has no executable body.",
      rationale="Swallowing an exception hides a failed operation and leaves callers unable to distinguish it from success.",
      remediation="Handle or log the exception, return a failure result, or rethrow when the operation cannot recover.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r"(?i)^\s*Catch(?:\s+[A-Za-z_]\w*(?:\s+As\s+[A-Za-z_.]\w*)?)?\s*$",
      nc="Try\n    Save()\nCatch\nEnd Try",
      c="Finally\n    connection.Dispose()\nEnd Try"),
    r("err", id="vb:on-error-goto", type="smell", qual="maint", sev="medium", cwe="CWE-703",
      title="Legacy On Error branch controls recovery",
      desc="On Error GoTo transfers failures to a label instead of structured exception handling.",
      rationale="Label-based recovery separates fault handling from the operation and makes error propagation difficult to reason about.",
      remediation="Replace the region with Try/Catch/Finally and handle the expected exception types locally.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement",
      re=r"(?i)^\s*On\s+Error\s+GoTo\s+[A-Za-z_]\w*",
      nc="On Error GoTo Failed",
      c="Try\n    Save()\nCatch ex As IOException\n    ReportFailure(ex)\nEnd Try"),
    r("err", id="vb:resume-next-statement", type="bug", qual="rel", sev="medium", cwe="CWE-703",
      title="Resume Next continues after a handled error",
      desc="A legacy error handler resumes at the statement following the failure.",
      rationale="Skipping the failed statement can continue with incomplete state and conceals the operation that did not complete.",
      remediation="Repair or abandon the operation explicitly in a Catch handler instead of resuming execution blindly.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/resume-statement",
      re=r"(?i)^\s*Resume\s+Next\s*$",
      nc="Resume Next",
      c="Throw"),
    r("err", id="vb:catch-system-exception", type="smell", qual="maint", sev="low", cwe="CWE-396",
      title="Catch handler captures the base exception type",
      desc="A Catch clause handles Exception or System.Exception rather than a recoverable subtype.",
      rationale="Catching the root exception type can hide programming defects and failures the current operation was not designed to recover from.",
      remediation="Catch only the concrete exception types the operation can handle and let other failures propagate.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031",
      re=r"(?i)^\s*Catch\s+\w+\s+As\s+(?:System\.)?Exception\b",
      nc="Catch ex As Exception",
      c="Catch ex As IOException"),
    r("err", id="vb:throw-exception-variable", type="bug", qual="rel", sev="medium", cwe="",
      title="Rethrow resets the original stack trace",
      desc="Throw is given an existing exception variable.",
      rationale="Throwing the caught variable starts a new stack trace and removes evidence of where the original exception occurred.",
      remediation="Use Throw by itself inside Catch to preserve the original stack trace.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/throw-statement",
      re=r"(?i)^\s*Throw\s+\w+\s*$",
      nc="Throw ex",
      c="Throw"),
    r("err", id="vb:catch-without-exception", type="smell", qual="maint", sev="low", cwe="CWE-391",
      title="Catch handler discards exception details",
      desc="A bare Catch clause receives no exception object.",
      rationale="Without the exception object, the handler cannot preserve diagnostic details or distinguish recoverable failure types.",
      remediation="Bind a specific exception type and variable when recovery needs context, then log or propagate it appropriately.",
      source="https://cwe.mitre.org/data/definitions/391.html",
      re=r"(?i)^\s*Catch\s*$",
      nc="Catch",
      c="Catch ex As IOException"),
    r("err", id="vb:generic-new-exception", type="smell", qual="maint", sev="low", cwe="CWE-391",
      title="Generic Exception is constructed",
      desc="Code creates the base Exception type rather than an exception that describes the failure.",
      rationale="Generic exceptions force callers to infer failure meaning from text and make targeted recovery unreliable.",
      remediation="Throw the most specific built-in or domain exception and include the original exception as InnerException when wrapping.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.exception",
      re=r"(?i)\bNew\s+(?:System\.)?Exception\s*\(",
      nc="Throw New Exception(\"invalid state\")",
      c="Throw New InvalidOperationException(\"invalid state\")"),
    r("err", id="vb:throw-new-in-catch", type="bug", qual="rel", sev="medium", cwe="CWE-391",
      title="Catch path creates an unrelated exception",
      desc="A Catch clause throws a new exception without preserving the caught exception as its cause.",
      rationale="Replacing the failure loses the original stack trace and error details needed for diagnosis.",
      remediation="Wrap the caught exception with the InnerException constructor or rethrow it unchanged when no additional context is needed.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.exception.innerexception",
      re=r"(?i)^\s*Catch\s+\w+\s+As\s+\w+\s*:\s*Throw\s+New\s+\w+Exception\s*\(",
      nc="Catch ex As IOException : Throw New InvalidOperationException(\"save failed\")",
      c="Catch ex As IOException : Throw"),
    r("err", id="vb:return-in-finally", type="bug", qual="rel", sev="high", cwe="CWE-584",
      title="Finally block returns from the procedure",
      desc="A one-line Finally clause returns and can override a pending exception or result.",
      rationale="Control flow out of Finally suppresses the outcome of the protected operation and hides failures from callers.",
      remediation="Perform cleanup in Finally only; return after the Try block or let the exception propagate.",
      source="https://cwe.mitre.org/data/definitions/584.html",
      re=r"(?i)^\s*Finally\s*:\s*Return\b",
      nc="Finally : Return False",
      c="Finally : connection.Dispose()"),
    r("err", id="vb:err-clear", type="smell", qual="maint", sev="medium", cwe="CWE-390",
      title="Legacy error state is cleared explicitly",
      desc="Err.Clear discards the current Visual Basic error information.",
      rationale="Clearing error state before recording or propagating it removes evidence required to diagnose a failed operation.",
      remediation="Capture the failure in structured exception handling and log or return the error before cleanup.",
      source="https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.errobject.clear",
      re=r"(?i)\bErr\.Clear\s*\(",
      nc="Err.Clear()",
      c="logger.LogError(ex, \"save failed\")"),
    r("err", id="vb:err-description-only", type="smell", qual="maint", sev="low", cwe="CWE-209",
      title="Only legacy error text is reported",
      desc="Err.Description is passed directly to a reporting call without the exception object.",
      rationale="Text-only reporting drops stack and type information and can expose unreviewed internal messages to users.",
      remediation="Log a typed exception through the application logger and present a safe, stable message to users.",
      source="https://cwe.mitre.org/data/definitions/209.html",
      re=r"(?i)\b(?:Console\.WriteLine|MessageBox\.Show|logger\.Log\w+)\s*\(\s*Err\.Description\s*\)",
      nc="MessageBox.Show(Err.Description)",
      c="logger.LogError(ex, \"save failed\")"),
    r("err", id="vb:catch-return-failure-code", type="bug", qual="rel", sev="medium", cwe="CWE-390",
      title="Catch handler returns a sentinel failure value",
      desc="A one-line Catch handler returns a literal sentinel instead of preserving the exception.",
      rationale="A sentinel value can be mistaken for a legitimate result and discards the cause of the failed operation.",
      remediation="Return a typed result that carries error information, or log and rethrow the exception.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r"(?i)^\s*Catch\s+\w+\s+As\s+\w+\s*:\s*Return\s+(?:Nothing|False|0|\"\")\s*$",
      nc="Catch ex As IOException : Return Nothing",
      c="Catch ex As IOException : Throw"),
]
