CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","js");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","javascript"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="js-prefer-template",type="smell",qual="maint",sev="info",cwe="",title="String concatenation over template literal",
   desc="Concatenating a string literal with a variable reads better as a template literal.",
   rationale="Template literals express interpolation more clearly than + concatenation and avoid subtle coercion.",
   remediation="Use a backtick template literal with ${...}.",
   source="https://eslint.org/docs/latest/rules/prefer-template",
   re=r"['\"][^'\"]*['\"]\s*\+\s*[A-Za-z_$]",nc='const g = "Hello " + name;',c="const g = `Hello ${name}`;"),
 r(id="js-prefer-object-spread",type="smell",qual="maint",sev="info",cwe="",title="Object.assign to a fresh object",
   desc="Object.assign({}, x) is clearer as an object spread.",
   rationale="Spreading ({ ...x }) is more readable than Object.assign into a fresh literal and avoids mutation mistakes.",
   remediation="Use object spread: { ...x }.",
   source="https://eslint.org/docs/latest/rules/prefer-object-spread",
   re=r"Object\.assign\s*\(\s*\{\s*\}",nc="const merged = Object.assign({}, defaults);",c="const merged = { ...defaults };"),
 r(id="js-no-new-require",type="bug",qual="rel",sev="medium",cwe="",title="new require(...)",
   desc="`new require('x')` news the return of require, almost never intended.",
   rationale="new binds tighter than the call, so new require('x') constructs require's result rather than the module, a subtle bug.",
   remediation="Call require without new.",
   source="https://eslint.org/docs/latest/rules/no-new-require",
   re=r"\bnew\s+require\s*\(",nc='const C = new require("thing");',c='const C = require("thing");'),
 r(id="js-no-labels",type="smell",qual="maint",sev="low",cwe="",title="Labeled statement",
   desc="Labeled loops/blocks obscure control flow.",
   rationale="Labels with break/continue create non-local jumps that are hard to follow; refactoring into functions is usually clearer.",
   remediation="Extract a function or restructure to avoid the label.",
   source="https://eslint.org/docs/latest/rules/no-labels",
   re=r"^\s*[A-Za-z_$][\w$]*\s*:\s*(for|while|do|switch)\b",nc="outer: for (const row of rows) {",c="for (const row of rows) {"),
 r(id="js-no-nested-ternary",type="smell",qual="maint",sev="low",cwe="",title="Nested ternary expression",
   desc="A ternary inside a ternary is hard to read.",
   rationale="Nested conditional expressions are difficult to parse visually and error-prone to edit.",
   remediation="Use if/else or extract a helper.",
   source="https://eslint.org/docs/latest/rules/no-nested-ternary",
   re=r"\?[^?:{}]*\?",nc="const t = a ? b ? 1 : 2 : 3;",c="const t = a ? pick(b) : 3;"),
 r(id="js-no-return-assign",type="bug",qual="rel",sev="medium",cwe="",title="Assignment in a return statement",
   desc="`return x = v` assigns and returns; usually a mistaken comparison.",
   rationale="An assignment in a return both mutates and returns the value, and is frequently a typo for ==.",
   remediation="Return a comparison, or assign on a separate line before returning.",
   source="https://eslint.org/docs/latest/rules/no-return-assign",
   re=r"\breturn\s+[A-Za-z_$][\w$.]*\s*=\s*[^=]",nc="return done = true;",c="return done === true;"),
 r(id="js-dom-xss-outerhtml",type="vuln",qual="sec",sev="high",cwe="CWE-79",owasp="A03:2021",title="Dynamic value assigned to outerHTML",
   desc="Assigning non-literal data to outerHTML parses it as HTML (DOM XSS).",
   rationale="outerHTML, like innerHTML, parses assigned strings as HTML, so attacker-influenced data can inject script.",
   remediation="Set textContent, or sanitize the HTML with a vetted sanitizer.",
   source="https://cwe.mitre.org/data/definitions/79.html",
   re=r"\.outerHTML\s*=\s*[A-Za-z_$]",nc="node.outerHTML = payload;",c="node.textContent = payload;"),
 r(id="js-insert-adjacent-html",type="hotspot",qual="sec",sev="medium",cwe="CWE-79",owasp="A03:2021",title="insertAdjacentHTML with dynamic data",
   desc="insertAdjacentHTML parses its argument as HTML.",
   rationale="insertAdjacentHTML injects parsed HTML into the DOM, so dynamic input is a cross-site-scripting vector.",
   remediation="Build nodes with the DOM API, or sanitize before inserting.",
   source="https://cwe.mitre.org/data/definitions/79.html",
   re=r"insertAdjacentHTML\s*\(",nc='box.insertAdjacentHTML("beforeend", html);',c="box.append(buildNode(data));"),
]
