# VB.NET language-pack rule specs — resource lifetime and concurrency families (#211).
# Clean-room, precision-biased lexical rules; bounded context confirms ownership and lifetime.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "vb")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "vbnet", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- res (10) ----
    r("res", id="vb:idisposable-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="Local disposable object has no observed cleanup",
      desc="A Dim declaration creates a known disposable I/O or data-access object and the bounded local context contains no cleanup on the same receiver.",
      rationale="The bounded context can establish only whether this procedure visibly disposes or closes the local; ownership transferred outside that window requires review.",
      remediation="Use Using for local ownership, or make the receiving owner and its cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/control-flow/using-statement",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*New\s+((System\.IO\.)?(FileStream|StreamReader|StreamWriter|BinaryReader|BinaryWriter|StringReader|StringWriter)|(System\.Data\.(SqlClient|OleDb|Odbc)\.)?(SqlConnection|SqlCommand|SqlDataReader|OleDbConnection|OleDbCommand|OdbcConnection|OdbcCommand))\s*\(",
      nc='Dim reader = New StreamReader(path)',
      c='Using reader = New StreamReader(path)\n    Consume(reader)\nEnd Using',
      effort=30),
    r("res", id="vb:file-open-not-managed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="File stream acquisition has no observed cleanup",
      desc="A local Dim declaration stores a File.Open-family result and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for locally owned streams, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.io.file.open",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*(System\.IO\.)?File\.(Open|OpenRead|OpenWrite|Create|CreateText|AppendText)\s*\(",
      nc='Dim stream = File.OpenRead(path)',
      c='Using stream = File.OpenRead(path)\n    Consume(stream)\nEnd Using'),
    r("res", id="vb:zip-archive-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="ZipArchive acquisition has no observed cleanup",
      desc="A local Dim declaration opens a ZIP archive and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for locally owned archives, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.open",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*(System\.IO\.Compression\.)?ZipFile\.Open(Read)?\s*\(",
      nc='Dim archive = ZipFile.OpenRead(path)',
      c='Using archive = ZipFile.OpenRead(path)\n    Extract(archive)\nEnd Using'),
    r("res", id="vb:data-reader-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="Data reader acquisition has no observed cleanup",
      desc="A local Dim declaration stores ExecuteReader output and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for locally owned readers, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.executereader",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*(Await\s+)?[A-Za-z_][A-Za-z0-9_\.]*\.ExecuteReader(Async)?\s*\(",
      nc='Dim reader = command.ExecuteReader()',
      c='Using reader = command.ExecuteReader()\n    ReadRows(reader)\nEnd Using'),
    r("res", id="vb:process-start-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="Process.Start result has no observed cleanup",
      desc="A local Dim declaration stores a Process.Start result and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for a locally owned Process, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*(System\.Diagnostics\.)?Process\.Start\s*\(",
      nc='Dim child = Process.Start(startInfo)',
      c='Using child = Process.Start(startInfo)\n    child.WaitForExit()\nEnd Using'),
    r("res", id="vb:cancellation-token-source-not-disposed", type="smell", qual="maint", sev="medium", cwe="CWE-404",
      title="CancellationTokenSource has no observed cleanup",
      desc="A local Dim declaration creates a CancellationTokenSource and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish lifecycle ownership or cleanup on every control-flow path.",
      remediation="Use Using for a short-lived source, or make the lifecycle owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.dispose",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*New\s+(System\.Threading\.)?CancellationTokenSource\s*\(",
      nc='Dim cancelSource = New CancellationTokenSource()',
      c='Using cancelSource = New CancellationTokenSource()\n    Run(cancelSource.Token)\nEnd Using'),
    r("res", id="vb:timer-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="Timer has no observed cleanup",
      desc="A local Dim declaration creates a timer and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish lifecycle ownership or cleanup on every control-flow path.",
      remediation="Use Using for a temporary timer, or make the owning type cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.timer.dispose",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*New\s+(?:(?:System\.)?(?:Threading|Timers)\.)?Timer\s*\(",
      nc='Dim timer = New Threading.Timer(AddressOf Tick)',
      c='Using timer = New Threading.Timer(AddressOf Tick)\n    WaitForWork()\nEnd Using'),
    r("res", id="vb:file-system-watcher-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="FileSystemWatcher has no observed cleanup",
      desc="A local Dim declaration creates a FileSystemWatcher and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish lifecycle ownership or cleanup on every control-flow path.",
      remediation="Use Using for a temporary watcher, or make the long-lived owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.dispose",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*New\s+(System\.IO\.)?FileSystemWatcher\s*\(",
      nc='Dim watcher = New FileSystemWatcher(root)',
      c='Using watcher = New FileSystemWatcher(root)\n    watcher.EnableRaisingEvents = True\nEnd Using'),
    r("res", id="vb:registry-key-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="Registry key has no observed cleanup",
      desc="A local Dim declaration stores an opened RegistryKey and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for locally owned keys, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.dispose",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?=\s*[A-Za-z_][A-Za-z0-9_\.]*\.Open(SubKey|RemoteBaseKey)\s*\(",
      nc='Dim key = Registry.CurrentUser.OpenSubKey("Software")',
      c='Using key = Registry.CurrentUser.OpenSubKey("Software")\n    ReadValue(key)\nEnd Using'),
    r("res", id="vb:http-response-not-disposed", type="bug", qual="rel", sev="medium", cwe="CWE-404",
      title="HttpResponseMessage has no observed cleanup",
      desc="A local Dim declaration stores an HTTP response and the bounded local context contains no cleanup on that receiver.",
      rationale="The bounded context cannot establish ownership transfer or cleanup on every control-flow path.",
      remediation="Use Using for locally owned responses, or make the receiving owner cleanup contract explicit.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.dispose",
      re=r"(?i)^\s*Dim\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+(System\.Net\.Http\.)?HttpResponseMessage\s*)?=\s*(Await\s+)?[A-Za-z_][A-Za-z0-9_\.]*\.(GetAsync|PostAsync|SendAsync)\s*\(",
      nc='Dim response = Await client.GetAsync(uri)',
      c='Using response = Await client.GetAsync(uri)\n    Return Await response.Content.ReadAsStringAsync()\nEnd Using'),

    # ---- conc (8) ----
    r("conc", id="vb:thread-start-without-join", type="smell", qual="maint", sev="medium", cwe="CWE-667",
      title="Thread starts without an observed join",
      desc="A Thread-named receiver calls Start, requiring review of lifecycle ownership and completion coordination.",
      rationale="A started thread without explicit ownership can outlive the operation that created it and complicate shutdown.",
      remediation="Use Task-based work where possible, or retain the thread and coordinate completion explicitly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.start",
      re=r"(?i)\b(?:Thread\.CurrentThread|[A-Za-z_]\w*Thread)\.Start\s*\(",
      nc='workerThread.Start()',
      c='Await workerTask'),
    r("conc", id="vb:synclock-type", type="bug", qual="rel", sev="medium", cwe="CWE-662",
      title="SyncLock uses a publicly reachable Type object",
      desc="A SyncLock statement locks a GetType expression that unrelated code can acquire.",
      rationale="Type objects are shared process-wide for a type, so public locking can create unexpected contention or deadlocks.",
      remediation="Use a Private ReadOnly synchronization object instead of a Type object.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2002",
      re=r"(?i)^\s*SyncLock\s+GetType\s*\(",
      nc='SyncLock GetType(Cache)\n    Refresh()\nEnd SyncLock',
      c='SyncLock _gate\n    Refresh()\nEnd SyncLock'),
    r("conc", id="vb:thread-sleep", type="smell", qual="maint", sev="medium", cwe="CWE-833",
      title="Thread.Sleep blocks a worker thread",
      desc="Code pauses a thread with Thread.Sleep.",
      rationale="Sleeping ties up a thread-pool or UI thread and reduces the scheduler's capacity to run useful work.",
      remediation="Use Await Task.Delay for asynchronous waiting, or a timer-driven design for scheduled work.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep",
      re=r"(?i)\b(System\.Threading\.)?Thread\.Sleep\s*\(",
      nc='Thread.Sleep(500)',
      c='Await Task.Delay(500)'),
    r("conc", id="vb:task-blocking-result", type="bug", qual="rel", sev="high", cwe="CWE-833",
      title="Task completion is waited synchronously",
      desc="Code reads Task.Result or calls Wait, blocking the current thread for asynchronous work.",
      rationale="Synchronous waits can deadlock under a synchronization context and consume a thread while the operation is pending.",
      remediation="Make the caller asynchronous and Await the task instead.",
      source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/",
      re=r"(?i)\b(?:\w*task\w*|\w+Async\s*\([^()]*\))\.(?:Result\b|Wait\s*\(\s*\))",
      nc='Dim body = client.GetStringAsync(uri).Result',
      c='Dim body = Await client.GetStringAsync(uri)'),
    r("conc", id="vb:thread-abort-concurrency", type="bug", qual="rel", sev="medium", cwe="CWE-667",
      title="Thread.Abort terminates execution asynchronously",
      desc="Code calls Abort on a Thread.",
      rationale="Aborting a thread can interrupt code while it holds state or synchronization and is unsupported on modern .NET runtimes.",
      remediation="Use cooperative cancellation with CancellationToken and let the thread exit normally.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort",
      re=r"(?i)\b(?:Thread\.CurrentThread|[A-Za-z_]\w*Thread)\.Abort\s*\(\s*\)",
      nc='workerThread.Abort()',
      c='cancelSource.Cancel()'),
    r("conc", id="vb:thread-suspend-resume", type="bug", qual="rel", sev="medium", cwe="CWE-667",
      title="Thread suspension is controlled externally",
      desc="Code suspends or resumes a Thread from another execution path.",
      rationale="Forced suspension can freeze a thread while it owns a lock, and these APIs are unsupported on current .NET runtimes.",
      remediation="Coordinate work with CancellationToken, events, or a bounded producer-consumer queue.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.suspend",
      re=r"(?i)\b(?:Thread\.CurrentThread|[A-Za-z_]\w*Thread)\.(?:Suspend|Resume)\s*\(\s*\)",
      nc='workerThread.Suspend()',
      c='pauseRequested.Set()'),
    r("conc", id="vb:task-run-unobserved", type="smell", qual="maint", sev="medium", cwe="CWE-390",
      title="Task.Run result is not observed",
      desc="A Task.Run call begins a background task as a standalone statement.",
      rationale="Without an awaited or retained Task, completion and exceptions have no defined owner to observe them.",
      remediation="Await the task, or retain it in a lifecycle-managed component that handles faults.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run",
      re=r"(?i)^\s*(System\.Threading\.Tasks\.)?Task\.Run\s*\(",
      nc='Task.Run(Sub() Refresh())',
      c='Await Task.Run(Sub() Refresh())'),
    r("conc", id="vb:static-local-shared-state", type="hotspot", qual="sec", sev="medium", cwe="CWE-362",
      title="Mutable Static local state can race",
      desc="A procedure declares a Static local variable, sharing it across concurrent calls.",
      rationale="Static locals persist between invocations, so concurrent callers can read or update the same state without synchronization.",
      remediation="Protect intentional shared state with a dedicated synchronization primitive, or move per-call data to a normal local.",
      source="https://cwe.mitre.org/data/definitions/362.html",
      re=r"(?i)^\s*Static\s+[A-Za-z_][A-Za-z0-9_]*\s*(As\s+[A-Za-z0-9_.]+\s*)?(=|As\s+New\b)",
      nc='Static nextId As Integer = 0',
      c='Dim nextId As Integer = 0',
      effort=30),
]
