# VB.NET language-pack rule specs (#211).
# Clean-room, precision-biased lexical rules for APIs, typing, performance, and maintainability.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "vb")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "vbnet", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # api (20)
    r("api", id="vb:webclient", type="smell", qual="maint", sev="low", cwe="",
      title="Legacy WebClient API used", desc="Code creates a WebClient instead of using HttpClient.",
      rationale="WebClient is not recommended for new development and has limited modern HTTP support.",
      remediation="Use a reused or injected HttpClient.", source="https://learn.microsoft.com/en-us/dotnet/api/system.net.webclient",
      re=r"(?i)\bNew\s+WebClient\s*\(", nc="Dim client = New WebClient()", c="Dim response = Await httpClient.GetAsync(endpoint)"),
    r("api", id="vb:httpwebrequest", type="smell", qual="maint", sev="low", cwe="",
      title="Legacy WebRequest API used", desc="Code creates an HTTP request with WebRequest.",
      rationale="The older request APIs have been superseded by HttpClient's asynchronous interface.",
      remediation="Use HttpClient to send the request.", source="https://learn.microsoft.com/en-us/dotnet/api/system.net.webrequest",
      re=r"(?i)\bWebRequest\.Create\s*\(", nc='Dim request = WebRequest.Create("https://api.example.test")', c='Dim response = Await httpClient.GetAsync("https://api.example.test")'),
    r("api", id="vb:binaryformatter", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="BinaryFormatter API used", desc="Code constructs or invokes BinaryFormatter.",
      rationale="BinaryFormatter can materialize attacker-controlled object graphs.",
      remediation="Use a data-only serializer with an explicit input schema.", source="https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide",
      re=r"(?i)\b(?:New\s+BinaryFormatter|BinaryFormatter\s*\.)", nc="Dim formatter = New BinaryFormatter()", c="Dim order = JsonSerializer.Deserialize(Of Order)(payload)"),
    r("api", id="vb:thread-abort-api", type="bug", qual="rel", sev="medium", cwe="",
      title="Thread.Abort invoked", desc="Code calls Abort on a receiver explicitly named as a thread.",
      rationale="Abort can interrupt code while state invariants are incomplete and is unsupported on modern .NET.",
      remediation="Use cooperative cancellation with CancellationToken.", source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort",
      re=r"(?i)\b(?:Thread\.CurrentThread|[A-Za-z_]\w*Thread)\.Abort\s*\(\s*\)", nc="workerThread.Abort()", c="cancellationSource.Cancel()"),
    r("api", id="vb:thread-yield-api", type="smell", qual="maint", sev="low", cwe="",
      title="Thread.Yield used for scheduling", desc="Code asks the runtime to yield the current thread instead of composing asynchronous work.",
      rationale="Thread.Yield makes scheduling behavior implicit and can obscure a design that should await or coordinate explicitly.",
      remediation="Use Await, a synchronization primitive, or a defined scheduling boundary.", source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.yield",
      re=r"(?i)\b(?:System\.Threading\.)?Thread\.Yield\s*\(\s*\)", nc="Thread.Yield()", c="Await Task.Yield()"),
    r("api", id="vb:application-exit-api", type="smell", qual="maint", sev="medium", cwe="",
      title="Application.Exit called", desc="Code terminates a Windows Forms application directly.",
      rationale="A component-driven exit prevents its host from deciding how to recover or coordinate shutdown.",
      remediation="Return an error or signal the application boundary to perform structured shutdown.", source="https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.exit",
      re=r"(?i)\bApplication\.Exit\s*\(", nc="Application.Exit()", c="Throw New InvalidOperationException(\"fatal\")"),
    r("api", id="vb:task-result", type="bug", qual="rel", sev="high", cwe="",
      title="Task.Result blocks asynchronous work", desc="Code obtains an asynchronous result through Result on a task-named receiver or an Async call.",
      rationale="Blocking an asynchronous operation can deadlock synchronization contexts and consumes a thread while waiting.",
      remediation="Await the task and make the containing method asynchronous.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/",
      re=r"(?i)\b(?:\w*task\w*|\w+Async\s*\([^()]*\))\.Result\b", nc="Dim item = LoadAsync(id).Result", c="Dim item = Await LoadAsync(id)"),
    r("api", id="vb:task-wait", type="bug", qual="rel", sev="high", cwe="",
      title="Task.Wait blocks asynchronous work", desc="Code synchronously waits on a task-named receiver or an Async call.",
      rationale="Synchronous waiting on asynchronous work can deadlock and wastes a thread.",
      remediation="Await the task instead of calling Wait.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/",
      re=r"(?i)\b(?:\w*task\w*|\w+Async\s*\([^()]*\))\.Wait\s*\(\s*\)", nc="SaveAsync(record).Wait()", c="Await SaveAsync(record)"),
    r("api", id="vb:getawaiter-getresult", type="bug", qual="rel", sev="high", cwe="",
      title="GetAwaiter().GetResult blocks a task", desc="Code forces a task to complete synchronously.",
      rationale="This bypasses asynchronous composition and can deadlock a captured context.",
      remediation="Await the task and propagate asynchronous execution.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/",
      re=r"(?i)\.GetAwaiter\s*\(\s*\)\.GetResult\s*\(\s*\)", nc="Dim result = FetchAsync().GetAwaiter().GetResult()", c="Dim result = Await FetchAsync()"),
    r("api", id="vb:async-sub-api", type="smell", qual="maint", sev="medium", cwe="",
      title="Async Sub declaration without an event-handler clause", desc="A procedure is declared Async Sub without a Handles clause.",
      rationale="Outside event handlers, Async Sub prevents callers from awaiting completion and observing exceptions.",
      remediation="Return Task from non-event asynchronous procedures.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/async-return-types",
      re=r"(?i)^\s*(?:Public|Private|Friend|Protected|Shared|Overridable|Overrides|Partial|\s)*Async\s+Sub\s+\w+\s*\([^\r\n]*\)\s*$", nc="Private Async Sub RefreshAsync()", c="Private Async Function RefreshAsync() As Task"),
    r("api", id="vb:thread-sleep-api", type="smell", qual="maint", sev="medium", cwe="",
      title="Thread.Sleep used for delayed work", desc="Code blocks a thread with Thread.Sleep.",
      rationale="Blocking a thread for timing reduces scalability and is unsuitable in asynchronous workflows.",
      remediation="Use Await Task.Delay or a timer.", source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep",
      re=r"(?i)\bThread\.Sleep\s*\(", nc="Thread.Sleep(1000)", c="Await Task.Delay(1000)"),
    r("api", id="vb:appdomain-createdomain", type="smell", qual="maint", sev="low", cwe="",
      title="AppDomain.CreateDomain used", desc="Code creates an additional AppDomain.",
      rationale="Application domains are not the supported plugin isolation model on modern .NET implementations.",
      remediation="Use process isolation or AssemblyLoadContext for plugin loading.", source="https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.createdomain",
      re=r"(?i)\bAppDomain\.CreateDomain\s*\(", nc='Dim domain = AppDomain.CreateDomain("plugin")', c="Dim context = New AssemblyLoadContext(\"plugin\", isCollectible:=True)"),
    r("api", id="vb:assembly-load-name", type="hotspot", qual="sec", sev="medium", cwe="CWE-470", owasp="A03:2021",
      title="Assembly loaded by a variable name", desc="Assembly.Load receives a variable expression.",
      rationale="A name controlled outside trusted configuration can load an unexpected component.",
      remediation="Map trusted identifiers to an explicit allowlist of known assemblies.", source="https://cwe.mitre.org/data/definitions/470.html",
      re=r"(?i)\bAssembly\.Load\s*\(\s*[A-Za-z_]\w*", nc="Dim plugin = Assembly.Load(pluginName)", c='Dim plugin = Assembly.Load("Approved.Plugin")'),
    r("api", id="vb:process-start-variable", type="hotspot", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Process.Start receives a variable command", desc="Process.Start is called with a variable as its first argument.",
      rationale="An externally influenced command can execute an unintended program or arguments.",
      remediation="Use a fixed executable and validate every argument against a closed set.", source="https://cwe.mitre.org/data/definitions/78.html",
      re=r"(?i)\bProcess\.Start\s*\(\s*[A-Za-z_]\w*\s*(?:,|\))", nc="Process.Start(command)", c='Process.Start("dotnet", "--info")'),
    r("api", id="vb:uri-escape-string", type="smell", qual="maint", sev="medium", cwe="CWE-116",
      title="Uri.EscapeUriString used for component data", desc="Code calls a generic URI escaping API for a value.",
      rationale="Generic URI escaping can preserve or encode delimiters incorrectly for a query value or another component.",
      remediation="Use Uri.EscapeDataString for a data component.", source="https://learn.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring",
      re=r"(?i)\bUri\.EscapeUriString\s*\(", nc="Dim query = Uri.EscapeUriString(searchText)", c="Dim query = Uri.EscapeDataString(searchText)"),
    r("api", id="vb:datetime-parse-no-culture", type="smell", qual="maint", sev="low", cwe="",
      title="DateTime.Parse called without a culture", desc="DateTime.Parse receives text without an explicit culture provider.",
      rationale="The default culture makes machine-readable dates vary between deployed environments.",
      remediation="Use ParseExact or Parse with CultureInfo.InvariantCulture for fixed formats.", source="https://learn.microsoft.com/en-us/dotnet/api/system.datetime.parse",
      re=r"(?i)\bDateTime\.Parse\s*\(\s*[^,()]+\s*\)", nc="Dim dateValue = DateTime.Parse(rawDate)", c="Dim dateValue = DateTime.Parse(rawDate, CultureInfo.InvariantCulture)"),
    r("api", id="vb:string-endswith-no-comparison", type="smell", qual="maint", sev="low", cwe="",
      title="String.EndsWith called without StringComparison", desc="String.EndsWith compares a literal without an explicit comparison mode.",
      rationale="The default comparison can be culture-sensitive, making protocol suffixes vary by locale.",
      remediation="Pass StringComparison.Ordinal or the required comparison mode.", source="https://learn.microsoft.com/en-us/dotnet/api/system.string.endswith",
      re=r"(?i)\.EndsWith\s*\(\s*\"[^\"]*\"\s*\)", nc='If fileName.EndsWith(".config") Then Load()', c='If fileName.EndsWith(".config", StringComparison.Ordinal) Then Load()'),
    r("api", id="vb:numeric-parse-no-culture", type="smell", qual="maint", sev="low", cwe="",
      title="Numeric Parse called without a culture", desc="A numeric Parse call receives one text argument.",
      rationale="Culture-dependent parsing can interpret separators differently in persisted or protocol values.",
      remediation="Pass CultureInfo.InvariantCulture or the intended culture.", source="https://learn.microsoft.com/en-us/dotnet/api/system.int32.parse",
      re=r"(?i)\b(?:Integer|Long|Decimal|Double)\.Parse\s*\(\s*[^,()]+\s*\)", nc="Dim amount = Decimal.Parse(rawAmount)", c="Dim amount = Decimal.Parse(rawAmount, CultureInfo.InvariantCulture)"),
    r("api", id="vb:tryparse-result-ignored", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="TryParse result discarded", desc="A TryParse call is used as a statement without checking its Boolean result.",
      rationale="A failed parse produces a default output value that can be mistaken for valid data.",
      remediation="Branch on the Boolean return before using the output variable.", source="https://cwe.mitre.org/data/definitions/252.html",
      re=r"(?i)^\s*(?:Integer|Long|Decimal|Double|DateTime|Guid)\.TryParse\s*\([^\n]*\)\s*$", nc="Integer.TryParse(rawCount, count)", c="If Not Integer.TryParse(rawCount, count) Then Return"),
    r("api", id="vb:debug-writeline", type="smell", qual="maint", sev="low", cwe="",
      title="Debug.WriteLine left in code", desc="Code writes a diagnostic line through Debug.WriteLine.",
      rationale="Ad hoc diagnostics are not structured and cannot be configured consistently in production.",
      remediation="Use the application's logging abstraction with an appropriate level.", source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.writeline",
      re=r"(?i)\bDebug\.WriteLine\s*\(", nc='Debug.WriteLine("connecting")', c='logger.LogInformation("connecting")'),

    # types (10)
    r("types", id="vb:option-strict-off", type="smell", qual="maint", sev="medium", cwe="", effort=30,
      title="Option Strict is disabled", desc="The file disables Option Strict, allowing implicit narrowing conversions and late binding.",
      rationale="Permissive conversions defer type errors to runtime and obscure member contracts.",
      remediation="Enable Option Strict and make conversions and member types explicit.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/option-strict-statement",
      re=r"(?i)^\s*Option\s+Strict\s+Off\b", nc="Option Strict Off", c="Option Strict On"),
    r("types", id="vb:option-explicit-off", type="smell", qual="maint", sev="medium", cwe="",
      title="Option Explicit is disabled", desc="The file disables Option Explicit, permitting undeclared variables.",
      rationale="An accidental name can silently create a new variable instead of producing a compile-time error.",
      remediation="Enable Option Explicit and declare every local variable.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/option-explicit-statement",
      re=r"(?i)^\s*Option\s+Explicit\s+Off\b", nc="Option Explicit Off", c="Option Explicit On"),
    r("types", id="vb:option-infer-off", type="smell", qual="maint", sev="low", cwe="",
      title="Option Infer is disabled", desc="The file disables local type inference.",
      rationale="Declarations without As clauses can otherwise become Object and lose compile-time type information.",
      remediation="Enable Option Infer and use explicit types where inference would obscure intent.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/option-infer-statement",
      re=r"(?i)^\s*Option\s+Infer\s+Off\b", nc="Option Infer Off", c="Option Infer On"),
    r("types", id="vb:implicit-object-local", type="smell", qual="maint", sev="medium", cwe="",
      title="Local declaration defaults to Object", desc="A Dim declaration has neither an As clause nor an initializer.",
      rationale="Object locals defer member checks and conversions until runtime, concealing the intended type.",
      remediation="Declare the intended type with As or initialize from a typed expression.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/dim-statement",
      re=r"(?i)^\s*Dim\s+[A-Za-z_]\w*\s*$", nc="Dim total", c="Dim total As Decimal"),
    r("types", id="vb:object-local", type="smell", qual="maint", sev="medium", cwe="",
      title="Local variable declared As Object", desc="A local Dim declaration explicitly uses Object.",
      rationale="A broad Object local loses compile-time member checking and often signals an unmodeled value contract.",
      remediation="Use the narrowest concrete type, interface, or generic type required.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/object-data-type",
      re=r"(?i)^\s*Dim\s+[A-Za-z_]\w*\s+As\s+Object\b", nc="Dim result As Object", c="Dim result As Customer"),
    r("types", id="vb:object-parameter", type="smell", qual="maint", sev="medium", cwe="",
      title="Parameter declared As Object", desc="A method parameter is typed as Object.",
      rationale="An Object parameter weakens the callable contract and makes callers discover valid inputs at runtime.",
      remediation="Use the narrowest type or interface accepted by the operation.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/object-data-type",
      re=r"(?i)\b(?:ByVal|ByRef)\s+[A-Za-z_]\w*\s+As\s+Object\b", nc="Sub Save(ByVal item As Object)", c="Sub Save(ByVal item As Customer)"),
    r("types", id="vb:object-function-return", type="smell", qual="maint", sev="medium", cwe="",
      title="Function returns Object", desc="A Function declaration exposes Object as its return type.",
      rationale="A broad return type forces callers to cast or use late binding and hides the result contract.",
      remediation="Return a specific type, interface, or generic result wrapper.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/function-statement",
      re=r"(?i)\bFunction\s+[A-Za-z_]\w*\s*\([^\n]*\)\s+As\s+Object\b", nc="Function Load() As Object", c="Function Load() As Customer"),
    r("types", id="vb:object-property", type="smell", qual="maint", sev="medium", cwe="",
      title="Property declared As Object", desc="A Property declaration uses Object as its public value type.",
      rationale="A broad property type obscures valid values and shifts type failures to runtime consumers.",
      remediation="Expose a concrete type or domain-specific interface.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/property-statement",
      re=r"(?i)\bProperty\s+[A-Za-z_]\w*\s+As\s+Object\b", nc="Public Property Payload As Object", c="Public Property Payload As Message"),
    r("types", id="vb:directcast-object", type="smell", qual="maint", sev="low", cwe="CWE-843",
      title="DirectCast uses an unchecked local value", desc="DirectCast converts a local value directly to another reference type.",
      rationale="A failed direct cast throws at runtime, so the conversion requires a guaranteed source contract.",
      remediation="Prefer a strongly typed source or TryCast with an explicit Nothing branch when the runtime type can vary.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/directcast-operator",
      re=r"(?i)\bDirectCast\s*\(\s*[A-Za-z_]\w*\s*,", nc="Dim user = DirectCast(value, Customer)", c="Dim user = TryCast(value, Customer)"),
    r("types", id="vb:cint-conversion", type="smell", qual="maint", sev="low", cwe="CWE-681",
      title="CInt conversion leaves rounding policy implicit", desc="Code converts a simple numeric value with CInt without an explicit rounding or truncation operation.",
      rationale="CInt rounds rather than truncates, so an unreviewed conversion can silently alter boundary values.",
      remediation="Specify the required rounding policy before converting.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/functions/type-conversion-functions",
      re=r"(?i)\bCInt\s*\(\s*[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)?\s*\)", nc="Dim units = CInt(quantity)", c="Dim units = CInt(Math.Truncate(quantity))"),

    # perf (6)
    r("perf", id="vb:keys-contains", type="smell", qual="maint", sev="low", cwe="",
      title="Dictionary.Keys.Contains used for membership", desc="Code tests a dictionary key through Keys.Contains.",
      rationale="ContainsKey states the lookup directly and avoids a key-collection operation.",
      remediation="Use dictionary.ContainsKey(key).", source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.containskey",
      re=r"(?i)\.Keys\.Contains\s*\(", nc="If users.Keys.Contains(id) Then Return", c="If users.ContainsKey(id) Then Return"),
    r("perf", id="vb:count-positive", type="smell", qual="maint", sev="low", cwe="",
      title="Count used to test whether a sequence has items", desc="A LINQ Count call is compared with zero.",
      rationale="Any can stop after the first item and more clearly states an existence test.",
      remediation="Use sequence.Any().", source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any",
      re=r"(?i)\.Count\s*\(\s*\)\s*(?:>|<>)\s*0\b", nc="If orders.Count() > 0 Then Send()", c="If orders.Any() Then Send()"),
    r("perf", id="vb:tolist-count", type="smell", qual="maint", sev="low", cwe="",
      title="ToList materializes only to count", desc="A sequence is materialized with ToList before its Count property is read.",
      rationale="The intermediate list allocates every element solely to compute a count.",
      remediation="Use Count directly on the sequence, or Any for an existence check.", source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolist",
      re=r"(?i)\.ToList\s*\(\s*\)\.Count\b", nc="Dim count = query.ToList().Count", c="Dim count = query.Count()"),
    r("perf", id="vb:repeated-string-concat", type="smell", qual="maint", sev="low", cwe="",
      title="String extended with concatenation assignment", desc="A variable is extended with &= and a string literal, which can allocate a replacement string.",
      rationale="The allocation becomes costly when this statement runs repeatedly.",
      remediation="Use StringBuilder.Append when the statement is on a repeated path; otherwise keep the simple concatenation.", source="https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder",
      re=r"(?i)^\s*[A-Za-z_]\w*\s*&=\s*\"", nc='message &= ", "', c='builder.Append(", ")'),
    r("perf", id="vb:tolower-contains", type="smell", qual="maint", sev="low", cwe="",
      title="ToLower used before Contains", desc="Case-insensitive membership is implemented by lowercasing a string first.",
      rationale="Lowercasing allocates and can apply culture-specific casing rather than the required ordinal comparison.",
      remediation="Use Contains with StringComparison.OrdinalIgnoreCase.", source="https://learn.microsoft.com/en-us/dotnet/api/system.string.contains",
      re=r"(?i)\.ToLower(?:Invariant)?\s*\(\s*\)\.Contains\s*\(", nc='If name.ToLower().Contains("admin") Then Flag()', c='If name.Contains("admin", StringComparison.OrdinalIgnoreCase) Then Flag()'),
    r("perf", id="vb:tochararray-foreach", type="smell", qual="maint", sev="low", cwe="",
      title="For Each iterates string.ToCharArray", desc="A For Each loop iterates an array created from a string.",
      rationale="Strings are already enumerable as Char, so ToCharArray allocates an unnecessary array.",
      remediation="Iterate the string directly.", source="https://learn.microsoft.com/en-us/dotnet/api/system.string.tochararray",
      re=r"(?i)\bFor\s+Each\s+\w+\s+In\s+[A-Za-z_]\w*\.ToCharArray\s*\(", nc="For Each ch In text.ToCharArray()", c="For Each ch In text"),

    # maint (6)
    r("maint", id="vb:select-case-true", type="smell", qual="maint", sev="low", cwe="",
      title="Select Case True obscures boolean branching", desc="A Select Case statement uses True as the selector.",
      rationale="Using Select Case True for boolean conditions hides the actual branch predicates and complicates maintenance.",
      remediation="Use If/ElseIf for boolean predicates, or select a stable value once.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/select-case-statement",
      re=r"(?i)^\s*Select\s+Case\s+True\b", nc="Select Case True", c="If isReady Then"),
    r("maint", id="vb:throw-ex", type="bug", qual="rel", sev="medium", cwe="",
      title="Throw ex resets exception origin", desc="A Catch block rethrows a named exception with Throw ex.",
      rationale="Throwing the captured exception resets stack information needed to diagnose the original failure.",
      remediation="Use bare Throw to preserve the exception stack.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/throw-statement",
      re=r"(?i)^\s*Throw\s+[A-Za-z_]\w*\s*$", nc="Throw ex", c="Throw"),
    r("maint", id="vb:catch-exception", type="smell", qual="maint", sev="low", cwe="",
      title="Catch handles the base Exception type", desc="A Catch clause catches System.Exception or Exception.",
      rationale="Catching every application exception obscures which failures are recoverable and can hide programming errors.",
      remediation="Catch only the specific exception types the operation can recover from.", source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031",
      re=r"(?i)^\s*Catch\s+(?:[A-Za-z_]\w*\s+As\s+)?(?:System\.)?Exception\b", nc="Catch ex As Exception", c="Catch ex As IOException"),
    r("maint", id="vb:goto", type="smell", qual="maint", sev="low", cwe="",
      title="GoTo statement used", desc="Code transfers control with GoTo.",
      rationale="Non-local jumps make control flow harder to follow and complicate later maintenance.",
      remediation="Use structured loops, methods, or an early return.", source="https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/goto-statement",
      re=r"(?i)^\s*GoTo\s+[A-Za-z_]\w*\b", nc="GoTo Retry", c="Continue While"),
    r("maint", id="vb:notimplementedexception", type="bug", qual="rel", sev="medium", cwe="",
      title="NotImplementedException shipped", desc="A member throws NotImplementedException.",
      rationale="An unfinished member fails at runtime when production code reaches it.",
      remediation="Implement the member or remove the unavailable path.", source="https://learn.microsoft.com/en-us/dotnet/api/system.notimplementedexception",
      re=r"(?i)\bThrow\s+New\s+NotImplementedException\s*\(", nc="Throw New NotImplementedException()", c="Return items.Count"),
    r("maint", id="vb:todo-marker", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="TODO or FIXME marker", desc="A comment marks unfinished work with TODO, FIXME, or HACK.",
      rationale="Visible debt markers should be resolved or linked to a tracked work item.",
      remediation="Resolve the item or link it to an issue.", source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r"(?i)'\s*(?:TODO|FIXME|HACK)\b", nc="' TODO: validate the input length", c="' Validates the input length below"),
]
