CC = "commentOnlyLine"
def r(**k):
    k.setdefault("lang","js"); k.setdefault("owasp",""); k.setdefault("effort",15)
    k.setdefault("tags",["sast","javascript"]); k.setdefault("cat_desc",k["desc"]); k.setdefault("skip",CC)
    return k
RULES = [
    r(id="js-no-extra-semi", type="smell", qual="maint", sev="info", cwe="", title="Unnecessary extra semicolon",
      desc="A redundant empty statement (;;) is dead syntax.",
      rationale="An extra semicolon creates an empty statement that has no effect and usually signals an editing mistake.",
      remediation="Remove the redundant semicolon.",
      source="https://eslint.org/docs/latest/rules/no-extra-semi",
      re=r";;", nc="notify();;", c="notify();"),
    r(id="js-no-throw-literal", type="bug", qual="rel", sev="low", cwe="", title="Throwing a non-Error literal",
      desc="Throwing a string/literal loses the stack trace and Error semantics.",
      rationale="Throwing a non-Error value gives no stack trace and breaks instanceof Error handling in catch sites.",
      remediation="Throw an Error (or subclass) instead of a literal.",
      source="https://eslint.org/docs/latest/rules/no-throw-literal",
      re=r"\bthrow\s+['\"]", nc='throw "boom";', c='throw new Error("boom");'),
    r(id="js-no-return-await", type="smell", qual="maint", sev="low", cwe="", title="Redundant return await",
      desc="`return await x` adds an extra microtask without changing behaviour outside try.",
      rationale="Outside a try block, return await is equivalent to return but adds an extra await tick; returning the promise directly is clearer.",
      remediation="Return the promise directly (keep await only inside try/finally).",
      source="https://eslint.org/docs/latest/rules/no-return-await",
      re=r"\breturn\s+await\s+", nc="return await fetchIt();", c="return fetchIt();"),
    r(id="js-no-unsafe-negation", type="bug", qual="rel", sev="medium", cwe="", title="Unsafe negation of in/instanceof",
      desc="`!a in b` negates `a` first; you almost certainly meant `!(a in b)`.",
      rationale="Operator precedence makes !a in b evaluate (!a) in b, testing whether the boolean is a key — rarely the intent.",
      remediation="Parenthesise: !(a in b) / !(a instanceof B).",
      source="https://eslint.org/docs/latest/rules/no-unsafe-negation",
      re=r"!\s*[A-Za-z_$][\w$.]*\s+(in|instanceof)\b", nc="if (!key in obj) return;", c="if (!(key in obj)) return;"),
    r(id="js-script-url", type="vuln", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021", title="javascript: URL",
      desc="A javascript: URL executes code when navigated, a stored-XSS vector.",
      rationale="Assigning a javascript: URL to href/src executes script in the page origin; if any part is attacker-influenced this is XSS.",
      remediation="Use a normal URL and attach behaviour via an event listener.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"['\"]javascript:", nc='link.href = "javascript:steal()";', c='link.href = "https://app.internal/go";'),
    r(id="js-document-cookie-write", type="hotspot", qual="sec", sev="low", cwe="CWE-1004", owasp="A05:2021", title="Direct document.cookie write",
      desc="Setting document.cookie in script cannot produce an HttpOnly cookie.",
      rationale="Cookies written from JavaScript are readable by JavaScript (never HttpOnly), so an XSS can steal them; set sensitive cookies server-side.",
      remediation="Set sensitive cookies from the server with HttpOnly and Secure.",
      source="https://cwe.mitre.org/data/definitions/1004.html",
      re=r"document\.cookie\s*=[^=]", nc='document.cookie = "sid=" + token;', c='setSessionCookieServerSide(token);'),
    r(id="js-no-sparse-array", type="bug", qual="rel", sev="low", cwe="", title="Sparse array with holes",
      desc="An elided element ([, 1]) creates a hole that many methods skip.",
      rationale="Sparse arrays with holes behave inconsistently across iteration methods and usually indicate a typo (a doubled or leading comma).",
      remediation="Fill the element explicitly, or remove the extra comma.",
      source="https://eslint.org/docs/latest/rules/no-sparse-arrays",
      re=r"\[\s*,", nc="const a = [, first];", c="const a = [empty, first];"),
    r(id="js-no-multi-assign", type="smell", qual="maint", sev="low", cwe="", title="Chained assignment",
      desc="`a = b = c` chains assignments and is easy to misread.",
      rationale="Chained assignment obscures which variables are written and can create unintended globals; separate statements are clearer.",
      remediation="Assign each variable on its own statement.",
      source="https://eslint.org/docs/latest/rules/no-multi-assign",
      re=r"[A-Za-z_$][\w$.]*\s*=\s*[A-Za-z_$][\w$.]*\s*=\s*[^=]", nc="first = second = 0;", c="first = 0;"),
    r(id="ts-prefer-namespace", type="smell", qual="maint", sev="low", cwe="", title="Legacy module keyword",
      desc="TypeScript's `module` keyword is legacy; use `namespace`.",
      rationale="The internal `module` keyword predates ES modules and is confusing next to real modules; `namespace` is the current spelling.",
      remediation="Use the namespace keyword.",
      source="https://typescript-eslint.io/rules/prefer-namespace-keyword/",
      re=r"\bmodule\s+[A-Za-z]", nc="module Legacy { export const x = 1; }", c="namespace Legacy { export const x = 1; }", tags=["sast","typescript"]),
    r(id="js-no-empty-block", type="smell", qual="maint", sev="low", cwe="", title="Empty block statement",
      desc="An empty {} block is dead code or a forgotten body.",
      rationale="An empty block usually means a forgotten implementation or leftover scaffolding.",
      remediation="Remove the empty block or add the intended statements (with a comment if intentional).",
      source="https://eslint.org/docs/latest/rules/no-empty",
      re=r"\)\s*\{\s*\}\s*(else|$|;)", nc="if (ready) {} else start();", c="if (ready) { begin(); } else start();"),
]
