CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","js");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","node"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="node-trust-proxy-true",type="hotspot",qual="sec",sev="low",cwe="CWE-348",owasp="A07:2021",title="Express trust proxy set to true",
   desc="trust proxy = true trusts the X-Forwarded-For header from any hop, allowing IP spoofing.",
   rationale="Blanket trust of forwarding headers lets a client spoof its source IP, defeating rate-limits and IP allow-lists.",
   remediation="Set trust proxy to a specific hop count or subnet, not true.",
   source="https://cwe.mitre.org/data/definitions/348.html",
   re=r"['\"]trust proxy['\"]\s*,\s*true",nc='app.set("trust proxy", true);',c='app.set("trust proxy", 1);'),
 r(id="node-csurf-deprecated",type="smell",qual="maint",sev="low",cwe="",title="Deprecated csurf middleware",
   desc="The csurf package is deprecated and unmaintained.",
   rationale="csurf was deprecated with known issues; relying on it leaves CSRF protection on unmaintained code.",
   remediation="Use a maintained CSRF mechanism (e.g. csrf-csrf or framework support).",
   source="https://github.com/expressjs/csurf",
   re=r"require\s*\(\s*['\"]csurf['\"]\s*\)",nc='const csrf = require("csurf");',c='const { doubleCsrf } = require("csrf-csrf");'),
 r(id="node-body-parser-deprecated",type="smell",qual="maint",sev="low",cwe="",title="Standalone body-parser",
   desc="body-parser is bundled into Express 4.16+ as express.json()/urlencoded().",
   rationale="A separate body-parser dependency is redundant on modern Express and adds an unnecessary package.",
   remediation="Use express.json() / express.urlencoded().",
   source="https://expressjs.com/en/api.html#express.json",
   re=r"require\s*\(\s*['\"]body-parser['\"]\s*\)",nc='const bp = require("body-parser");',c="app.use(express.json());"),
 r(id="node-tls-weak-ciphers",type="hotspot",qual="sec",sev="medium",cwe="CWE-327",owasp="A02:2021",title="Weak TLS cipher configured",
   desc="A cipher list containing RC4/DES/MD5/NULL/EXPORT enables broken cryptography.",
   rationale="These legacy ciphers are broken or export-grade; offering them allows downgrade to insecure encryption.",
   remediation="Use modern AEAD ciphers (e.g. TLS_AES_256_GCM_SHA384) and let the platform default win.",
   source="https://cwe.mitre.org/data/definitions/327.html",
   re=r"ciphers\s*:\s*['\"][^'\"]*(RC4|DES|MD5|NULL|EXPORT)",nc='const o = { ciphers: "RC4-MD5" };',c='const o = { ciphers: "TLS_AES_256_GCM_SHA384" };'),
 r(id="node-process-umask-zero",type="hotspot",qual="sec",sev="medium",cwe="CWE-266",owasp="A01:2021",title="process.umask(0)",
   desc="umask(0) makes newly created files world-writable by default.",
   rationale="A zero umask removes all default permission masking, so files/dirs are created world-readable/writable.",
   remediation="Set a restrictive umask (e.g. 0o077) or omit the call.",
   source="https://cwe.mitre.org/data/definitions/266.html",
   re=r"process\.umask\s*\(\s*0\s*\)",nc="process.umask(0);",c="process.umask(0o077);"),
 r(id="node-punycode-deprecated",type="smell",qual="maint",sev="low",cwe="",title="Deprecated punycode module",
   desc="The core punycode module is deprecated.",
   rationale="Node's built-in punycode is deprecated and slated for removal; use the userland package or the WHATWG URL.",
   remediation="Use the userland 'punycode/' package or the URL API.",
   source="https://nodejs.org/api/punycode.html",
   re=r"require\s*\(\s*['\"]punycode['\"]\s*\)",nc='const p = require("punycode");',c='const url = new URL(input);'),
 r(id="node-util-isarray",type="smell",qual="maint",sev="low",cwe="",title="Deprecated util.isArray",
   desc="util.isArray is deprecated; Array.isArray is the standard.",
   rationale="util.isArray is a legacy shim deprecated in favor of the built-in Array.isArray.",
   remediation="Use Array.isArray(x).",
   source="https://nodejs.org/api/util.html#utilisarrayobject",
   re=r"\butil\.isArray\s*\(",nc="if (util.isArray(rows)) {}",c="if (Array.isArray(rows)) {}"),
 r(id="node-sys-module",type="bug",qual="rel",sev="medium",cwe="",title="Removed sys module",
   desc="require('sys') refers to a module removed from Node.",
   rationale="The sys module was renamed to util years ago and removed; requiring it throws on modern Node.",
   remediation="Use require('util').",
   source="https://nodejs.org/api/util.html",
   re=r"require\s*\(\s*['\"]sys['\"]\s*\)",nc='const sys = require("sys");',c='const util = require("util");'),
 r(id="node-csp-unsafe-inline",type="hotspot",qual="sec",sev="medium",cwe="CWE-79",owasp="A05:2021",title="CSP allows unsafe-inline",
   desc="A Content-Security-Policy with 'unsafe-inline' permits inline scripts/styles, weakening XSS defense.",
   rationale="unsafe-inline lets inline scripts run, which largely defeats the XSS mitigation a CSP is meant to provide.",
   remediation="Remove unsafe-inline; use nonces or hashes for the scripts you need.",
   source="https://cwe.mitre.org/data/definitions/79.html",
   re=r"unsafe-inline",nc='scriptSrc: ["\x27self\x27", "\x27unsafe-inline\x27"]',c='scriptSrc: ["\x27self\x27"]'),
 r(id="node-csp-unsafe-eval",type="hotspot",qual="sec",sev="medium",cwe="CWE-95",owasp="A05:2021",title="CSP allows unsafe-eval",
   desc="A CSP with 'unsafe-eval' permits eval()/new Function, re-enabling a code-injection sink.",
   rationale="unsafe-eval allows string-to-code execution, undermining the CSP's protection against injected code.",
   remediation="Remove unsafe-eval and avoid runtime code evaluation.",
   source="https://cwe.mitre.org/data/definitions/95.html",
   re=r"unsafe-eval",nc='scriptSrc: ["\x27self\x27", "\x27unsafe-eval\x27"]',c='scriptSrc: ["\x27self\x27"]'),
]
