# Scala language-pack rule specs (#207).
# Clean-room, precision-biased line rules. The Scala tree-sitter grammar is already registered;
# the dedicated cognitive-complexity rule is implemented in astwalk rather than approximated here.
CC = "commentOnlyLine"
STRING_SOURCE = r'(?:\b(?:scala\.)?sys\.env\s*\([^)]*\)|\bSystem\.getenv\s*\([^)]*\)|\bscala\.io\.StdIn\.readLine\s*\([^)]*\))'


def r(fam, **k):
    k.setdefault("lang", "scala")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "scala", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r('bugs',
      id='scala:option-get',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Unsafe get on an Option or Try value',
      desc='A value is accessed with the partial get operation, which throws when the container is empty or failed.',
      rationale='Option.get and Try.get turn an expected absence or failure into a runtime exception, making normal error states crash the current operation.',
      remediation='Use pattern matching, fold, getOrElse, or propagate the failure explicitly.',
      source='https://www.scala-lang.org/api/current/',
      re='\\.get\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val account = maybeAccount.get',
      c='val account = maybeAccount.getOrElse(defaultAccount)'),
    r('bugs',
      id='scala:collection-head',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Partial collection head access',
      desc='The head operation throws when the collection is empty.',
      rationale='Collection.head is a partial operation and raises an exception for an empty collection, which is often a valid runtime state.',
      remediation='Use headOption and handle None, or prove non-emptiness before accessing the first element.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.head\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val first = values.head',
      c='val first = values.headOption'),
    r('bugs',
      id='scala:collection-tail',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Partial collection tail access',
      desc='The tail operation throws when the collection is empty.',
      rationale='Collection.tail is undefined for an empty collection and converts a routine boundary condition into an exception.',
      remediation='Use drop(1), pattern matching, or check nonEmpty before taking the tail.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.tail\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val rest = values.tail',
      c='val rest = values.drop(1)'),
    r('bugs',
      id='scala:collection-init',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Partial collection init access',
      desc='The init operation throws when the collection is empty.',
      rationale='Collection.init requires at least one element and fails at runtime for an empty input.',
      remediation='Use dropRight(1), pattern matching, or establish that the collection is non-empty.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.init\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val prefix = values.init',
      c='val prefix = values.dropRight(1)'),
    r('bugs',
      id='scala:collection-last',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Partial collection last access',
      desc='The last operation throws when the collection is empty.',
      rationale='Collection.last is a partial operation and cannot represent the empty case safely.',
      remediation='Use lastOption and handle None, or validate non-emptiness first.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.last\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val finalValue = values.last',
      c='val finalValue = values.lastOption'),
    r('bugs',
      id='scala:collection-reduce',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Reduction without an empty-case value',
      desc='A collection is reduced with an operation that throws for empty input.',
      rationale='reduce, reduceLeft, and reduceRight require at least one element; an empty collection causes a runtime exception.',
      remediation='Use fold/foldLeft/foldRight with an identity value or handle the empty case explicitly.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.(?:reduce|reduceLeft|reduceRight)\\s*\\(',
      nc='val total = values.reduce(_ + _)',
      c='val total = values.foldLeft(0)(_ + _)'),
    r('bugs',
      id='scala:iterator-next',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Iterator next called directly',
      desc='Iterator.next throws when no element remains.',
      rationale='Calling next without a proven hasNext condition makes exhausted iterators fail with NoSuchElementException.',
      remediation='Use hasNext, collect through a safe collection operation, or expose the result as an Option.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.next\\s*\\(\\s*\\)',
      nc='val item = iterator.next()',
      c='val item = iterator.take(1).toList.headOption'),
    r('bugs',
      id='scala:string-to-int',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Unchecked String toInt conversion',
      desc='String.toInt throws when the input is not a valid integer.',
      rationale='Text received from files, requests, or users can be malformed; toInt converts that expected validation failure into NumberFormatException.',
      remediation='Use toIntOption, Try, or a validated parser and handle the failure.',
      source='https://www.scala-lang.org/api/current/',
      re=STRING_SOURCE + '\\.toInt\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val port = sys.env("PORT").toInt',
      c='val port = sys.env("PORT").toIntOption'),
    r('bugs',
      id='scala:string-to-long',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Unchecked String toLong conversion',
      desc='String.toLong throws when the input is not a valid long integer.',
      rationale='Unchecked numeric parsing makes malformed external input raise NumberFormatException instead of producing a controlled validation result.',
      remediation='Use toLongOption, Try, or a validated parser and handle the failure.',
      source='https://www.scala-lang.org/api/current/',
      re=STRING_SOURCE + '\\.toLong\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val size = System.getenv("MAX_SIZE").toLong',
      c='val size = System.getenv("MAX_SIZE").toLongOption'),
    r('bugs',
      id='scala:string-to-double',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-248',
      title='Unchecked String toDouble conversion',
      desc='String.toDouble throws when the input is not a valid floating-point value.',
      rationale='Unchecked numeric parsing turns ordinary invalid input into an exception and may bypass normal validation handling.',
      remediation='Use toDoubleOption, Try, or a validated parser and handle the failure.',
      source='https://www.scala-lang.org/api/current/',
      re=STRING_SOURCE + '\\.toDouble\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val ratio = scala.io.StdIn.readLine().toDouble',
      c='val ratio = scala.io.StdIn.readLine().toDoubleOption'),
    r('bugs',
      id='scala:unimplemented-expression',
      type='bug',
      qual='rel',
      sev='high',
      cwe='CWE-248',
      title='Unimplemented expression left in executable code',
      desc='The Scala ??? placeholder throws NotImplementedError whenever execution reaches it.',
      rationale='The placeholder compiles successfully, so unfinished code can reach production and fail only when the path is exercised.',
      remediation='Implement the expression or return a typed error that callers can handle.',
      source='https://www.scala-lang.org/api/current/',
      re='\\?\\?\\?',
      nc='def loadAccount(id: String): Account = ???',
      c='def loadAccount(id: String): Either[Error, Account] = repository.load(id)'),
    r('bugs',
      id='scala:collection-apply-index',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-125',
      title='Direct collection index access',
      desc='A collection constructed on the line is indexed with apply, which throws for an invalid index.',
      rationale='Indexed apply is a partial operation; an index outside the collection bounds raises an exception.',
      remediation='Use lift(index), applyOrElse where appropriate, or validate the index before access.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\b(?:List|Vector|Seq|Array)\\s*\\([^;\\n]*\\)\\s*\\(\\s*[A-Za-z_]\\w*\\s*\\)',
      nc='val selected = Vector(10, 20, 30)(index)',
      c='val selected = Vector(10, 20, 30).lift(index)'),
    r('err',
      id='scala:catch-throwable',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-396',
      title='Catch clause handles Throwable',
      desc='A catch clause intercepts Throwable, including fatal JVM errors that application code should not normally recover from.',
      rationale='Catching Throwable can absorb virtual-machine and linkage failures, leaving the process in an unreliable state.',
      remediation='Catch only the specific non-fatal exceptions the operation can recover from.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\bcase\\s+[^=\\n]*:\\s*Throwable\\s*=>',
      nc='try work() catch { case problem: Throwable => fallback() }',
      c='try work() catch { case problem: IOException => fallback() }'),
    r('err',
      id='scala:catch-all',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-396',
      title='Catch-all case discards exception type',
      desc='A catch block uses case _ and handles every thrown value without preserving its type.',
      rationale='A catch-all case hides programming errors and makes it impossible to distinguish failures that require different recovery actions.',
      remediation='Match the expected exception classes and let unexpected failures propagate.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\bcatch\\s*\\{[^\\n}]*\\bcase\\s+_\\s*=>',
      nc='try work() catch { case _ => fallback() }',
      c='try work() catch { case problem: IOException => fallback() }'),
    r('err',
      id='scala:empty-catch',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-390',
      title='Exception is silently swallowed',
      desc='A catch case resolves to Unit without logging, recovery, or propagation.',
      rationale='Silently swallowing an exception hides the failed operation and leaves callers believing that it completed successfully.',
      remediation='Handle the failure, add contextual logging, or rethrow/return a typed error.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\bcatch\\s*\\{[^\\n}]*=>\\s*(?:\\(\\)|\\{\\s*\\})\\s*\\}',
      nc='try write() catch { case _: IOException => () }',
      c='try write() catch { case problem: IOException => logger.warn("write failed", problem) }'),
    r('err',
      id='scala:throw-usage',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='CWE-248',
      title='Explicit throw used for ordinary control flow',
      desc='The code throws an exception directly instead of representing a recoverable failure in the return type.',
      rationale='Routine failure represented by throw is invisible in the method type and encourages broad exception handling at distant call sites.',
      remediation='Return Either, Try, Option, or a domain-specific result and reserve exceptions for exceptional boundaries.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\bthrow\\s+(?:new\\s+)?[A-Z][A-Za-z0-9_]*',
      nc='if (account == null) throw new IllegalArgumentException("account")',
      c='if (account == null) Left(InvalidAccount)'),
    r('err',
      id='scala:recover-all',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-396',
      title='Future recovery catches every failure',
      desc='A recover or recoverWith block uses case _ and converts every failure to the same result.',
      rationale='Catching all Future failures can mask cancellation, programming defects, and infrastructure faults that should remain visible.',
      remediation='Recover only the expected exception types and preserve unexpected failures.',
      source='https://docs.scala-lang.org/overviews/core/futures.html',
      re='\\.(?:recover|recoverWith)\\s*\\{[^\\n}]*\\bcase\\s+_\\s*=>',
      nc='request().recover { case _ => cachedValue }',
      c='request().recover { case _: TimeoutException => cachedValue }'),
    r('conc',
      id='scala:future-blocking',
      type='bug',
      qual='rel',
      sev='medium',
      cwe='CWE-667',
      title='Blocking Await in asynchronous code',
      desc='Await.result or Await.ready blocks the current thread until a Future completes.',
      rationale='Blocking a Future execution thread can starve the execution context and create latency spikes or deadlocks under load.',
      remediation='Compose Futures with map, flatMap, for-comprehensions, or return the Future to the caller.',
      source='https://docs.scala-lang.org/overviews/core/futures.html',
      re='\\bAwait\\.(?:result|ready)\\s*\\(',
      nc='val response = Await.result(fetch(), 5.seconds)',
      c='val response = fetch().map(process)',
      effort=30),
    r('conc',
      id='scala:execution-context-global',
      type='hotspot',
      qual='sec',
      sev='medium',
      cwe='CWE-400',
      title='Global execution context requires review',
      desc='The process-wide ExecutionContext.global pool is used directly.',
      rationale='The global pool is shared by unrelated work; blocking or high-volume tasks can interfere with the entire process and make capacity isolation impossible.',
      remediation='Inject a purpose-specific ExecutionContext sized for the workload and isolate blocking operations.',
      source='https://docs.scala-lang.org/overviews/core/futures.html',
      re='\\bExecutionContext\\.global\\b',
      nc='implicit val ec: ExecutionContext = ExecutionContext.global',
      c='implicit val ec: ExecutionContext = appExecutionContext',
      effort=30),
    r('conc',
      id='scala:blocking-in-future',
      type='bug',
      qual='rel',
      sev='high',
      cwe='CWE-400',
      title='Thread sleep inside Future body',
      desc='A Future body directly calls Thread.sleep.',
      rationale='Sleeping inside a Future occupies a worker thread without doing useful work and can exhaust a bounded execution context.',
      remediation='Use a scheduler/timer to complete the Future later, or isolate the blocking operation in a dedicated execution context.',
      source='https://docs.scala-lang.org/overviews/core/futures.html',
      re='\\bFuture\\s*\\{[^\\n}]*\\bThread\\.sleep\\s*\\(',
      nc='val delayed = Future { Thread.sleep(1000); compute() }',
      c='val delayed = scheduler.after(1.second)(compute())',
      effort=30),
    r('conc',
      id='scala:unmanaged-thread',
      type='hotspot',
      qual='sec',
      sev='medium',
      cwe='CWE-400',
      title='Unmanaged thread creation',
      desc='The code constructs a Thread directly.',
      rationale='Ad-hoc threads bypass application lifecycle, naming, limits, supervision, and centralized failure handling.',
      remediation='Use an injected Executor/ExecutionContext or a managed runtime abstraction.',
      source='https://docs.scala-lang.org/overviews/core/futures.html',
      re='\\bnew\\s+Thread\\s*\\(',
      nc='val worker = new Thread(() => runJob())',
      c='val worker = Future(runJob())(jobExecutionContext)',
      effort=30),
    r('conc',
      id='scala:parallel-collection',
      type='hotspot',
      qual='sec',
      sev='low',
      cwe='CWE-400',
      title='Implicit parallel collection execution',
      desc='A collection is converted with par, moving work to an implicit parallel execution pool.',
      rationale='Parallel collections make scheduling and resource use less explicit and can overload shared pools for small or blocking operations.',
      remediation='Use an explicit bounded execution context and measure that parallel execution benefits this workload.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.par\\s*(?:$|[;,\\)\\]\\}\\.+\\-*/])',
      nc='val hashes = records.par.map(hashRecord)',
      c='val hashes = records.map(hashRecord)',
      effort=30),
    r('api',
      id='scala:return-keyword',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Explicit return keyword',
      desc="A method uses return instead of Scala's expression-oriented result.",
      rationale='Explicit return makes control flow less compositional and can interact unexpectedly with closures through non-local returns.',
      remediation='Make the intended value the final expression or restructure the method with smaller expressions.',
      source='https://docs.scala-lang.org/style/',
      re='\\breturn\\b',
      nc='if (invalid) return Left(InvalidInput)',
      c='if (invalid) Left(InvalidInput) else validate()',
      effort=5),
    r('api',
      id='scala:java-conversions-deprecated',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='',
      title='Deprecated JavaConversions API',
      desc='The deprecated scala.collection.JavaConversions implicit conversion API is referenced.',
      rationale='Global implicit collection conversions obscure allocation and mutation boundaries and were replaced by explicit converters.',
      remediation='Import scala.jdk.CollectionConverters._ and call asJava/asScala explicitly.',
      source='https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html',
      re='\\b(?:scala\\.collection\\.)?JavaConversions\\b',
      nc='import scala.collection.JavaConversions._',
      c='import scala.jdk.CollectionConverters._'),
    r('api',
      id='scala:java-converters-deprecated',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Legacy JavaConverters API',
      desc='The scala.collection.JavaConverters compatibility API is referenced.',
      rationale='Scala 2.13 and Scala 3 provide scala.jdk.CollectionConverters as the maintained explicit conversion API.',
      remediation='Use scala.jdk.CollectionConverters._ and explicit asJava/asScala conversions.',
      source='https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html',
      re='\\b(?:scala\\.collection\\.)?JavaConverters\\b',
      nc='import scala.collection.JavaConverters._',
      c='import scala.jdk.CollectionConverters._'),
    r('api',
      id='scala:collection-breakout-deprecated',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='',
      title='Deprecated collection.breakOut',
      desc='The removed collection.breakOut builder is used.',
      rationale='breakOut depended on implicit collection-builder behavior that changed in Scala 2.13 and is unavailable in Scala 3.',
      remediation='Use an explicit target conversion such as .to(List), .toVector, or a collection factory.',
      source='https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html',
      re='\\b(?:scala\\.)?collection\\.breakOut\\b|\\bbreakOut\\b',
      nc='val ids: Vector[Int] = rows.map(_.id)(collection.breakOut)',
      c='val ids: Vector[Int] = rows.iterator.map(_.id).toVector',
      effort=30),
    r('api',
      id='scala:procedure-syntax',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='',
      title='Deprecated procedure syntax',
      desc='A method body starts without an equals sign, using removed Scala 2 procedure syntax.',
      rationale='Procedure syntax hides the Unit return type and is no longer accepted by Scala 3.',
      remediation='Declare the return type and equals sign explicitly, for example def run(): Unit = { ... }.',
      source='https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html',
      re='^\\s*(?:(?:private|protected|final|override|implicit)\\s+)*def\\s+[A-Za-z_]\\w*\\s*(?:\\[[^\\]]+\\]\\s*)?\\([^)]*\\)\\s*\\{',
      nc='def record(event: Event) { audit.append(event) }',
      c='def record(event: Event): Unit = { audit.append(event) }'),
    r('api',
      id='scala:delayed-init-deprecated',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='',
      title='Deprecated DelayedInit inheritance',
      desc='A class or object inherits from DelayedInit.',
      rationale='DelayedInit changes initialization semantics in surprising ways and is deprecated/removed from modern Scala.',
      remediation='Move startup logic into an explicit main method, constructor, or lifecycle hook.',
      source='https://docs.scala-lang.org/scala3/guides/migration/incompat-dropped-features.html',
      re='\\b(?:extends|with)\\s+DelayedInit\\b',
      nc='object Server extends DelayedInit',
      c='object Server { def main(args: Array[String]): Unit = start() }',
      effort=30),
    r('types',
      id='scala:null-usage',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='CWE-476',
      title='Null literal used in Scala code',
      desc='The null literal is assigned, returned, or compared directly.',
      rationale="Null bypasses Scala's type-level representation of absence and reintroduces NullPointerException paths.",
      remediation='Represent absence with Option or a domain-specific sum type and convert Java nulls at the boundary.',
      source='https://docs.scala-lang.org/style/',
      re='(?:=\\s*null\\b|\\breturn\\s+null\\b|\\bnull\\s*[:;,\\)\\]\\}])',
      nc='val owner: User = null',
      c='val owner: Option[User] = None',
      effort=30),
    r('types',
      id='scala:asinstanceof',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='CWE-704',
      title='Unchecked asInstanceOf cast',
      desc='The code performs an unchecked runtime cast with asInstanceOf.',
      rationale='A failed cast throws ClassCastException and usually indicates that the type model does not express the actual alternatives.',
      remediation='Use pattern matching, type classes, generics, or a safe decoding API.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\.asInstanceOf\\s*\\[',
      nc='val admin = principal.asInstanceOf[Admin]',
      c='val admin = principal match { case value: Admin => Some(value); case _ => None }',
      effort=30),
    r('types',
      id='scala:isinstanceof',
      type='smell',
      qual='maint',
      sev='low',
      cwe='CWE-704',
      title='Manual isInstanceOf type test',
      desc='The code tests a runtime type with isInstanceOf.',
      rationale='Manual type tests often pair with unsafe casts and bypass exhaustive pattern matching.',
      remediation='Use pattern matching or polymorphism so the compiler can check the alternatives.',
      source='https://scalacenter.github.io/scalafix/docs/rules/overview.html',
      re='\\.isInstanceOf\\s*\\[',
      nc='if (principal.isInstanceOf[Admin]) allow()',
      c='principal match { case _: Admin => allow(); case _ => deny() }'),
    r('types',
      id='scala:option-or-null',
      type='smell',
      qual='maint',
      sev='medium',
      cwe='CWE-476',
      title='Option converted back to null',
      desc='Option.orNull converts a typed absence into a null reference.',
      rationale='Converting Option to null discards the type-level guarantee and moves the failure risk to downstream code.',
      remediation='Keep the value as Option or convert it only at a Java interoperability boundary.',
      source='https://www.scala-lang.org/api/current/',
      re='\\.orNull\\b',
      nc='val owner: User = maybeOwner.orNull',
      c='val owner: Option[User] = maybeOwner'),
    r('perf',
      id='scala:filter-size',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Filter followed by size',
      desc='A collection is filtered and then fully materialized/traversed only to count matching elements.',
      rationale='filter(...).size may allocate an intermediate collection and communicates the intent less directly than count.',
      remediation='Use count(predicate).',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.filter\\s*\\([^)]*\\)\\.(?:size|length)\\b',
      nc='val activeCount = users.filter(_.active).size',
      c='val activeCount = users.count(_.active)',
      effort=5),
    r('perf',
      id='scala:map-flatten',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Map followed by flatten',
      desc='A collection uses map(...).flatten instead of flatMap.',
      rationale='map followed by flatten creates an avoidable intermediate structure and obscures the one-to-many transformation.',
      remediation='Use flatMap directly.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.map\\s*\\([^)]*\\)\\.flatten\\b',
      nc='val children = parents.map(_.children).flatten',
      c='val children = parents.flatMap(_.children)',
      effort=5),
    r('perf',
      id='scala:reverse-head',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Collection reversed to access the last element',
      desc='The code reverses a collection and immediately takes head.',
      rationale='Reversing the entire collection does unnecessary work when only the final element is needed.',
      remediation='Use lastOption/last when the collection semantics make that safe.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\.reverse\\.head\\b',
      nc='val finalItem = values.reverse.head',
      c='val finalItem = values.lastOption',
      effort=5),
    r('maint',
      id='scala:var-in-functional',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Mutable var declaration',
      desc='A local or member variable is declared with var.',
      rationale='Reassignment increases the number of states a reader must track and makes functional transformations harder to compose and test.',
      remediation='Prefer val and derive new values with expressions; isolate mutation behind a narrow abstraction when necessary.',
      source='https://docs.scala-lang.org/style/',
      re='^\\s*(?:(?:private|protected|final|override|implicit)\\s+)*var\\s+[A-Za-z_]\\w*',
      nc='var total = 0',
      c='val total = values.sum'),
    r('maint',
      id='scala:wildcard-import',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Wildcard import',
      desc='An import brings every member from a namespace into scope.',
      rationale='Wildcard imports hide dependencies, increase naming collisions, and make code review less explicit.',
      remediation='Import the specific names used by the file.',
      source='https://docs.scala-lang.org/style/',
      re='^\\s*import\\s+.+(?:\\._|\\.\\*)\\s*$',
      nc='import scala.concurrent.duration._',
      c='import scala.concurrent.duration.DurationInt',
      effort=5),
    r('maint',
      id='scala:println-logging',
      type='smell',
      qual='maint',
      sev='info',
      cwe='',
      title='println used for application logging',
      desc='The code writes operational output with println.',
      rationale='println has no levels, structured fields, correlation context, or configurable sink and is difficult to manage in production.',
      remediation="Use the project's structured logging abstraction.",
      source='https://docs.scala-lang.org/style/',
      re='\\b(?:Predef\\.)?println\\s*\\(',
      nc='println(s"loaded ${accounts.size} accounts")',
      c='logger.info("loaded accounts", "count" -> accounts.size)',
      effort=5),
    r('maint',
      id='scala:mutable-collection',
      type='smell',
      qual='maint',
      sev='low',
      cwe='',
      title='Mutable collection API referenced',
      desc='The code imports or references scala.collection.mutable.',
      rationale='Mutable collections expose in-place state changes that complicate reasoning, sharing, and concurrent use.',
      remediation='Prefer immutable collections and confine mutation to a small, well-documented boundary where it is measurably necessary.',
      source='https://docs.scala-lang.org/overviews/collections-2.13/',
      re='\\bscala\\.collection\\.mutable(?:\\.|\\b)',
      nc='import scala.collection.mutable.ArrayBuffer',
      c='import scala.collection.immutable.Vector',
      effort=30),
    r('inj',
      id='scala:sql-interpolation',
      type='vuln',
      qual='sec',
      sev='high',
      cwe='CWE-89',
      owasp='A03:2021',
      title='SQL query built with string interpolation',
      desc='A JDBC SQL sink receives an interpolated Scala string containing a SQL statement.',
      rationale='Interpolating values into SQL changes query structure and can allow attacker-controlled input to become executable SQL.',
      remediation='Use a PreparedStatement with placeholders and bind every external value through typed parameters.',
      source='https://cwe.mitre.org/data/definitions/89.html',
      re='(?i)\\b(?:prepareStatement|executeQuery|executeUpdate)\\s*\\(\\s*s(?:"""|")[^"\\n]*\\b(?:select|insert|update|delete)\\b[^"\\n]*\\$(?:\\{|[A-Za-z_])',
      nc='val statement = connection.prepareStatement(s"SELECT * FROM users WHERE id = $userId")',
      c='val statement = connection.prepareStatement("SELECT * FROM users WHERE id = ?")',
      effort=30),
]
