# JS/TS language-pack rule specs (#188). Line-detectable rules only; families needing
# type-flow/complexity/cross-procedural analysis are AST-tier (E39), not emitted here.
CC = "commentOnlyLine"

def r(**k):
    k.setdefault("lang", "js")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "javascript"])
    k.setdefault("cat_desc", k["desc"])
    return k

RULES = [
    # ── maintainability / style ──────────────────────────────────────────────
    r(id="js-no-var", type="smell", qual="maint", sev="low", cwe="", title="Use let/const instead of var",
      desc="`var` is function-scoped and hoisted; `let`/`const` are block-scoped and safer.",
      rationale="var declarations are hoisted and function-scoped, which leads to surprising closures and accidental redeclaration. let/const are block-scoped.",
      remediation="Replace var with const (or let if the binding is reassigned).",
      source="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var",
      re=r"\bvar\s+[A-Za-z_$]", nc="var count = 0;", c="const count = 0;", skip=CC, tags=["sast","javascript","es6"]),
    r(id="js-no-console", type="smell", qual="maint", sev="info", cwe="", title="Leftover console statement",
      desc="A console.* call left in shipped code leaks internals and clutters output.",
      rationale="console statements are debugging aids that should not ship; they can leak data to the browser console and add noise.",
      remediation="Remove the console call or route through a configurable logger.",
      source="https://eslint.org/docs/latest/rules/no-console",
      re=r"\bconsole\.(log|debug|info|warn|error|trace|dir)\s*\(", nc="console.log(user);", c="logger.info(user);", skip=CC),
    r(id="js-no-debugger", type="smell", qual="maint", sev="info", cwe="", title="Leftover debugger statement",
      desc="A `debugger` statement halts execution when devtools are open and must not ship.",
      rationale="A shipped debugger statement pauses execution for any user with devtools open.",
      remediation="Remove the debugger statement.",
      source="https://eslint.org/docs/latest/rules/no-debugger",
      re=r"\bdebugger\b\s*;?", nc="debugger;", c="const debuggerEnabled = false;", skip=CC),
    r(id="js-no-alert", type="smell", qual="maint", sev="info", cwe="", title="Use of alert/confirm/prompt",
      desc="Browser dialog functions block the UI thread and are inappropriate in production.",
      rationale="alert/confirm/prompt block the event loop and are almost always leftover debugging code in production.",
      remediation="Use a non-blocking UI component instead of a browser dialog.",
      source="https://eslint.org/docs/latest/rules/no-alert",
      re=r"\b(alert|confirm|prompt)\s*\(", nc='alert("done");', c='showToast("done");', skip=CC),
    r(id="js-eqeqeq", type="bug", qual="rel", sev="medium", cwe="", title="Use === instead of ==",
      desc="`==`/`!=` apply type coercion with surprising results; use `===`/`!==`.",
      rationale="Loose equality coerces operands (0 == '', null == undefined), a frequent source of bugs. Strict equality avoids coercion.",
      remediation="Replace == with === and != with !== (adjust logic if coercion was relied on).",
      source="https://eslint.org/docs/latest/rules/eqeqeq",
      re=r"([^=!<>]==[^=]|[^=!]!=[^=])", nc="if (a == b) return 1;", c="if (a === b) return 1;", skip=CC),
    r(id="js-eq-null", type="smell", qual="maint", sev="info", cwe="", title="Ambiguous == null comparison",
      desc="`== null` matches both null and undefined; make the intent explicit.",
      rationale="== null intentionally matches null and undefined; being explicit (=== null or a nullish check) documents intent and avoids accidental coercion.",
      remediation="Use === null / === undefined, or a documented nullish check.",
      source="https://eslint.org/docs/latest/rules/no-eq-null",
      re=r"[^=!]==\s*null\b", nc="if (val == null) return;", c="if (val === null) return;", skip=CC),
    r(id="js-empty-catch", type="bug", qual="rel", sev="medium", cwe="CWE-390", title="Empty catch block",
      desc="An empty catch swallows the error silently, hiding failures.",
      rationale="Silently swallowing an exception hides failures and complicates debugging (CWE-390: detection of error condition without action).",
      remediation="Handle or log the error, or rethrow it.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r"catch\s*\([^)]*\)\s*\{\s*\}", nc="try { run(); } catch (e) {}", c="try { run(); } catch (e) { log(e); }", skip=CC),
    r(id="js-no-cond-assign", type="bug", qual="rel", sev="medium", cwe="", title="Assignment in a conditional",
      desc="An assignment (`=`) inside an if/while condition is usually a mistaken `===`.",
      rationale="An assignment inside a condition is almost always a typo for a comparison and silently changes state.",
      remediation="Use a comparison operator, or move the assignment out of the condition.",
      source="https://eslint.org/docs/latest/rules/no-cond-assign",
      re=r"\b(if|while)\s*\(\s*[A-Za-z_$][\w$.]*\s*=\s*[^=]", nc="if (node = node.next) {", c="if (node === node.next) {", skip=CC),
    r(id="js-prototype-builtins", type="bug", qual="rel", sev="low", cwe="", title="Object.prototype builtin called directly",
      desc="Calling hasOwnProperty directly breaks on null-prototype objects; use Object.prototype.hasOwnProperty.call.",
      rationale="Objects created with Object.create(null) or that shadow hasOwnProperty break a direct call; call it via Object.prototype.",
      remediation="Use Object.prototype.hasOwnProperty.call(obj, key) (or Object.hasOwn).",
      source="https://eslint.org/docs/latest/rules/no-prototype-builtins",
      re=r"\.hasOwnProperty\s*\(", nc='if (obj.hasOwnProperty("k")) {}', c='if (Object.hasOwn(obj, "k")) {}', skip=CC),
    r(id="js-no-with", type="bug", qual="rel", sev="medium", cwe="", title="Use of the with statement",
      desc="`with` makes scope resolution ambiguous and is disallowed in strict mode.",
      rationale="with adds an object to the scope chain, making variable references ambiguous and defeating optimization; it is banned in strict mode.",
      remediation="Reference properties explicitly instead of using with.",
      source="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with",
      re=r"\bwith\s*\(", nc="with (config) { host = h; }", c="const { host } = config;", skip=CC),
    r(id="js-no-new-wrappers", type="bug", qual="rel", sev="low", cwe="", title="Primitive wrapper constructor",
      desc="`new String/Number/Boolean` creates an object wrapper, not a primitive.",
      rationale="new String('x') yields an object, so typeof is 'object' and == comparisons behave unexpectedly.",
      remediation="Call the function without new (String(x)) or use a literal.",
      source="https://eslint.org/docs/latest/rules/no-new-wrappers",
      re=r"\bnew\s+(String|Number|Boolean)\s*\(", nc='const s = new String("x");', c='const s = String("x");', skip=CC),
    r(id="js-no-array-constructor", type="smell", qual="maint", sev="low", cwe="", title="Array constructor",
      desc="`new Array(n)` is error-prone (single numeric arg = length); prefer a literal.",
      rationale="The Array constructor treats a single numeric argument as a length, a common source of confusion; array literals are clearer.",
      remediation="Use an array literal [] instead of the Array constructor.",
      source="https://eslint.org/docs/latest/rules/no-array-constructor",
      re=r"\bnew\s+Array\s*\(", nc="const a = new Array(1, 2, 3);", c="const a = [1, 2, 3];", skip=CC),
    r(id="js-parseint-radix", type="bug", qual="rel", sev="low", cwe="", title="parseInt without a radix",
      desc="`parseInt` without a radix can misparse strings with leading zeros/0x.",
      rationale="Without an explicit radix, parseInt's behavior depends on the input prefix, historically parsing leading-zero strings as octal.",
      remediation="Pass the radix explicitly, e.g. parseInt(s, 10).",
      source="https://eslint.org/docs/latest/rules/radix",
      re=r"\bparseInt\s*\(\s*[^,)]+\)", nc="const n = parseInt(input);", c="const n = parseInt(input, 10);", skip=CC),
    r(id="js-no-caller", type="smell", qual="maint", sev="low", cwe="", title="Use of arguments.caller/callee",
      desc="`.caller`/`.callee` are deprecated and disallowed in strict mode.",
      rationale="Function.caller/arguments.callee are deprecated, defeat optimization, and throw in strict mode.",
      remediation="Refer to the function by a named reference instead.",
      source="https://eslint.org/docs/latest/rules/no-caller",
      re=r"\.(caller|callee)\b", nc="const f = arguments.callee;", c="const f = namedFn;", skip=CC),
    # ── TypeScript-specific (line-detectable) ────────────────────────────────
    r(id="ts-explicit-any", type="smell", qual="maint", sev="low", cwe="", title="Explicit any type",
      desc="An explicit `any` type disables type checking for that value.",
      rationale="any opts a value out of type checking, so downstream errors go undetected. Prefer a precise type or unknown.",
      remediation="Replace any with a specific type, a generic, or unknown.",
      source="https://typescript-eslint.io/rules/no-explicit-any/",
      re=r":\s*any\b", nc="function f(x: any) { return x; }", c="function f(x: unknown) { return x; }", skip=CC, tags=["sast","typescript"]),
    r(id="ts-non-null-assertion", type="smell", qual="maint", sev="low", cwe="", title="Non-null assertion",
      desc="The `!` non-null assertion overrides the compiler and can hide a real null.",
      rationale="The non-null assertion tells the compiler a value is not null without proof; if it is, a runtime error follows.",
      remediation="Narrow the type with a check, or use optional chaining.",
      source="https://typescript-eslint.io/rules/no-non-null-assertion/",
      re=r"[\w\])]![.\[]", nc="const v = user!.name;", c="const v = user?.name;", skip=CC, tags=["sast","typescript"]),
    r(id="ts-ts-ignore", type="smell", qual="maint", sev="low", cwe="", title="@ts-ignore directive",
      desc="`@ts-ignore` suppresses a compiler error unconditionally; prefer @ts-expect-error.",
      rationale="@ts-ignore hides the next line's type error even after the underlying issue is fixed; @ts-expect-error fails when the error disappears.",
      remediation="Replace @ts-ignore with @ts-expect-error, or fix the underlying type error.",
      source="https://typescript-eslint.io/rules/ban-ts-comment/",
      re=r"@ts-ignore\b", nc="// @ts-ignore", c="// @ts-expect-error", tags=["sast","typescript"]),
    # ── security (JS-specific, not covered by the language-agnostic core) ─────
    r(id="js-settimeout-string", type="vuln", qual="sec", sev="medium", cwe="CWE-95", owasp="A03:2021", title="setTimeout/setInterval with a string body",
      desc="A string first argument to setTimeout/setInterval is evaluated like eval().",
      rationale="Passing a string to setTimeout/setInterval invokes the eval mechanism on it, enabling code injection if the string is influenced by input.",
      remediation="Pass a function reference or arrow function instead of a string.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"\b(setTimeout|setInterval)\s*\(\s*['\"]", nc='setTimeout("doWork()", 100);', c="setTimeout(() => doWork(), 100);", skip=CC),
    r(id="js-postmessage-wildcard", type="hotspot", qual="sec", sev="medium", cwe="CWE-345", owasp="A08:2021", title="postMessage with wildcard target origin",
      desc="`postMessage(data, '*')` sends the message to any origin.",
      rationale="A wildcard targetOrigin lets any window receive the message, potentially leaking data to a malicious frame.",
      remediation="Specify the exact target origin instead of '*'.",
      source="https://cwe.mitre.org/data/definitions/345.html",
      re=r"postMessage\s*\([^,]+,\s*['\"]\*['\"]", nc='win.postMessage(payload, "*");', c='win.postMessage(payload, "https://app.example.com");', skip=CC),
    r(id="js-localstorage-sensitive", type="hotspot", qual="sec", sev="low", cwe="CWE-522", owasp="A04:2021", title="Sensitive value in localStorage",
      desc="localStorage persists data readable by any script on the origin (XSS-exfiltratable).",
      rationale="Tokens/secrets in localStorage are readable by any JavaScript on the page, so an XSS can exfiltrate them; they also persist indefinitely.",
      remediation="Keep sensitive tokens in memory or an HttpOnly cookie, not localStorage.",
      source="https://cwe.mitre.org/data/definitions/522.html",
      re=r"localStorage\.setItem\s*\(\s*['\"](token|password|secret|jwt|api[_-]?key|access[_-]?token)", nc='localStorage.setItem("token", jwt);', c='sessionStorage.setItem("theme", mode);', skip=CC),
    r(id="js-insecure-websocket", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021", title="Insecure WebSocket (ws://)",
      desc="A ws:// WebSocket is unencrypted and open to interception.",
      rationale="ws:// transmits in cleartext; a network attacker can read or tamper with the traffic. Use wss://.",
      remediation="Use a wss:// (TLS) WebSocket endpoint.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r"new\s+WebSocket\s*\(\s*['\"]ws://", nc='const s = new WebSocket("ws://api.internal");', c='const s = new WebSocket("wss://api.internal");', skip=CC),
]
