# Ruby/Rails language-pack rule specs (#206).
# Clean-room, precision-biased line rules. The Ruby tree-sitter grammar is already registered;
# cognitive complexity is implemented in astwalk rather than approximated with regular expressions.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "rb")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "ruby", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # bugs (8)
    r("bugs",
      id="rb:rescue-nil", type="bug", qual="rel", sev="medium", cwe="CWE-390",
      title="Exception is converted to nil or false",
      desc="A rescue modifier converts an exception into nil or false without preserving the failure.",
      rationale="Silently replacing an exception with a falsey value makes a failed operation indistinguishable from a legitimate empty result.",
      remediation="Rescue the expected exception explicitly and return a typed error, log context, or propagate the failure.",
      source="https://ruby-doc.org/core/keywords_rdoc.html",
      re=r"\brescue(?:\s+[A-Z][A-Za-z0-9_:]*)?\s+(?:nil|false)\b",
      nc="payload = JSON.parse(raw_payload) rescue nil",
      c="payload = JSON.parse(raw_payload)"),
    r("bugs",
      id="rb:rescue-exception", type="bug", qual="rel", sev="high", cwe="CWE-396",
      title="Rescue catches Exception or a broader root type",
      desc="A rescue clause catches Exception, Object, or BasicObject and can absorb fatal runtime failures.",
      rationale="Catching Ruby's broad root exception types can intercept system-exit, signal, and virtual-machine failures that application code should not recover from.",
      remediation="Rescue StandardError subclasses that the operation can handle and let fatal exceptions propagate.",
      source="https://ruby-doc.org/3.3.0/Exception.html",
      re=r"\brescue\s+(?:Exception|Object|BasicObject)\b",
      nc="begin work rescue Exception => error; fallback(error) end",
      c="begin work rescue IOError => error; fallback(error) end",
      effort=30),
    r("bugs",
      id="rb:bang-result-assignment", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Conditional bang-method result assigned directly",
      desc="The result of a conditional mutating bang method is assigned even though the method returns nil when no change occurs.",
      rationale="Methods such as strip!, chomp!, gsub!, uniq!, and compact! return nil when the receiver is unchanged, so assigning their result can unexpectedly erase a valid value.",
      remediation="Call the mutating method separately, or use the non-bang method when a value must always be returned.",
      source="https://ruby-doc.org/3.3.0/String.html",
      re=r"^\s*[A-Za-z_]\w*\s*=\s*[A-Za-z_][\w.]*\.(?:strip!|chomp!|gsub!|sub!|uniq!|compact!|flatten!|reject!|select!)(?:\s|$|[;,)])",
      nc="clean_name = name.strip!",
      c="clean_name = name.strip"),
    r("bugs",
      id="rb:nan-comparison", type="bug", qual="rel", sev="medium", cwe="CWE-480",
      title="NaN compared with equality",
      desc="Code compares a value to Float::NAN with an equality operator.",
      rationale="NaN is not equal to itself, so equality and inequality checks do not reliably test whether a floating-point value is NaN.",
      remediation="Use value.nan? after establishing that the value is a Float.",
      source="https://ruby-doc.org/3.3.0/Float.html",
      re=r"(?:==|!=|===)\s*Float::NAN\b|\bFloat::NAN\s*(?:==|!=|===)",
      nc="invalid = value == Float::NAN",
      c="invalid = value.nan?"),
    r("bugs",
      id="rb:hash-shared-mutable-default", type="bug", qual="rel", sev="medium", cwe="CWE-1188",
      title="Hash uses one shared mutable default object",
      desc="Hash.new is initialized with a mutable object that is shared by every missing key.",
      rationale="Mutating the default array, hash, or set for one missing key mutates the same object observed through every other missing key.",
      remediation="Use Hash.new { |hash, key| hash[key] = [] } or another block that creates a fresh value per key.",
      source="https://ruby-doc.org/3.3.0/Hash.html",
      re=r"\bHash\.new\s*\(\s*(?:\[\s*\]|\{\s*\}|Set\.new)\s*\)",
      nc="groups = Hash.new([])",
      c="groups = Hash.new { |hash, key| hash[key] = [] }"),
    r("bugs",
      id="rb:params-to-i", type="bug", qual="rel", sev="medium", cwe="CWE-20",
      title="Request parameter converted with to_i without validation",
      desc="A request parameter is converted with to_i, which returns zero for malformed text instead of reporting an error.",
      rationale="Silently converting invalid input to zero can bypass validation and select an unintended record, limit, or authorization branch.",
      remediation="Parse with Integer(value, exception: false) or Integer(value) and handle invalid input explicitly.",
      source="https://ruby-doc.org/3.3.0/String.html",
      re=r"(?:params|request\.parameters)\s*\[[^\]]+\]\s*\.to_i\b",
      nc="limit = params[:limit].to_i",
      c="limit = Integer(params[:limit], exception: false)"),
    r("bugs",
      id="rb:params-to-f", type="bug", qual="rel", sev="medium", cwe="CWE-20",
      title="Request parameter converted with to_f without validation",
      desc="A request parameter is converted with to_f, which returns 0.0 for malformed text instead of reporting an error.",
      rationale="Silent numeric coercion can transform invalid external data into a valid-looking value and bypass normal validation handling.",
      remediation="Parse with Float(value, exception: false) or Float(value) and reject malformed input explicitly.",
      source="https://ruby-doc.org/3.3.0/String.html",
      re=r"(?:params|request\.parameters)\s*\[[^\]]+\]\s*\.to_f\b",
      nc="ratio = params[:ratio].to_f",
      c="ratio = Float(params[:ratio], exception: false)"),
    r("bugs",
      id="rb:time-now-zone-sensitive", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Time.now used for a Rails zone-sensitive calculation",
      desc="Time.now is immediately used for a Rails date or time-zone calculation.",
      rationale="Time.now uses the system clock zone rather than the configured Rails Time.zone and can produce the wrong date or boundary around zone transitions.",
      remediation="Use Time.current or Time.zone.now for Rails application time.",
      source="https://api.rubyonrails.org/classes/ActiveSupport/TimeWithZone.html",
      re=r"\bTime\.now\.(?:to_date|beginning_of_day|end_of_day|in_time_zone)\b",
      nc="report_date = Time.now.to_date",
      c="report_date = Time.current.to_date"),

    # injection and trust-boundary rules (10)
    r("inj",
      id="rb:sql-interpolation", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL query contains Ruby string interpolation",
      desc="A Rails or database SQL sink receives an interpolated SQL string.",
      rationale="Interpolation changes SQL structure before the database parses it and can allow external values to become executable query syntax.",
      remediation="Use bind parameters, hash conditions, or a prepared statement and bind every external value.",
      source="https://guides.rubyonrails.org/security.html#sql-injection",
      re=r"(?i)\b(?:where|find_by_sql|execute|exec_query|select_all)\s*\(\s*\"[^\"\n]*#\{[^}]+\}",
      nc='User.where("email = \'#{params[:email]}\'")',
      c='User.where(email: params[:email])',
      effort=30),
    r("inj",
      id="rb:sql-concatenation", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL query concatenates request data",
      desc="A Rails or database SQL sink concatenates request-derived data into SQL text.",
      rationale="Concatenation lets untrusted data alter SQL syntax and can bypass intended query constraints.",
      remediation="Use bind parameters, hash conditions, or a prepared statement instead of concatenating request values.",
      source="https://guides.rubyonrails.org/security.html#sql-injection",
      re=r"(?i)\b(?:where|find_by_sql|execute|exec_query|select_all)\s*\(\s*\"[^\"\n]*\b(?:select|insert|update|delete|where|from)\b[^\"\n]*\"\s*\+\s*(?:params|request\.parameters|cookies|session)\b",
      nc='User.find_by_sql("SELECT * FROM users WHERE email = \'" + params[:email])',
      c='User.find_by_sql(["SELECT * FROM users WHERE email = ?", params[:email]])',
      effort=30),
    r("inj",
      id="rb:command-injection", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="OS command interpolates request data",
      desc="A command API, backtick command, or percent-x command interpolates request, cookie, session, or environment data.",
      rationale="Shell command interpolation can turn external input into executable options, separators, or additional commands.",
      remediation="Use an argv-style API with fixed executable and separate validated arguments; never invoke a shell for request data.",
      source="https://ruby-doc.org/3.3.0/Kernel.html#method-i-system",
      re=r"(?:\b(?:system|exec|spawn|IO\.popen|Open3\.(?:capture2|capture2e|capture3|popen2|popen3))\s*(?:\(\s*)?\"[^\"\n]*#\{\s*(?:params|request|cookies|session|ENV)\b|`[^`\n]*#\{\s*(?:params|request|cookies|session|ENV)\b|%x[^A-Za-z0-9_\s][^\n]*#\{\s*(?:params|request|cookies|session|ENV)\b)",
      nc='system("convert #{params[:file]}")',
      c='system("convert", validated_file)',
      effort=30),
    r("inj",
      id="rb:command-tainted-argument", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="OS command receives request data directly",
      desc="A command-execution API receives request-controlled data as the command argument.",
      rationale="Passing request data as the command string allows attackers to choose an executable or inject shell syntax when a shell form is selected.",
      remediation="Use a fixed executable and a validated argv array, or map external choices to a closed allowlist.",
      source="https://ruby-doc.org/3.3.0/Kernel.html#method-i-system",
      re=r"\b(?:system|exec|spawn|IO\.popen)\s*\(\s*(?:params|request\.parameters|cookies|session)\s*\[",
      nc="system(params[:command])",
      c='system("convert", validated_file)',
      effort=30),
    r("inj",
      id="rb:unsafe-yaml-load", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="Unsafe YAML deserialization of request data",
      desc="YAML.load, Psych.load, or unsafe_load receives request-controlled data.",
      rationale="General YAML deserialization can instantiate arbitrary Ruby objects and invoke dangerous gadget behavior.",
      remediation="Use YAML.safe_load with an explicit permitted-class list and aliases disabled unless they are required.",
      source="https://ruby-doc.org/stdlib/libdoc/psych/rdoc/Psych.html",
      re=r"\b(?:YAML|Psych)\.(?:load|unsafe_load)\s*\(\s*(?:params|request\.parameters|cookies|session)\b",
      nc="object = YAML.load(params[:payload])",
      c="object = YAML.safe_load(params[:payload], permitted_classes: [], aliases: false)",
      effort=30),
    r("inj",
      id="rb:unsafe-marshal-load", type="vuln", qual="sec", sev="critical", cwe="CWE-502", owasp="A08:2021",
      title="Marshal deserializes request-controlled data",
      desc="Marshal.load receives request, cookie, or session data.",
      rationale="Ruby Marshal can recreate arbitrary object graphs and is unsafe for data an attacker can modify.",
      remediation="Use a data-only format with schema validation, such as JSON, and authenticate any serialized state.",
      source="https://ruby-doc.org/3.3.0/Marshal.html",
      re=r"\bMarshal\.load\s*\(\s*(?:params|request\.parameters|cookies|session)\b",
      nc="state = Marshal.load(cookies[:state])",
      c="state = JSON.parse(cookies.encrypted[:state])",
      effort=60),
    r("inj",
      id="rb:xss-html-safe", type="vuln", qual="sec", sev="high", cwe="CWE-79", owasp="A03:2021",
      title="Request data marked html_safe",
      desc="Request-controlled data is marked html_safe and bypasses Rails output escaping.",
      rationale="html_safe tells Rails that the string is trusted HTML, allowing attacker-controlled markup or script to reach the response.",
      remediation="Keep automatic escaping enabled and sanitize only with an allowlist appropriate for the output context.",
      source="https://guides.rubyonrails.org/security.html#cross-site-scripting-xss",
      re=r"(?:params|request\.parameters|cookies|session)\s*\[[^\]]+\]\s*\.html_safe\b",
      nc="@content = params[:content].html_safe",
      c="@content = sanitize(params[:content], tags: %w[p strong em])",
      effort=30),
    r("inj",
      id="rb:xss-raw", type="vuln", qual="sec", sev="high", cwe="CWE-79", owasp="A03:2021",
      title="raw helper renders request data",
      desc="The Rails raw helper receives request, cookie, or session data directly.",
      rationale="raw disables HTML escaping and can render attacker-controlled elements, attributes, or script into the page.",
      remediation="Render the value normally or sanitize it with a narrow HTML allowlist before output.",
      source="https://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html",
      re=r"\braw\s*\(\s*(?:params|request\.parameters|cookies|session)\s*\[",
      nc="raw(params[:content])",
      c="sanitize(params[:content], tags: %w[p strong em])",
      effort=30),
    r("inj",
      id="rb:open-redirect", type="vuln", qual="sec", sev="medium", cwe="CWE-601", owasp="A01:2021",
      title="Redirect target comes directly from request data",
      desc="redirect_to receives a request parameter without a host or path allowlist.",
      rationale="An attacker-controlled redirect target can send users to a phishing site while appearing to follow a trusted application link.",
      remediation="Redirect to a fixed internal route or validate the target against an explicit allowlist and disallow other hosts.",
      source="https://guides.rubyonrails.org/security.html#redirection",
      re=r"\bredirect_to\s*(?:\(\s*)?(?:params|request\.parameters)\s*\[",
      nc="redirect_to params[:next]",
      c="redirect_to dashboard_path",
      effort=30),
    r("inj",
      id="rb:mass-assignment", type="vuln", qual="sec", sev="high", cwe="CWE-915", owasp="A01:2021",
      title="Active Record mass assignment uses raw params",
      desc="An Active Record create, update, or constructor call receives raw params instead of an explicit permitted set.",
      rationale="Raw parameter mass assignment can modify protected attributes such as roles, ownership, or approval state.",
      remediation="Use a dedicated strong-parameters method that permits only the fields allowed for this operation.",
      source="https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters",
      re=r"\b[A-Z][A-Za-z0-9_:]*\.(?:new|create|create!|update|update!)\s*\(\s*params\s*(?:\[|\))",
      nc="user = User.create(params[:user])",
      c="user = User.create(user_params)",
      effort=30),

    # cryptography (4)
    r("crypto",
      id="rb:weak-hash", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Weak digest API used",
      desc="Ruby code references the MD5 or SHA-1 digest implementation.",
      rationale="MD5 and SHA-1 have practical collision attacks and are unsuitable for signatures, integrity decisions, certificates, or password storage.",
      remediation="Use SHA-256 or stronger for integrity and a password-specific KDF such as bcrypt, scrypt, or Argon2 for passwords.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"\b(?:Digest::(?:MD5|SHA1)|OpenSSL::Digest::(?:MD5|SHA1))\b",
      nc="checksum = Digest::MD5.hexdigest(payload)",
      c="checksum = Digest::SHA256.hexdigest(payload)"),
    r("crypto",
      id="rb:insecure-cipher-mode", type="hotspot", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="ECB cipher mode selected",
      desc="OpenSSL::Cipher is configured with electronic codebook mode.",
      rationale="ECB encrypts equal plaintext blocks to equal ciphertext blocks and reveals structural patterns in protected data.",
      remediation="Use an authenticated mode such as AES-256-GCM with a unique nonce for every encryption operation.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"(?i)\bOpenSSL::Cipher(?:\.new)?\s*\(\s*[\"'][^\"'\n]*-ecb[\"']",
      nc='cipher = OpenSSL::Cipher.new("aes-256-ecb")',
      c='cipher = OpenSSL::Cipher.new("aes-256-gcm")',
      effort=60),
    r("crypto",
      id="rb:insecure-random-token", type="vuln", qual="sec", sev="high", cwe="CWE-338", owasp="A02:2021",
      title="Security token generated with non-cryptographic randomness",
      desc="A token-, secret-, password-, session-, or API-key-named value is generated with rand or Random.rand.",
      rationale="Ruby's general pseudo-random generator is predictable enough to be unsuitable for authentication tokens and secrets.",
      remediation="Use SecureRandom.hex, urlsafe_base64, random_bytes, or uuid with sufficient entropy.",
      source="https://ruby-doc.org/stdlib/libdoc/securerandom/rdoc/SecureRandom.html",
      re=r"(?i)\b[A-Za-z_]\w*(?:token|secret|password|session_id|api_key)\w*\s*=\s*(?:rand|Random\.rand)\s*(?:\(|\b)",
      nc="reset_token = rand(1_000_000).to_s",
      c="reset_token = SecureRandom.urlsafe_base64(32)",
      effort=15),
    r("crypto",
      id="rb:weak-cipher", type="hotspot", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="Weak OpenSSL cipher selected",
      desc="OpenSSL::Cipher is configured with DES, 3DES, RC2, RC4, or Blowfish.",
      rationale="These legacy ciphers have inadequate security margins or known attacks and should not protect new data.",
      remediation="Use an authenticated modern construction such as AES-256-GCM or ChaCha20-Poly1305 with unique nonces.",
      source="https://www.openssl.org/docs/manmaster/man1/openssl-ciphers.html",
      re=r"(?i)\bOpenSSL::Cipher(?:\.new)?\s*\(\s*[\"'](?:des|des-ede3|rc2|rc4|bf|blowfish)[\"']",
      nc='cipher = OpenSSL::Cipher.new("des-ede3")',
      c='cipher = OpenSSL::Cipher.new("aes-256-gcm")',
      effort=60),

    # authorization (4)
    r("authz",
      id="rb:skip-csrf", type="hotspot", qual="sec", sev="medium", cwe="CWE-352", owasp="A01:2021",
      title="Rails CSRF verification is skipped",
      desc="A controller skips the verify_authenticity_token callback.",
      rationale="Disabling CSRF verification allows another site to submit authenticated state-changing requests through a victim's browser.",
      remediation="Keep CSRF protection enabled or isolate a stateless API endpoint that uses an authentication mechanism not sent automatically by browsers.",
      source="https://guides.rubyonrails.org/security.html#cross-site-request-forgery-csrf",
      re=r"\bskip_(?:before_)?action\s+(?::verify_authenticity_token|[\"']verify_authenticity_token[\"'])",
      nc="skip_before_action :verify_authenticity_token",
      c="protect_from_forgery with: :exception",
      effort=30),
    r("authz",
      id="rb:skip-authentication", type="hotspot", qual="sec", sev="high", cwe="CWE-306", owasp="A07:2021",
      title="Authentication callback is skipped",
      desc="A controller skips a common authentication callback.",
      rationale="Skipping authentication can expose actions that were expected to require a logged-in principal.",
      remediation="Remove the skip or restrict it to a narrowly reviewed public action with explicit authorization tests.",
      source="https://guides.rubyonrails.org/action_controller_overview.html#filters",
      re=r"\bskip_(?:before_)?action\s+(?::(?:authenticate_user!|require_login|require_authentication)|[\"'](?:authenticate_user!|require_login|require_authentication)[\"'])",
      nc="skip_before_action :authenticate_user!",
      c="before_action :authenticate_user!",
      effort=30),
    r("authz",
      id="rb:permit-all-params", type="vuln", qual="sec", sev="high", cwe="CWE-915", owasp="A01:2021",
      title="Strong parameters permit every attribute",
      desc="params.permit! marks the complete request parameter tree as permitted.",
      rationale="Permitting every attribute defeats strong-parameter allowlisting and can expose ownership, role, or administrative fields to mass assignment.",
      remediation="Permit an explicit field list for each operation and nested object.",
      source="https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters",
      re=r"\bparams\.permit!(?:\s|$|[;,)])",
      nc="attributes = params.permit!",
      c="attributes = params.require(:user).permit(:name, :email)",
      effort=30),
    r("authz",
      id="rb:pundit-skip-authorization", type="hotspot", qual="sec", sev="medium", cwe="CWE-862", owasp="A01:2021",
      title="Pundit authorization verification is skipped",
      desc="Code explicitly skips Pundit authorization or policy-scope verification.",
      rationale="Skipping the verification hook removes a defense that detects controller actions which forgot to authorize a record or scope a collection.",
      remediation="Authorize the record or apply policy_scope; use a skip only for a documented public action with tests.",
      source="https://github.com/varvet/pundit#ensuring-policies-and-scopes-are-used",
      re=r"\bskip_(?:authorization|policy_scope)\b",
      nc="skip_authorization",
      c="authorize @account",
      effort=30),

    # security hotspots (6)
    r("hotspot",
      id="rb:eval-request-data", type="vuln", qual="sec", sev="critical", cwe="CWE-95", owasp="A03:2021",
      title="Ruby evaluation API receives request data",
      desc="eval, instance_eval, class_eval, or module_eval receives request-controlled data.",
      rationale="Dynamic Ruby evaluation gives attacker-controlled text the privileges of application code.",
      remediation="Replace evaluation with a closed command map, parser, or explicit dispatch table.",
      source="https://ruby-doc.org/3.3.0/Kernel.html#method-i-eval",
      re=r"\b(?:eval|instance_eval|class_eval|module_eval)\s*\(\s*(?:params|request\.parameters|cookies|session|ENV)\b",
      nc="result = eval(params[:expression])",
      c="result = OPERATIONS.fetch(params[:operation]).call(input)",
      effort=60),
    r("hotspot",
      id="rb:dynamic-constantize", type="hotspot", qual="sec", sev="high", cwe="CWE-470", owasp="A03:2021",
      title="Request data controls constant lookup",
      desc="A request parameter is converted to a Ruby constant with constantize or safe_constantize.",
      rationale="Dynamic constant lookup can expose unintended classes and combine with reflective construction or dispatch to reach dangerous behavior.",
      remediation="Map external names to an explicit allowlist of permitted classes.",
      source="https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html",
      re=r"(?:params|request\.parameters)\s*\[[^\]]+\]\s*\.(?:constantize|safe_constantize)\b",
      nc="klass = params[:type].constantize",
      c="klass = ALLOWED_TYPES.fetch(params[:type])",
      effort=30),
    r("hotspot",
      id="rb:dynamic-send", type="hotspot", qual="sec", sev="high", cwe="CWE-470", owasp="A03:2021",
      title="Request data controls reflective method dispatch",
      desc="send, public_send, or __send__ receives a request parameter as the method name.",
      rationale="Reflective dispatch can invoke methods that were not intended to be reachable from external input.",
      remediation="Map external operation names to a closed set of callable methods or command objects.",
      source="https://ruby-doc.org/3.3.0/Object.html#method-i-public_send",
      re=r"\.(?:send|public_send|__send__)\s*\(\s*(?:params|request\.parameters)\s*\[",
      nc="account.public_send(params[:operation])",
      c="ACTIONS.fetch(params[:operation]).call(account)",
      effort=30),
    r("hotspot",
      id="rb:ssl-verify-none", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A02:2021",
      title="TLS peer verification is disabled",
      desc="OpenSSL verification is set to VERIFY_NONE or numeric zero.",
      rationale="Disabling certificate verification permits machine-in-the-middle interception and endpoint impersonation.",
      remediation="Use VERIFY_PEER with a trusted CA store and hostname verification.",
      source="https://ruby-doc.org/stdlib/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html",
      re=r"\bOpenSSL::SSL::VERIFY_NONE\b|\bverify_mode\s*=\s*0\b",
      nc="http.verify_mode = OpenSSL::SSL::VERIFY_NONE",
      c="http.verify_mode = OpenSSL::SSL::VERIFY_PEER",
      effort=30),
    r("hotspot",
      id="rb:open-uri-request-url", type="hotspot", qual="sec", sev="high", cwe="CWE-918", owasp="A10:2021",
      title="OpenURI fetches a request-controlled URL",
      desc="URI.open or OpenURI.open_uri receives a request parameter directly.",
      rationale="A request-controlled URL can reach internal services, cloud metadata endpoints, or attacker-selected hosts.",
      remediation="Resolve a closed set of approved destinations or validate scheme, host, port, redirects, and resolved IP ranges before fetching.",
      source="https://ruby-doc.org/stdlib/libdoc/open-uri/rdoc/OpenURI.html",
      re=r"\b(?:URI\.open|OpenURI\.open_uri)\s*\(\s*(?:params|request\.parameters)\s*\[",
      nc="body = URI.open(params[:url]).read",
      c="body = HTTP.get(APPROVED_ENDPOINTS.fetch(params[:source]))",
      effort=60),
    r("hotspot",
      id="rb:dynamic-regexp", type="hotspot", qual="sec", sev="medium", cwe="CWE-1333", owasp="A03:2021",
      title="Regular expression is built from request data",
      desc="Regexp.new or Regexp.compile receives a request parameter without escaping.",
      rationale="Attacker-controlled regular expressions can trigger excessive backtracking or change matching semantics.",
      remediation="Use Regexp.escape for literal matching, constrain pattern syntax, and bound input length and execution time.",
      source="https://ruby-doc.org/3.3.0/Regexp.html",
      re=r"\bRegexp\.(?:new|compile)\s*\(\s*(?:params|request\.parameters)\s*\[",
      nc="pattern = Regexp.new(params[:pattern])",
      c="pattern = Regexp.new(Regexp.escape(params[:pattern]))",
      effort=30),

    # deprecated / risky APIs (4)
    r("api",
      id="rb:file-exists-deprecated", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated File.exists? API",
      desc="Code calls File.exists?, which is deprecated in favor of File.exist?.",
      rationale="Using the maintained API avoids deprecation warnings and keeps code compatible with current Ruby versions.",
      remediation="Replace File.exists? with File.exist?.",
      source="https://ruby-doc.org/3.3.0/File.html",
      re=r"\bFile\.exists\?\s*\(",
      nc='File.exists?("config.yml")',
      c='File.exist?("config.yml")',
      effort=5),
    r("api",
      id="rb:uri-escape-deprecated", type="smell", qual="maint", sev="medium", cwe="CWE-116",
      title="Deprecated URI escaping API",
      desc="Code calls URI.escape, URI.encode, or URI.unescape, which do not provide component-aware URI encoding.",
      rationale="Generic URI escaping can encode the wrong grammar component and these methods were removed from modern Ruby.",
      remediation="Use URI.encode_www_form_component, URI.decode_www_form_component, or a URI builder appropriate for the component.",
      source="https://ruby-doc.org/stdlib/libdoc/uri/rdoc/URI.html",
      re=r"\bURI\.(?:escape|encode|unescape)\s*\(",
      nc="target = URI.escape(value)",
      c="target = URI.encode_www_form_component(value)",
      effort=15),
    r("api",
      id="rb:update-attributes-deprecated", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated Active Record update_attributes API",
      desc="Code calls update_attributes or update_attributes!, which were replaced by update and update!.",
      rationale="Using removed compatibility aliases complicates framework upgrades and can fail after a Rails version change.",
      remediation="Replace update_attributes with update, or update_attributes! with update!.",
      source="https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html",
      re=r"\.(?:update_attributes|update_attributes!)\s*\(",
      nc="account.update_attributes(name: value)",
      c="account.update(name: value)",
      effort=5),
    r("api",
      id="rb:filter-callback-deprecated", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated Rails filter callback name",
      desc="A controller uses before_filter, after_filter, or around_filter instead of the current action callback API.",
      rationale="The filter aliases are deprecated and make framework upgrades harder.",
      remediation="Use before_action, after_action, or around_action.",
      source="https://guides.rubyonrails.org/action_controller_overview.html#filters",
      re=r"\b(?:before_filter|after_filter|around_filter)\b",
      nc="before_filter :authenticate_user!",
      c="before_action :authenticate_user!",
      effort=5),

    # maintainability (3 pattern + 1 AST)
    r("maint",
      id="rb:global-variable", type="smell", qual="maint", sev="low", cwe="CWE-1108",
      title="Global variable assignment",
      desc="Code assigns a Ruby global variable.",
      rationale="Global mutable state creates hidden coupling between unrelated code and makes tests order-dependent.",
      remediation="Pass dependencies explicitly or encapsulate state behind a narrowly scoped object.",
      source="https://ruby-doc.org/core/syntax/assignment_rdoc.html",
      re=r"^\s*\$[A-Za-z_]\w*\s*=",
      nc="$current_tenant = tenant",
      c="Current.tenant = tenant",
      effort=30),
    r("maint",
      id="rb:class-variable", type="smell", qual="maint", sev="low", cwe="CWE-1108",
      title="Class variable assignment",
      desc="Code assigns a Ruby class variable shared across an inheritance hierarchy.",
      rationale="Class variables have inheritance-wide sharing semantics that are easy to misunderstand and can create surprising cross-class state changes.",
      remediation="Use a class-instance variable with an explicit reader/writer or inject state through instances.",
      source="https://ruby-doc.org/core/syntax/assignment_rdoc.html",
      re=r"^\s*@@[A-Za-z_]\w*\s*=",
      nc="@@registry = {}",
      c="@registry = {}",
      effort=30),
    r("maint",
      id="rb:mutable-constant", type="smell", qual="maint", sev="medium", cwe="CWE-1108",
      title="Mutable object assigned to a constant",
      desc="A constant is initialized with a mutable collection and is not frozen on the same line.",
      rationale="Ruby constants prevent rebinding but do not prevent mutation, so shared configuration can change unexpectedly at runtime.",
      remediation="Freeze the object and nested values, or construct immutable configuration through a dedicated object.",
      source="https://ruby-doc.org/core/syntax/assignment_rdoc.html",
      re=r"^\s*[A-Z][A-Z0-9_]*\s*=\s*(?:\[\s*\]|\{\s*\}|Set\.new\b|Array\.new\b|Hash\.new\b)\s*$",
      nc="ALLOWED_HOSTS = []",
      c="ALLOWED_HOSTS = [].freeze",
      effort=15),
]
