-- +goose Up
-- Third-party findings ingested from SARIF 2.1.0 (#415).
--
-- An imported finding is DURABLE on purpose. The ingest writes an append-only audit entry asserting
-- that N external results entered an engagement; if the findings themselves lived only in process
-- memory, that entry would record a fact the system cannot produce, and a re-posted report would
-- duplicate on every restart because the idempotency history vanished with it.
--
-- Provenance is immutable: tool, version, rule, source digest, ingesting actor and time together let a
-- reader re-derive the finding from the exact bytes that produced it, so an UPDATE is forbidden at the
-- database level rather than merely avoided by the store.
--
-- RLS-native via the 0057 procedure (tenant_id keys the policy; the empty tenant means DENY, so rows
-- use the non-empty 'default' tenant seeded in 0058 for single-tenant deployments).
--
-- engagement_id and finding_id are logical cross-aggregate references validated at the application
-- layer, matching findings/writeup_drafts: the engagement gate is what proves tenancy on read.
CREATE TABLE imported_findings (
    id            TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL REFERENCES tenants(id),
    engagement_id TEXT NOT NULL,
    -- finding_id links to the first-party finding this result agrees with; '' when nothing matched.
    -- Both sources are kept: a match records agreement, it never replaces one with the other.
    finding_id    TEXT NOT NULL DEFAULT '',
    -- 'unknown' is a first-class severity here. An external severity with no documented mapping is
    -- stored as unknown and NEVER defaulted to medium, which would invent a risk nobody assessed.
    severity      TEXT NOT NULL CHECK (severity IN ('critical','high','medium','low','info','unknown')),
    title         TEXT NOT NULL,
    message       TEXT NOT NULL,
    path          TEXT NOT NULL DEFAULT '',
    start_line    INTEGER NOT NULL DEFAULT 0 CHECK (start_line >= 0),
    start_column  INTEGER NOT NULL DEFAULT 0 CHECK (start_column >= 0),
    logical_name  TEXT NOT NULL DEFAULT '',
    -- The source tool's suppression is RECORDED, never obeyed: it is information about the tool, not
    -- authority over this system's gate.
    suppressed    BOOLEAN NOT NULL DEFAULT false,
    fingerprint   TEXT NOT NULL DEFAULT '',
    tool_name     TEXT NOT NULL CHECK (tool_name <> ''),
    tool_version  TEXT NOT NULL CHECK (tool_version <> ''),
    rule_id       TEXT NOT NULL CHECK (rule_id <> ''),
    source_digest TEXT NOT NULL CHECK (source_digest <> ''),
    ingested_by   TEXT NOT NULL CHECK (ingested_by <> ''),
    ingested_at   TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The idempotency key: one finding per (tenant, engagement, source document, rule, location).
--
-- Note precisely what this does and does not promise. Re-posting the SAME BYTES is a no-op, so a
-- pipeline that retries an upload cannot inflate the queue. A report REGENERATED by a second scan has a
-- different digest and therefore inserts a fresh row set for the same rule and location: the digest is
-- part of the key on purpose, because two documents are two pieces of evidence with two provenances, and
-- collapsing them would silently discard the newer tool version's attestation. Cross-document
-- consolidation belongs in the read model, not in a unique index that would destroy provenance.
CREATE UNIQUE INDEX imported_findings_idem ON imported_findings
    (tenant_id, engagement_id, source_digest, rule_id, path, logical_name, start_line);

-- Backs the document-digest short circuit and the per-engagement read.
CREATE INDEX imported_findings_digest ON imported_findings (tenant_id, engagement_id, source_digest);

CALL synapse_enable_tenant_rls('imported_findings');

-- Provenance is immutable. INSERT and DELETE stay available (an engagement teardown must be able to
-- remove its rows); an in-place edit of an ingested result is not, because a finding whose tool, rule
-- or source digest could be rewritten can no longer be re-checked against its source.
CREATE TRIGGER imported_findings_immutable
    BEFORE UPDATE ON imported_findings
    FOR EACH ROW EXECUTE FUNCTION synapse_forbid_mutation();

-- +goose Down
DROP TRIGGER IF EXISTS imported_findings_immutable ON imported_findings;
DROP TABLE imported_findings;
