apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-api
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
    {{- if .Values.api.metrics.enabled }}
    - name: metrics
      port: {{ .Values.api.metrics.port }}
      targetPort: metrics
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-web
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
