package bincat

import (
	"archive/zip"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

// writeJar writes a jar (zip) at path whose entries are the given name->content map.
func writeJar(t *testing.T, path string, entries map[string]string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	zw := zip.NewWriter(f)
	for name, content := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
}

func TestParsePomProperties(t *testing.T) {
	ok := "#Generated by Maven\ngroupId=com.example\nartifactId=demo\nversion=1.2.3\n"
	g, a, v, got := parsePomProperties([]byte(ok))
	if !got || g != "com.example" || a != "demo" || v != "1.2.3" {
		t.Fatalf("parsePomProperties(valid) = %q %q %q %v", g, a, v, got)
	}
	// Missing version -> rejected (never a coordinate without a concrete version).
	if _, _, _, got := parsePomProperties([]byte("groupId=com.example\nartifactId=demo\n")); got {
		t.Error("a pom.properties with no version must be rejected")
	}
	// PURL-breaking characters in a coordinate -> rejected.
	if _, _, _, got := parsePomProperties([]byte("groupId=com.ex/ample\nartifactId=demo\nversion=1.0\n")); got {
		t.Error("a group with a slash must be rejected")
	}
}

func TestJarComponents(t *testing.T) {
	dir := t.TempDir()
	// A shaded/fat jar embeds one pom.properties per bundled dependency; a single-level scan inventories all.
	jar := filepath.Join(dir, "app.jar")
	writeJar(t, jar, map[string]string{
		"META-INF/maven/org.apache.commons/commons-text/pom.properties": "groupId=org.apache.commons\nartifactId=commons-text\nversion=1.10.0\n",
		"META-INF/maven/com.google.guava/guava/pom.properties":          "groupId=com.google.guava\nartifactId=guava\nversion=31.1-jre\n",
		"META-INF/MANIFEST.MF":  "Manifest-Version: 1.0\n",
		"org/example/App.class": "not-real-bytecode",
	})
	comps := jarComponents(jar)
	sort.Slice(comps, func(i, j int) bool { return comps[i].Name < comps[j].Name })
	want := []sbom.Component{
		{Name: "com.google.guava:guava", Version: "31.1-jre", PURL: "pkg:maven/com.google.guava/guava@31.1-jre", Scope: sbom.ScopeProduction},
		{Name: "org.apache.commons:commons-text", Version: "1.10.0", PURL: "pkg:maven/org.apache.commons/commons-text@1.10.0", Scope: sbom.ScopeProduction},
	}
	if len(comps) != len(want) {
		t.Fatalf("jarComponents returned %d components, want %d: %+v", len(comps), len(want), comps)
	}
	for i := range want {
		if comps[i].Name != want[i].Name || comps[i].Version != want[i].Version || comps[i].PURL != want[i].PURL || comps[i].Scope != want[i].Scope {
			t.Errorf("component %d = %+v, want %+v", i, comps[i], want[i])
		}
	}
	// A jar with no embedded Maven coordinate yields nothing (no guessing from a filename).
	plain := filepath.Join(dir, "plain.jar")
	writeJar(t, plain, map[string]string{"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\n"})
	if got := jarComponents(plain); len(got) != 0 {
		t.Errorf("a jar without pom.properties must yield nothing, got %+v", got)
	}
	// A non-zip file with a .jar name is not a false coordinate.
	bogus := filepath.Join(dir, "bogus.jar")
	if err := os.WriteFile(bogus, []byte("this is not a zip"), 0o644); err != nil {
		t.Fatal(err)
	}
	if got := jarComponents(bogus); got != nil {
		t.Errorf("a non-zip .jar must yield nothing, got %+v", got)
	}
}

func TestNodePackageManifest(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, content string) string {
		p := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}

	unscoped := write("app/node_modules/lodash/package.json", `{"name":"lodash","version":"4.17.21"}`)
	scoped := write("app/node_modules/@babel/core/package.json", `{"name":"@babel/core","version":"7.22.0"}`)
	nestedFixture := write("app/node_modules/lodash/test/fixtures/package.json", `{"name":"fixture","version":"9.9.9"}`)
	appRoot := write("app/package.json", `{"name":"my-app","version":"1.0.0"}`)
	noVersion := write("app/node_modules/private-thing/package.json", `{"name":"private-thing"}`)

	if !isNodePackageManifest(unscoped) || !isNodePackageManifest(scoped) {
		t.Error("an installed package manifest must be recognized (scoped and unscoped)")
	}
	if isNodePackageManifest(nestedFixture) {
		t.Error("a nested fixture package.json must NOT be treated as an installed package")
	}
	if isNodePackageManifest(appRoot) {
		t.Error("the project-root package.json (not under node_modules) must NOT be cataloged")
	}

	c, ok := nodeComponent(unscoped)
	if !ok || c.PURL != "pkg:npm/lodash@4.17.21" || c.Name != "lodash" {
		t.Errorf("nodeComponent(unscoped) = %+v, ok=%v", c, ok)
	}
	c, ok = nodeComponent(scoped)
	if !ok || c.PURL != "pkg:npm/%40babel/core@7.22.0" || c.Name != "@babel/core" {
		t.Errorf("nodeComponent(scoped) = %+v, ok=%v", c, ok)
	}
	if _, ok := nodeComponent(noVersion); ok {
		t.Error("a manifest without a version must yield nothing")
	}
}

func TestGemComponent(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, content string) string {
		p := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}

	// The serialized form RubyGems writes into specifications/ (Gem::Specification#to_ruby).
	railsSpec := "# -*- encoding: utf-8 -*-\n" +
		"Gem::Specification.new do |s|\n" +
		"  s.name = \"rails\".freeze\n" +
		"  s.version = \"7.0.4\".freeze\n" +
		"  s.platform = \"ruby\".freeze\n" +
		"end\n"
	rails := write("usr/lib/ruby/gems/3.1.0/specifications/rails-7.0.4.gemspec", railsSpec)
	if !isInstalledGemspec(rails) {
		t.Fatal("a *.gemspec under specifications/ must be recognized")
	}
	c, ok := gemComponent(rails)
	if !ok || c.PURL != "pkg:gem/rails@7.0.4" || c.Name != "rails" {
		t.Errorf("gemComponent(rails) = %+v, ok=%v", c, ok)
	}

	// A platform gem keeps the clean version from s.version (the platform lives on its own line).
	nokoSpec := "Gem::Specification.new do |s|\n" +
		"  s.name = \"nokogiri\".freeze\n" +
		"  s.version = \"1.15.0\".freeze\n" +
		"  s.platform = \"x86_64-linux\".freeze\n" +
		"end\n"
	noko := write("usr/lib/ruby/gems/3.1.0/specifications/nokogiri-1.15.0-x86_64-linux.gemspec", nokoSpec)
	if c, ok := gemComponent(noko); !ok || c.PURL != "pkg:gem/nokogiri@1.15.0" {
		t.Errorf("gemComponent(platform gem) = %+v, ok=%v; want clean version", c, ok)
	}

	// The older Gem::Version.new(...) version form is also read.
	oldSpec := "Gem::Specification.new do |s|\n  s.name = \"rake\".freeze\n  s.version = Gem::Version.new(\"13.0.6\")\nend\n"
	old := write("usr/lib/ruby/gems/3.1.0/specifications/rake-13.0.6.gemspec", oldSpec)
	if c, ok := gemComponent(old); !ok || c.PURL != "pkg:gem/rake@13.0.6" {
		t.Errorf("gemComponent(Gem::Version form) = %+v, ok=%v", c, ok)
	}

	// A hand-written source .gemspec (NOT under specifications/) is not treated as an installed spec.
	source := write("app/mygem.gemspec", "Gem::Specification.new do |s|\n  s.name = \"mygem\"\n  s.version = MyGem::VERSION\nend\n")
	if isInstalledGemspec(source) {
		t.Error("a source .gemspec outside specifications/ must NOT be treated as installed")
	}
}

// TestCatalogInstalledLanguages exercises the full rootfs walk over a mixed image: a jar, an installed npm
// package, and an installed gem all surface with matcher-ready PURLs.
func TestCatalogInstalledLanguages(t *testing.T) {
	rootfs := t.TempDir()
	writeJar(t, filepath.Join(rootfs, "opt/app/service.jar"), map[string]string{
		"META-INF/maven/io.netty/netty-common/pom.properties": "groupId=io.netty\nartifactId=netty-common\nversion=4.1.94.Final\n",
	})
	mustWrite := func(rel, content string) {
		p := filepath.Join(rootfs, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	mustWrite("app/node_modules/express/package.json", `{"name":"express","version":"4.18.2"}`)
	mustWrite("usr/lib/ruby/gems/3.1.0/specifications/puma-6.4.0.gemspec",
		"Gem::Specification.new do |s|\n  s.name = \"puma\".freeze\n  s.version = \"6.4.0\".freeze\nend\n")

	comps, err := Cataloger{}.CatalogInstalled(context.Background(), rootfs)
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]bool{}
	for _, c := range comps {
		got[c.PURL] = true
	}
	for _, want := range []string{
		"pkg:maven/io.netty/netty-common@4.1.94.Final",
		"pkg:npm/express@4.18.2",
		"pkg:gem/puma@6.4.0",
	} {
		if !got[want] {
			t.Errorf("expected %s in catalog, got %v", want, keys(got))
		}
	}
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// jarBytes builds an in-memory jar (zip) from name->content entries.
func jarBytes(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, content := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// writeNestedJar writes an outer jar whose named entries carry raw byte content (e.g. a nested jar).
func writeNestedJar(t *testing.T, path string, raw map[string][]byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	zw := zip.NewWriter(f)
	for name, content := range raw {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write(content); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
}

func TestJarNestedArchives(t *testing.T) {
	dir := t.TempDir()
	// A Spring Boot fat jar nests its dependency jars under BOOT-INF/lib, each with its own pom.properties.
	nested := jarBytes(t, map[string]string{
		"META-INF/maven/org.apache.logging.log4j/log4j-core/pom.properties": "groupId=org.apache.logging.log4j\nartifactId=log4j-core\nversion=2.14.1\n",
	})
	boot := filepath.Join(dir, "app.jar")
	writeNestedJar(t, boot, map[string][]byte{
		"BOOT-INF/lib/log4j-core-2.14.1.jar": nested,
		"META-INF/MANIFEST.MF":               []byte("Manifest-Version: 1.0\nMain-Class: org.springframework.boot.loader.JarLauncher\n"),
		"BOOT-INF/classes/App.class":         []byte("x"),
	})
	comps := jarComponents(boot)
	found := false
	for _, c := range comps {
		if c.PURL == "pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1" && c.Name == "org.apache.logging.log4j:log4j-core" {
			found = true
		}
	}
	if !found {
		t.Errorf("nested dependency jar must be cataloged, got %+v", comps)
	}
}

func TestNonConcreteVersionRejected(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, content string) string {
		p := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}
	// A dist-tag / meta version is not a concrete version; emitting it would key a wrong or unmatched CVE.
	npm := write("app/node_modules/lodash/package.json", `{"name":"lodash","version":"latest"}`)
	if _, ok := nodeComponent(npm); ok {
		t.Error(`npm version "latest" must be rejected`)
	}
	gem := write("usr/lib/ruby/gems/3.1.0/specifications/rack-latest.gemspec",
		"Gem::Specification.new do |s|\n  s.name = \"rack\".freeze\n  s.version = \"latest\".freeze\nend\n")
	if _, ok := gemComponent(gem); ok {
		t.Error(`gem version "latest" must be rejected`)
	}
}

func TestDefaultGemCataloged(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, filepath.FromSlash("usr/lib/ruby/gems/3.1.0/specifications/default/rexml-3.2.5.gemspec"))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte("Gem::Specification.new do |s|\n  s.name = \"rexml\".freeze\n  s.version = \"3.2.5\".freeze\nend\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !isInstalledGemspec(p) {
		t.Fatal("a default gem under specifications/default/ must be recognized")
	}
	if c, ok := gemComponent(p); !ok || c.PURL != "pkg:gem/rexml@3.2.5" {
		t.Errorf("gemComponent(default gem) = %+v, ok=%v", c, ok)
	}
}

// A nested entry that is not a valid zip is skipped by the EOCD guard, without panicking or emitting.
func TestJarNestedGarbageSkipped(t *testing.T) {
	dir := t.TempDir()
	outer := filepath.Join(dir, "outer.jar")
	writeNestedJar(t, outer, map[string][]byte{
		"BOOT-INF/lib/notazip.jar":          []byte("this is not a zip archive at all"),
		"META-INF/maven/g/a/pom.properties": []byte("groupId=g\nartifactId=a\nversion=1.0.0\n"),
	})
	comps := jarComponents(outer) // must not panic; the valid top-level coordinate still surfaces
	found := false
	for _, c := range comps {
		if c.PURL == "pkg:maven/g/a@1.0.0" {
			found = true
		}
	}
	if !found {
		t.Errorf("a garbage nested jar must be skipped while the valid top-level coordinate is kept, got %+v", comps)
	}
}

// A serialized gemspec with two s.version assignments is not a standard installed spec; fail closed rather
// than emit a version that disagrees with Ruby's last-assignment-wins semantics.
func TestGemDuplicateVersionRejected(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, filepath.FromSlash("usr/lib/ruby/gems/3.1.0/specifications/rack-3.0.8.gemspec"))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	spec := "Gem::Specification.new do |s|\n  s.name = \"rack\".freeze\n  s.version = \"2.0.0\".freeze\n  s.version = \"3.0.8\".freeze\nend\n"
	if err := os.WriteFile(p, []byte(spec), 0o644); err != nil {
		t.Fatal(err)
	}
	if c, ok := gemComponent(p); ok {
		t.Errorf("a gemspec with two s.version lines must be rejected, got %+v", c)
	}
}

// A pom.properties whose real content exceeds the read cap is skipped, never parsed as a truncated prefix
// that could yield a wrong (earlier) version.
func TestJarOversizePomSkipped(t *testing.T) {
	dir := t.TempDir()
	jar := filepath.Join(dir, "big.jar")
	// A valid early version, then filler pushing a later version past the 64KiB cap.
	body := "groupId=com.example\nartifactId=demo\nversion=1.0.0\n" + strings.Repeat("# pad\n", 20000) + "version=2.0.0\n"
	writeJar(t, jar, map[string]string{"META-INF/maven/com.example/demo/pom.properties": body})
	if got := jarComponents(jar); len(got) != 0 {
		t.Errorf("an over-cap pom.properties must be skipped, got %+v", got)
	}
}
