<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="dependencies/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Reachbench.Direct" Version="1.0.0" />
    <PackageReference Include="Reachbench.Dynamic" Version="1.0.0" />
    <PackageReference Include="Reachbench.Unused" Version="1.0.0" />
    <PackageReference Include="Reachbench.Unsupported" Version="1.0.0" Condition="'$(TargetFramework)' == 'net9.0'" />
  </ItemGroup>
</Project>
