package sca

import (
	"strings"
	"unicode"

	"github.com/KKloudTarus/synapse-ce/internal/domain/agent"
	"github.com/KKloudTarus/synapse-ce/internal/domain/finding"
	"github.com/KKloudTarus/synapse-ce/internal/domain/judgment"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
	"github.com/KKloudTarus/synapse-ce/internal/domain/verdict"
	fptriageuc "github.com/KKloudTarus/synapse-ce/internal/usecase/fptriage"
	"github.com/KKloudTarus/synapse-ce/internal/usecase/ports"
)

// aiTriagePolicyVersion is sealed with every scan that carries AI triage. Bump it whenever the
// authorization contract changes so an audit can replay which policy could affect a CI gate.
const aiTriagePolicyVersion = "fp-gate-v5"

// EvaluationPolicyVersion returns the immutable policy identity for evaluation report metadata without
// exporting the authorization constant as part of the package API.
func EvaluationPolicyVersion() string { return aiTriagePolicyVersion }

// aiTriageMode controls whether an otherwise-authorized AI consensus can affect a quality gate.
// The zero value is deliberately shadow so missing/invalid composition fails closed.
type aiTriageMode string

const (
	aiTriageModeShadow  aiTriageMode = "shadow"
	aiTriageModeEnforce aiTriageMode = "enforce"
)

const (
	aiPolicyNotSuspected                  = "not_suspected_false_positive"
	aiPolicyVerifierRequired              = "distinct_verifier_required"
	aiPolicyIndependenceRequired          = "verifier_independence_required"
	aiPolicyFindingMissing                = "finding_not_found"
	aiPolicyFindingIneligible             = "finding_not_eligible"
	aiPolicySeverityFloor                 = "severity_requires_human"
	aiPolicySecretFloor                   = "secret_requires_human"
	aiPolicyDangerousCWEFloor             = "cwe_requires_human"
	aiPolicyEvidenceRequired              = "evidence_ledger_required"
	aiPolicyDeterministicEvidenceRequired = "deterministic_evidence_required"
	aiPolicyShadowMode                    = "shadow_mode"
	aiPolicyVerifiedConsensus             = "verified_consensus"
)

// humanReviewCWEs are weakness classes where a false negative can directly expose an execution,
// injection, authentication/authorization, request-forgery, traversal, upload, or deserialization
// boundary. Even two agreeing models can only advise on these classes; they never exempt the gate.
var humanReviewCWEs = map[string]struct{}{
	"CWE-22": {}, "CWE-23": {}, "CWE-36": {}, "CWE-78": {}, "CWE-79": {}, "CWE-89": {}, "CWE-94": {},
	"CWE-259": {}, "CWE-321": {}, "CWE-284": {}, "CWE-285": {}, "CWE-287": {}, "CWE-306": {},
	"CWE-434": {}, "CWE-502": {}, "CWE-522": {}, "CWE-798": {}, "CWE-862": {}, "CWE-863": {}, "CWE-918": {},
}

// applyAIGatePolicy is retained for package-level policy tests and historical non-service callers.
// The production scan path MUST call applyAIGatePolicyWithServerEvidence with a separately derived map.
// Keeping this compatibility seam prevents unrelated policy tests from needing to fabricate SAST raw
// producer state; it is not used by Service.runFPTriage.
func applyAIGatePolicy(result *ScanResult, evidenceAvailable bool, mode aiTriageMode) {
	applyAIGatePolicyWithIndependence(result, evidenceAvailable, mode, ports.AIIndependenceModelFamily)
}

// applyAIGatePolicyWithIndependence has the same compatibility-only role as applyAIGatePolicy. The
// evaluation harness runs in shadow mode and cannot grant gate authority. Production authorization uses
// applyAIGatePolicyWithServerEvidence directly with server-re-derived evidence.
func applyAIGatePolicyWithIndependence(result *ScanResult, evidenceAvailable bool, mode aiTriageMode, independence ports.AIIndependencePolicy) {
	compat := make(map[string][]ports.AITriageEvidenceToken)
	if result != nil {
		for _, critique := range result.AITriage {
			if key := strings.TrimSpace(critique.DedupKey); key != "" {
				compat[key] = append([]ports.AITriageEvidenceToken(nil), critique.ContextEvidence...)
			}
		}
	}
	applyAIGatePolicyWithServerEvidence(result, evidenceAvailable, mode, independence, compat)
}

// applyAIGatePolicyWithServerEvidence is the production authorizing boundary. serverEvidence is
// generated by aiTriageEvidenceForCandidates before the port call and is intentionally independent of
// the AICritique DTO. The carried ContextEvidence is audit metadata only and must match this server copy.
func applyAIGatePolicyWithServerEvidence(result *ScanResult, evidenceAvailable bool, mode aiTriageMode, independence ports.AIIndependencePolicy, serverEvidence map[string][]ports.AITriageEvidenceToken) {
	if result == nil || len(result.AITriage) == 0 {
		return
	}
	independence = normalizeAIIndependencePolicy(independence)
	findings := make(map[string]finding.Finding, len(result.Findings))
	for _, item := range result.Findings {
		if key := strings.TrimSpace(item.DedupKey); key != "" {
			findings[key] = item
		}
	}
	for i := range result.AITriage {
		critique := &result.AITriage[i]
		critique.PolicyVersion = aiTriagePolicyVersion
		critique.IndependencePolicy = independence
		critique.Shadow = mode != aiTriageModeEnforce
		critique.WouldGateExempt = false
		critique.GateExempt = false
		critique.ReviewRequired = false

		if !critique.SuspectedFP {
			critique.PolicyReason = aiPolicyNotSuspected
			continue
		}
		if independence == "" {
			critique.PolicyReason = aiPolicyIndependenceRequired
			critique.ReviewRequired = true
			continue
		}
		if strings.TrimSpace(critique.VerifierModel) == "" {
			critique.PolicyReason = aiPolicyVerifierRequired
			critique.ReviewRequired = true
			continue
		}
		if !hasIndependentVerifierIdentity(*critique) {
			critique.PolicyReason = aiPolicyIndependenceRequired
			critique.ReviewRequired = true
			continue
		}
		if !hasVerifiedConsensus(*critique) {
			critique.PolicyReason = aiPolicyVerifierRequired
			critique.ReviewRequired = true
			continue
		}
		item, ok := findings[strings.TrimSpace(critique.DedupKey)]
		if !ok {
			critique.PolicyReason = aiPolicyFindingMissing
			critique.ReviewRequired = true
			continue
		}
		if reason := humanReviewFloor(item); reason != "" {
			critique.PolicyReason = reason
			critique.ReviewRequired = true
			continue
		}
		if !isFPTriageEligible(item) {
			critique.PolicyReason = aiPolicyFindingIneligible
			critique.ReviewRequired = true
			continue
		}
		derived, ok := serverEvidence[strings.TrimSpace(critique.DedupKey)]
		if !ok || fptriageuc.ValidateEvidenceReceiptAgainst(*critique, item, derived) != nil {
			critique.PolicyReason = aiPolicyDeterministicEvidenceRequired
			critique.ReviewRequired = true
			continue
		}
		if !evidenceAvailable {
			critique.PolicyReason = aiPolicyEvidenceRequired
			critique.ReviewRequired = true
			continue
		}
		if mode != aiTriageModeEnforce {
			critique.PolicyReason = aiPolicyShadowMode
			critique.WouldGateExempt = true
			critique.ReviewRequired = true
			continue
		}
		critique.PolicyReason = aiPolicyVerifiedConsensus
		critique.GateExempt = true
	}
}

// hasVerifiedConsensus validates the full DTO rather than trusting its Verified boolean. This keeps a
// buggy or alternate FPTriager implementation from granting itself gate authority by setting one field.
func hasVerifiedConsensus(c ports.AICritique) bool {
	return c.Verified && hasIndependentVerifierIdentity(c) &&
		c.Verdict == string(judgment.CritiqueRefuted) && c.Confidence >= verdict.EvidenceThreshold &&
		c.VerifierVerdict == string(judgment.CritiqueRefuted) && c.VerifierConfidence >= verdict.EvidenceThreshold
}

func hasIndependentVerifierIdentity(c ports.AICritique) bool {
	proposerFamily := agent.CanonicalModelID(c.ProposerModel)
	verifierFamily := agent.CanonicalModelID(c.VerifierModel)
	proposerProvider := agent.CanonicalProviderID(c.ProposerProvider)
	verifierProvider := agent.CanonicalProviderID(c.VerifierProvider)
	return proposerFamily != "" && verifierFamily != "" &&
		c.ProposerModelFamily == proposerFamily && c.VerifierModelFamily == verifierFamily &&
		c.ProposerProvider == proposerProvider && c.VerifierProvider == verifierProvider &&
		agent.IndependentLLMs(proposerProvider, c.ProposerModel, verifierProvider, c.VerifierModel, string(c.IndependencePolicy))
}

func normalizeAIIndependencePolicy(policy ports.AIIndependencePolicy) ports.AIIndependencePolicy {
	switch ports.AIIndependencePolicy(strings.ToLower(strings.TrimSpace(string(policy)))) {
	case ports.AIIndependenceModelFamily:
		return ports.AIIndependenceModelFamily
	case ports.AIIndependenceProvider:
		return ports.AIIndependenceProvider
	default:
		return ""
	}
}

func humanReviewFloor(item finding.Finding) string {
	if item.Severity == shared.SeverityCritical || item.Severity == shared.SeverityHigh {
		return aiPolicySeverityFloor
	}
	if item.Kind == finding.KindSecret {
		return aiPolicySecretFloor
	}
	tokens := cweTokens(item.CWE)
	for _, token := range tokens {
		if _, protected := humanReviewCWEs[token]; protected {
			return aiPolicyDangerousCWEFloor
		}
		if isMalformedCWE(token) {
			return aiPolicyDangerousCWEFloor
		}
	}
	if len(tokens) == 0 && (item.Kind == finding.KindSAST || item.Kind == finding.KindMisconfig) {
		return aiPolicyDangerousCWEFloor
	}
	return ""
}

func cweTokens(value string) []string {
	tokens := strings.FieldsFunc(strings.ToUpper(value), func(r rune) bool {
		switch r {
		case ',', ';', '|', '/', ':', '.', '(', ')':
			return true
		}
		return unicode.IsSpace(r)
	})
	for i := range tokens {
		tokens[i] = canonicalCWEToken(tokens[i])
	}
	return tokens
}

func isMalformedCWE(token string) bool {
	const prefix = "CWE-"
	if !strings.HasPrefix(token, prefix) {
		return false
	}
	digits := strings.TrimPrefix(token, prefix)
	if digits == "" {
		return true
	}
	for _, r := range digits {
		if r < '0' || r > '9' {
			return true
		}
	}
	return false
}

func canonicalCWEToken(token string) string {
	const prefix = "CWE-"
	if !strings.HasPrefix(token, prefix) {
		return token
	}
	digits := strings.TrimPrefix(token, prefix)
	if digits == "" {
		return token
	}
	for _, r := range digits {
		if r < '0' || r > '9' {
			return token
		}
	}
	digits = strings.TrimLeft(digits, "0")
	if digits == "" {
		digits = "0"
	}
	return prefix + digits
}

func hasCredentialCWE(value string) bool {
	for _, token := range cweTokens(value) {
		switch token {
		case "CWE-259", "CWE-321", "CWE-522", "CWE-798":
			return true
		}
	}
	return false
}
