//go:build cgo

package astwalk

// cRuntimeRule is deliberately local to the AST sidecar.
type cRuntimeRule struct {
	kind, rule, cwe, severity, title, description string
}

// cRuntimeRules mirrors the AST-detected c:* catalog entries.
var cRuntimeRules = map[string]cRuntimeRule{
	"stack-buffer-overflow-loop":         {kind: "reliability", rule: "c:stack-buffer-overflow-loop", cwe: "CWE-121", severity: "high", title: "Loop index exceeds stack buffer bounds", description: "Detects loop index upper bound reaching or exceeding sizeof(buffer)."},
	"vla-stack-allocation":               {kind: "sast", rule: "c:vla-stack-allocation", cwe: "CWE-770", severity: "medium", title: "Variable Length Array stack allocation", description: "Detects variable length array (VLA) stack allocations."},
	"alloca-in-loop":                     {kind: "reliability", rule: "c:alloca-in-loop", cwe: "CWE-770", severity: "high", title: "alloca() called inside loop body", description: "Detects alloca() called inside a loop body."},
	"unbounded-memcpy-size":              {kind: "sast", rule: "c:unbounded-memcpy-size", cwe: "CWE-120", severity: "high", title: "memcpy with unvalidated length", description: "Detects memcpy() called with unvalidated user length."},
	"off-by-one-null-terminator":         {kind: "reliability", rule: "c:off-by-one-null-terminator", cwe: "CWE-193", severity: "high", title: "Buffer missing space for null terminator", description: "Detects allocating string buffer with strlen without + 1."},
	"unaligned-pointer-cast":             {kind: "reliability", rule: "c:unaligned-pointer-cast", cwe: "CWE-125", severity: "medium", title: "Pointer cast with stricter alignment", description: "Detects casting byte pointers to types with stricter alignment requirements."},
	"flexible-array-member-misuse":       {kind: "reliability", rule: "c:flexible-array-member-misuse", cwe: "CWE-131", severity: "high", title: "Flexible array allocated without element size", description: "Detects allocating struct with flexible array member without element size."},
	"stack-array-large-allocation":       {kind: "quality", rule: "c:stack-array-large-allocation", cwe: "CWE-770", severity: "low", title: "Large buffer allocated on stack", description: "Detects large array (>64KB) allocated on thread stack."},
	"strncpy-missing-null-termination":   {kind: "reliability", rule: "c:strncpy-missing-null-termination", cwe: "CWE-170", severity: "medium", title: "strncpy without explicit null termination", description: "Detects strncpy called with full buffer size without explicit null termination."},
	"dangling-stack-pointer-return":      {kind: "reliability", rule: "c:dangling-stack-pointer-return", cwe: "CWE-562", severity: "high", title: "Function returns pointer to local stack variable", description: "Detects function returning address of local stack variable."},
	"memset-cleared-by-compiler":         {kind: "sast", rule: "c:memset-cleared-by-compiler", cwe: "CWE-14", severity: "medium", title: "Sensitive buffer memset before exit", description: "Detects memset clearing sensitive buffers which can be optimized away."},
	"printf-non-literal-format":          {kind: "sast", rule: "c:printf-non-literal-format", cwe: "CWE-134", severity: "high", title: "printf format string passed as variable", description: "Detects passing non-literal format string to printf."},
	"percent-n-specifier-used":           {kind: "sast", rule: "c:percent-n-specifier-used", cwe: "CWE-134", severity: "high", title: "%n format specifier used in format string", description: "Detects %n format conversion specifier in format strings."},
	"syslog-variable-format":             {kind: "sast", rule: "c:syslog-variable-format", cwe: "CWE-134", severity: "high", title: "syslog format string from untrusted variable", description: "Detects passing dynamic message variable directly as syslog format."},
	"custom-varargs-missing-format-attr": {kind: "quality", rule: "c:custom-varargs-missing-format-attr", cwe: "CWE-134", severity: "low", title: "Variadic logging function missing format attribute", description: "Detects variadic logging functions lacking __attribute__((format))."},
	"signed-integer-overflow":            {kind: "reliability", rule: "c:signed-integer-overflow", cwe: "CWE-190", severity: "medium", title: "Signed integer arithmetic overflow hazard", description: "Detects unvalidated signed arithmetic addition/multiplication."},
	"signed-unsigned-comparison":         {kind: "reliability", rule: "c:signed-unsigned-comparison", cwe: "CWE-681", severity: "medium", title: "Comparison between signed and unsigned integers", description: "Detects direct relational comparison between signed and unsigned types."},
	"integer-truncation-cast":            {kind: "reliability", rule: "c:integer-truncation-cast", cwe: "CWE-197", severity: "medium", title: "Integer conversion truncates wider type", description: "Detects narrowing integer cast that truncates high bits."},
	"shift-count-overflow":               {kind: "reliability", rule: "c:shift-count-overflow", cwe: "CWE-190", severity: "high", title: "Bit shift count exceeds type bit width", description: "Detects bit shift operand equal to or greater than operand width."},
	"multiplication-overflow-malloc":     {kind: "sast", rule: "c:multiplication-overflow-malloc", cwe: "CWE-190", severity: "high", title: "Multiplication in malloc argument without check", description: "Detects multiplication in allocation size without overflow check."},
	"lossy-pointer-to-int-cast":          {kind: "reliability", rule: "c:lossy-pointer-to-int-cast", cwe: "CWE-704", severity: "high", title: "Pointer cast to narrower integer type", description: "Detects pointer cast to uint32_t instead of uintptr_t."},
	"divide-by-zero-hazard":              {kind: "reliability", rule: "c:divide-by-zero-hazard", cwe: "CWE-369", severity: "high", title: "Division without zero divisor check", description: "Detects division operation without zero divisor validation."},
	"unchecked-malloc-return":            {kind: "reliability", rule: "c:unchecked-malloc-return", cwe: "CWE-476", severity: "high", title: "malloc return value used without NULL check", description: "Detects dereferencing malloc return pointer without checking for NULL."},
	"null-pointer-dereference":           {kind: "reliability", rule: "c:null-pointer-dereference", cwe: "CWE-476", severity: "high", title: "Dereference of known NULL pointer", description: "Detects dereferencing pointers assigned to NULL."},
	"unchecked-fopen-return":             {kind: "reliability", rule: "c:unchecked-fopen-return", cwe: "CWE-476", severity: "high", title: "fopen return value passed without NULL check", description: "Detects passing fopen result to file functions without NULL validation."},
	"unchecked-getenv-return":            {kind: "reliability", rule: "c:unchecked-getenv-return", cwe: "CWE-476", severity: "high", title: "getenv return value used without NULL check", description: "Detects passing getenv() result to string functions without NULL check."},
	"signal-handler-async-unsafe":        {kind: "reliability", rule: "c:signal-handler-async-unsafe", cwe: "CWE-479", severity: "high", title: "Async-signal-unsafe function in signal handler", description: "Detects calling async-signal-unsafe functions inside signal handlers."},
	"volatile-used-for-synchronization":  {kind: "reliability", rule: "c:volatile-used-for-synchronization", cwe: "CWE-362", severity: "medium", title: "volatile used for thread synchronization", description: "Detects volatile variables used as thread synchronization flags."},
	"pthread-join-missing":               {kind: "reliability", rule: "c:pthread-join-missing", cwe: "CWE-404", severity: "medium", title: "pthread_create without join or detach", description: "Detects pthread_create called without pthread_join or pthread_detach."},
	"insecure-rand-function":             {kind: "sast", rule: "c:insecure-rand-function", cwe: "CWE-338", severity: "high", title: "rand() used in security context", description: "Detects rand() or random() used for tokens or crypto operations."},
	"deprecated-des-cipher":              {kind: "sast", rule: "c:deprecated-des-cipher", cwe: "CWE-327", severity: "high", title: "DES or 3DES encryption API used", description: "Detects DES encryption routines."},
	"hardcoded-cryptographic-key":        {kind: "sast", rule: "c:hardcoded-cryptographic-key", cwe: "CWE-321", severity: "high", title: "Hardcoded cryptographic key material in C", description: "Detects static cryptographic key string literal."},
	"static-iv-initialization":           {kind: "sast", rule: "c:static-iv-initialization", cwe: "CWE-329", severity: "high", title: "Static initialization vector used with cipher", description: "Detects constant all-zero initialization vector used with block cipher."},
	"insecure-md5-hashing":               {kind: "sast", rule: "c:insecure-md5-hashing", cwe: "CWE-327", severity: "medium", title: "MD5 hash function used in security verification", description: "Detects MD5 hash functions used in security contexts."},
	"insecure-ssl-version":               {kind: "sast", rule: "c:insecure-ssl-version", cwe: "CWE-326", severity: "high", title: "Deprecated SSLv2, SSLv3, or TLS 1.0/1.1 protocol", description: "Detects enabling legacy SSLv2/SSLv3/TLS 1.0 protocols."},
	"long-function-body":                 {kind: "quality", rule: "c:long-function-body", cwe: "CWE-1120", severity: "low", title: "Function body exceeds statement count", description: "Detects functions containing more than 50 statements."},
	"deeply-nested-control-flow":         {kind: "quality", rule: "c:deeply-nested-control-flow", cwe: "CWE-1120", severity: "medium", title: "Deeply nested control structures", description: "Detects control flow nested beyond four levels."},
	"excessive-parameters":               {kind: "quality", rule: "c:excessive-parameters", cwe: "CWE-1120", severity: "low", title: "Function declared with too many parameters", description: "Detects functions declared with more than seven parameters."},
	"goto-backward-jump":                 {kind: "quality", rule: "c:goto-backward-jump", cwe: "CWE-1120", severity: "low", title: "Backward goto jump used for looping", description: "Detects goto jumps jumping backwards to previous labels."},
	"macro-missing-parentheses":          {kind: "reliability", rule: "c:macro-missing-parentheses", cwe: "CWE-783", severity: "medium", title: "Macro parameter missing safety parentheses", description: "Detects preprocessor macro expressions without parameter parentheses."},
	"magic-numbers-in-logic":             {kind: "quality", rule: "c:magic-numbers-in-logic", cwe: "CWE-1120", severity: "low", title: "Unnamed numeric literal in conditional logic", description: "Detects unnamed numeric constants in relational expressions."},
	"todo-comment-left":                  {kind: "quality", rule: "c:todo-comment-left", cwe: "CWE-546", severity: "info", title: "TODO or FIXME marker in source code", description: "Detects TODO or FIXME comments left in source code."},
	"commented-out-c-code":               {kind: "quality", rule: "c:commented-out-c-code", cwe: "CWE-561", severity: "info", title: "Block of commented-out C code", description: "Detects blocks of commented-out C code statements."},
	"single-letter-identifier":           {kind: "quality", rule: "c:single-letter-identifier", cwe: "CWE-1120", severity: "low", title: "Single-letter variable name in wide scope", description: "Detects single-letter variable names used across wide scopes."},
	"duplicate-switch-cases":             {kind: "reliability", rule: "c:duplicate-switch-cases", cwe: "CWE-561", severity: "medium", title: "Duplicate case label in switch statement", description: "Detects duplicate case labels in switch statements."},
	"unreachable-code-after-return":      {kind: "reliability", rule: "c:unreachable-code-after-return", cwe: "CWE-561", severity: "medium", title: "Statement immediately follows return", description: "Detects unreachable statements following unconditional returns."},
}
