import { AlertTriangle, ArrowLeft, Boxes, Bug, CalendarClock, FolderGit2, History, ListChecks, Server, ShieldQuestion, Target } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, NavLink, Outlet, useOutletContext, useParams } from 'react-router-dom'
import { Button, Card, EmptyState, ErrorState, Field, Input, Pill, Select, SevBadge, Spinner, cn } from '../components/ui'
import { api, ApiError } from '../lib/api'
import type { AssetCoverage, AssetCoverageVerdict, AssetFinding, AssetHistoryItem, AssetMembership, AssetPosture, BusinessAsset, BusinessAssetCriticality, BusinessAssetLifecycle, BusinessAssetType, Engagement } from '../lib/types'
import { PostureBadge } from './Assets'
import { StatusPill } from './Engagements'

type Context={asset:BusinessAsset;projects:AssetMembership[];technical:AssetMembership[];engagements:Engagement[];findings:AssetFinding[];coverage:AssetCoverage;posture:AssetPosture;history:AssetHistoryItem[];reload:()=>void}
export function useAssetContext(){return useOutletContext<Context>()}

export function AssetDetail(){const{key=''}=useParams();const[data,setData]=useState<Context|null|undefined>(undefined);const[error,setError]=useState<string|null>(null)
  function load(){setError(null);Promise.all([api.getBusinessAsset(key),api.businessAssetProjects(key),api.businessAssetTechnicalAssets(key),api.businessAssetEngagements(key),api.businessAssetFindings(key),api.businessAssetCoverage(key),api.businessAssetPosture(key),api.businessAssetHistory(key)]).then(([asset,projects,technical,engagements,findings,coverage,posture,history])=>setData({asset,projects,technical,engagements,findings,coverage,posture,history,reload:load})).catch(e=>{if(e instanceof ApiError&&e.status===404)setData(null);else setError(e instanceof Error?e.message:'Failed to load Asset')})}
  useEffect(load,[key])
  if(error)return <div className="mx-auto max-w-6xl"><ErrorState message={error}/></div>;if(data===undefined)return <Spinner label="Loading Asset…"/>;if(!data)return <EmptyState icon={Boxes} title="Asset not found" hint="It may not exist or belongs to another tenant."/>
  const retired=data.asset.lifecycle==='retired';return <div className="mx-auto max-w-7xl animate-fade-in"><Link to="/assets" className="mb-4 inline-flex items-center gap-1.5 text-sm text-mutedfg hover:text-foreground"><ArrowLeft className="size-4"/>All Assets</Link><header className="bg-hero mb-5 rounded-xl border border-border p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-bold tracking-tight">{data.asset.name}</h1><PostureBadge rating={data.posture.rating}/></div><p className="mt-1 font-mono text-xs text-subtlefg">{data.asset.key}</p><p className="mt-3 max-w-3xl text-sm text-mutedfg">{data.asset.description||'No description.'}</p></div><div className="flex flex-wrap gap-2"><Pill>{data.asset.type.replace('_',' ')}</Pill><Pill>{data.asset.criticality}</Pill><Pill>{data.asset.lifecycle}</Pill></div></div></header>{retired&&<div className="mb-5 flex items-start gap-3 rounded-xl border border-high/30 bg-high/10 p-4 text-sm text-high"><AlertTriangle className="mt-0.5 size-4 shrink-0"/><span>This Asset is retired and remains readable for history. Membership and assignment changes are disabled.</span></div>}<nav className="mb-6 flex gap-6 overflow-x-auto border-b border-border whitespace-nowrap" aria-label="Asset views"><Tab to="." end>Overview</Tab><Tab to="components">Components</Tab><Tab to="engagements">Engagements</Tab><Tab to="findings">Findings</Tab><Tab to="coverage">Coverage</Tab><Tab to="history">History</Tab></nav><Outlet context={data}/></div>}
function Tab({to,end=false,children}:{to:string;end?:boolean;children:React.ReactNode}){return <NavLink to={to} end={end} className={({isActive})=>cn('shrink-0 border-b-2 px-1 pb-2 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand/60',isActive?'border-brand text-foreground':'border-transparent text-mutedfg')}>{children}</NavLink>}

function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-lg border border-border bg-elevated px-4 py-3"><div className="text-2xl font-bold tabular-nums">{value}</div><div className="mt-0.5 text-xs text-mutedfg">{label}</div></div>}
export function AssetOverview(){const c=useAssetContext();return <div className="space-y-5"><Card title="Security posture"><div className="flex items-start gap-3"><ShieldQuestion className="mt-0.5 size-5 text-branddim"/><div><PostureBadge rating={c.posture.rating}/><p className="mt-2 text-sm text-mutedfg">{c.posture.explanation}</p></div></div></Card><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Projects" value={c.projects.length}/><Stat label="Technical assets" value={c.technical.length}/><Stat label="Engagements" value={c.engagements.length}/><Stat label="Publishable findings" value={c.findings.length}/></div><AssetEditor/></div>}

function AssetEditor(){const c=useAssetContext();const[name,setName]=useState(c.asset.name);const[description,setDescription]=useState(c.asset.description);const[owner,setOwner]=useState(c.asset.owner);const[type,setType]=useState<BusinessAssetType>(c.asset.type);const[criticality,setCriticality]=useState<BusinessAssetCriticality>(c.asset.criticality);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const retired=c.asset.lifecycle==='retired';const next:Partial<Record<BusinessAssetLifecycle,BusinessAssetLifecycle>>={draft:'active',active:'decommissioning',decommissioning:'retired'}
  async function save(lifecycle=c.asset.lifecycle){setSaving(true);setError(null);try{await api.updateBusinessAsset(c.asset.id,{name:name.trim(),description:description.trim(),owner:owner.trim(),type,criticality,lifecycle,version:c.asset.version,metadata:c.asset.metadata});c.reload()}catch(e){setError(e instanceof Error?e.message:'Failed to update Asset')}finally{setSaving(false)}}
  return <Card title="Asset metadata and lifecycle" actions={<div className="flex gap-2"><Button variant="secondary" disabled={retired} loading={saving} onClick={()=>save()}>Save</Button>{next[c.asset.lifecycle]&&<Button variant="brand" disabled={saving} onClick={()=>save(next[c.asset.lifecycle])}>{next[c.asset.lifecycle]==='retired'?'Retire Asset':`Move to ${next[c.asset.lifecycle]}`}</Button>}</div>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input value={name} disabled={retired} onChange={e=>setName(e.target.value)}/></Field><Field label="Owner"><Input value={owner} disabled={retired} onChange={e=>setOwner(e.target.value)}/></Field><Field label="Type"><Select value={type} disabled={retired} onValueChange={v=>setType(v as BusinessAssetType)} options={[{value:'product',label:'Product'},{value:'application',label:'Application'},{value:'system',label:'System'},{value:'business_service',label:'Business service'}]}/></Field><Field label="Criticality"><Select value={criticality} disabled={retired} onValueChange={v=>setCriticality(v as BusinessAssetCriticality)} options={[{value:'critical',label:'Critical'},{value:'high',label:'High'},{value:'medium',label:'Medium'},{value:'low',label:'Low'}]}/></Field><Field label="Description"><Input value={description} disabled={retired} onChange={e=>setDescription(e.target.value)}/></Field><div><div className="text-xs uppercase tracking-wide text-subtlefg">Lifecycle / version</div><div className="mt-2 flex gap-2"><Pill>{c.asset.lifecycle}</Pill><Pill>v{c.asset.version}</Pill></div></div></div>{error&&<div className="mt-4"><ErrorState message={error}/></div>}</Card>}

function MembershipEditor({title,icon:Icon,items,options,technical=false}:{title:string;icon:typeof Boxes;items:AssetMembership[];options:{value:string;label:string}[];technical?:boolean}){const c=useAssetContext();const[rows,setRows]=useState(items);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const retired=c.asset.lifecycle==='retired';const known=new Set(options.map(option=>option.value));const componentOptions=[{value:'',label:'Select component'},...options,...rows.filter(row=>row.componentId&&!known.has(row.componentId)).map(row=>({value:row.componentId,label:row.componentId}))];async function save(){setSaving(true);setError(null);try{if(technical)await api.replaceBusinessAssetTechnicalAssets(c.asset.id,rows);else await api.replaceBusinessAssetProjects(c.asset.id,rows);c.reload()}catch(e){setError(e instanceof Error?e.message:'Failed to save components')}finally{setSaving(false)}}return <Card title={title} actions={<Button variant="secondary" disabled={retired} loading={saving} onClick={save}>Save</Button>}><div className="space-y-3">{rows.map((row,i)=><div key={`${row.componentId}-${i}`} className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_150px_minmax(0,1fr)_auto]"><Select ariaLabel={`${title} component`} disabled={retired} value={row.componentId} onValueChange={componentId=>setRows(v=>v.map((x,j)=>j===i?{...x,componentId}:x))} options={componentOptions}/><Select ariaLabel={`${title} role`} disabled={retired} value={row.role} onValueChange={role=>setRows(v=>v.map((x,j)=>j===i?{...x,role:role as AssetMembership['role']}:x))} options={[{value:'primary',label:'Primary'},{value:'supporting',label:'Supporting'},{value:'dependency',label:'Dependency'}]}/><Input aria-label={`${title} provenance`} disabled={retired} value={row.provenance} onChange={e=>setRows(v=>v.map((x,j)=>j===i?{...x,provenance:e.target.value}:x))}/><button type="button" disabled={retired} onClick={()=>setRows(v=>v.filter((_,j)=>j!==i))} className="rounded-lg px-3 text-mutedfg hover:bg-elevated disabled:opacity-40" aria-label="Remove component">×</button></div>)}{rows.length===0&&<div className="flex items-center gap-2 text-sm text-mutedfg"><Icon className="size-4"/>No components linked.</div>}<Button variant="secondary" disabled={retired||options.length===0} onClick={()=>setRows(v=>[...v,{componentId:'',role:'supporting',provenance:'manual'}])}>Add component</Button>{error&&<ErrorState message={error}/>}</div></Card>}
export function AssetComponents(){const c=useAssetContext();const[options,setOptions]=useState<{projects:{value:string;label:string}[];technical:{value:string;label:string}[]}|null>(null);const[error,setError]=useState<string|null>(null);useEffect(()=>{Promise.all([api.listProjects(),api.listTechnicalAssets().catch(e=>{if(e instanceof ApiError&&e.status===404)return[];throw e})]).then(([projects,technical])=>setOptions({projects:projects.map(project=>({value:project.id,label:`${project.name} · ${project.key}`})),technical:technical.map(item=>({value:item.id,label:`${item.name} · ${item.kind} · ${item.key}`}))})).catch(e=>setError(e instanceof Error?e.message:'Failed to load available components'))},[]);if(error)return <ErrorState message={error}/>;if(!options)return <Spinner label="Loading available components…"/>;return <div className="space-y-5"><MembershipEditor title="Projects / repositories" icon={FolderGit2} items={c.projects} options={options.projects}/><MembershipEditor title="Technical / fleet assets" icon={Server} items={c.technical} options={options.technical} technical/></div>}

export function AssetEngagements(){const c=useAssetContext();if(!c.engagements.length)return <EmptyState icon={Target} title="No Engagements assigned" hint="Assign an existing Engagement or select this Asset when creating one."/>;return <div className="space-y-3">{c.engagements.map(e=><Link key={e.id} to={`/engagements/${e.id}`} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-card p-4 hover:border-brand/40"><div><div className="font-medium">{e.name}</div><div className="mt-1 text-xs text-mutedfg">{e.inScope.length} in scope · {e.authorizedFrom?new Date(e.authorizedFrom).toLocaleDateString():'Open start'} → {e.authorizedTo?new Date(e.authorizedTo).toLocaleDateString():'Open end'}</div></div><StatusPill status={e.status}/></Link>)}</div>}
export function AssetFindings(){const c=useAssetContext();if(!c.findings.length)return <EmptyState icon={Bug} title="No current findings" hint="This is not a clean result unless Coverage is complete and current."/>;return <Card title="Findings" bodyClass="divide-y divide-border p-0">{c.findings.map(row=><Link key={`${row.external?'external':'internal'}-${row.finding.id}`} to={row.external?`/engagements/${row.engagementId}`:`/engagements/${row.engagementId}#finding-${encodeURIComponent(row.finding.id)}`} className="flex items-start justify-between gap-4 p-4 hover:bg-elevated"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{row.finding.title}</span>{row.external&&<Pill>External · {row.provenance?.toolName||'unknown tool'}</Pill>}{row.suppressedByTool&&<Pill>Suppressed by tool</Pill>}</div><div className="mt-1 text-xs text-mutedfg">{row.engagementName} · {row.external?'external result':row.finding.status} · reachability {row.reachability.state} ({row.reachability.tier}){row.reachability.status?` · ${row.reachability.status}`:''}</div>{row.external&&row.provenance&&<div className="mt-1 font-mono text-[11px] text-subtlefg">{row.provenance.toolName} {row.provenance.toolVersion} · {row.provenance.ruleId} · {row.provenance.sourceDigest}</div>}</div><SevBadge sev={row.finding.severity}/></Link>)}</Card>}

const COVERAGE_STYLE:Record<AssetCoverageVerdict,string>={covered:'bg-accent/10 text-accent ring-accent/30',stale:'bg-info/10 text-info ring-info/30',not_assessed:'bg-muted text-mutedfg ring-border',unknown:'bg-muted text-mutedfg ring-border',excluded:'bg-medium/10 text-medium ring-medium/30',failed:'bg-critical/10 text-critical ring-critical/30',partial:'bg-high/10 text-high ring-high/30',unauthorized:'bg-critical/10 text-critical ring-critical/30'}
function CoverageBadge({verdict}:{verdict:AssetCoverageVerdict}){return <span className={cn('inline-flex rounded-md px-2 py-0.5 text-xs font-semibold ring-1 ring-inset',COVERAGE_STYLE[verdict])}>{verdict.replace('_',' ')}</span>}
export function AssetCoverageView(){const c=useAssetContext();if(!c.coverage.rows.length)return <EmptyState icon={ListChecks} title="No expected components" hint="Link Projects or technical assets to establish the coverage denominator."/>;return <div className="space-y-4"><Card title={`Coverage · ${c.coverage.freshnessTargetDays} day freshness target`}><div className="flex flex-wrap gap-3">{Object.entries(c.coverage.counts).map(([v,n])=><span key={v} className="inline-flex items-center gap-2"><CoverageBadge verdict={v as AssetCoverageVerdict}/><span className="text-sm tabular-nums text-mutedfg">{n}</span></span>)}</div></Card><div className="space-y-2">{c.coverage.rows.map(r=><div key={`${r.kind}-${r.componentId}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4"><div><div className="font-mono text-sm">{r.name||r.componentId}</div><div className="mt-1 text-xs text-mutedfg">{r.kind} · {r.lastAssessed?`last assessed ${new Date(r.lastAssessed).toLocaleString()}`:'never assessed'}</div></div><CoverageBadge verdict={r.verdict}/></div>)}</div></div>}
export function AssetHistory(){const c=useAssetContext();if(!c.history.length)return <EmptyState icon={History} title="No assessment history" hint="Assigned Engagements and retests will appear here without rewriting historical records."/>;return <div className="space-y-3">{c.history.map(h=><Link key={h.engagementId} to={`/engagements/${h.engagementId}`} className="flex items-start gap-4 rounded-xl border border-border bg-card p-4 hover:border-brand/40"><CalendarClock className="mt-0.5 size-5 text-branddim"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{h.name}</span><StatusPill status={h.status}/></div><p className="mt-1 text-xs text-mutedfg">{h.scopeCount} scope targets · {h.findingCount} findings · {h.retestCount} retests · updated {new Date(h.updatedAt).toLocaleString()}</p></div></Link>)}</div>}
