package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func armRules() []rule.Rule {
	return []rule.Rule{
		{
			Key: "arm-storage-public-blob", Name: "Storage account permits public blob access", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "storage", "public-access"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Storage account explicitly permits anonymous public blob access.",
			Rationale:           "Anonymous blob access can expose data without identity-based authorization and is frequently enabled accidentally at the container layer.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set allowBlobPublicAccess to false and authorize clients with Microsoft Entra ID or narrowly scoped SAS tokens.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"allowBlobPublicAccess\":false}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"allowBlobPublicAccess\":true}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-nsg-open-inbound", Name: "Network security rule allows internet-wide inbound access", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "network", "firewall"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure network security group contains an Allow inbound rule whose source covers the entire internet.",
			Rationale:           "Internet-wide inbound rules expose services to continuous scanning, credential attacks, and exploitation of remotely reachable vulnerabilities.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Restrict the source prefixes and destination ports to the smallest trusted ranges that require access.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkSecurityGroups\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityRules\":[{\"name\":\"ssh\",\"properties\":{\"direction\":\"Inbound\",\"access\":\"Allow\",\"sourceAddressPrefix\":\"10.0.0.0/8\",\"destinationPortRange\":\"22\"}}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkSecurityGroups\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityRules\":[{\"name\":\"ssh\",\"properties\":{\"direction\":\"Inbound\",\"access\":\"Allow\",\"sourceAddressPrefix\":\"0.0.0.0/0\",\"destinationPortRange\":\"22\"}}]}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-public-ip-on-nic", Name: "Network interface attaches a public IP address", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "network", "public-access"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A network interface IP configuration references an Azure Public IP resource.",
			Rationale:           "Attaching a public address directly to a workload increases attack surface and can bypass centralized ingress controls.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Prefer private addressing and publish only through a controlled load balancer, application gateway, firewall, or bastion.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkInterfaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"ipConfigurations\":[{\"name\":\"ipconfig\",\"properties\":{\"privateIPAllocationMethod\":\"Dynamic\"}}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkInterfaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"ipConfigurations\":[{\"name\":\"ipconfig\",\"properties\":{\"publicIPAddress\":{\"id\":\"[resourceId('Microsoft.Network/publicIPAddresses','pip')]\"}}}]}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-aks-rbac-disabled", Name: "AKS role-based access control is disabled", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "aks", "authorization"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An AKS managed cluster explicitly disables Kubernetes role-based access control.",
			Rationale:           "Without RBAC, Kubernetes API authorization cannot enforce least-privilege roles for users and workloads.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set enableRBAC to true and grant narrowly scoped Azure and Kubernetes roles.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.ContainerService/managedClusters\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enableRBAC\":true}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.ContainerService/managedClusters\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enableRBAC\":false}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-keyvault-public-network", Name: "Key Vault allows public network access", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "key-vault", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Key Vault explicitly allows public network access or permits traffic by default in its network ACLs.",
			Rationale:           "A publicly reachable vault is exposed to internet-originated authentication attacks and weakens network-layer defense in depth.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set publicNetworkAccess to Disabled and use private endpoints, or configure a deny-by-default network ACL with explicit exceptions.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Disabled\",\"networkAcls\":{\"defaultAction\":\"Deny\"}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Enabled\",\"networkAcls\":{\"defaultAction\":\"Allow\"}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-storage-public-network", Name: "Storage account allows public network access", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "storage", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Storage account explicitly allows public network access or uses an allow-by-default network ACL.",
			Rationale:           "Public reachability increases the chance that leaked credentials or overly broad SAS tokens can be abused from anywhere.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Disable public network access or use private endpoints and a deny-by-default network ACL.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Disabled\",\"networkAcls\":{\"defaultAction\":\"Deny\"}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Enabled\",\"networkAcls\":{\"defaultAction\":\"Allow\"}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-sql-public-network", Name: "SQL server allows public network access", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "sql", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure SQL logical server explicitly enables public network access.",
			Rationale:           "A public database endpoint is reachable from the internet and is exposed to password attacks and exploitation attempts.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set publicNetworkAccess to Disabled and connect through private endpoints.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Disabled\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Enabled\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-webapp-public-network", Name: "Web app allows public network access", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "app-service", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure App Service application explicitly enables public network access.",
			Rationale:           "Public reachability may be intentional, but it should be reviewed because it exposes the application directly to internet traffic.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Disable public network access for internal applications or place the application behind an approved ingress service and web application firewall.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Disabled\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicNetworkAccess\":\"Enabled\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-storage-https-only-off", Name: "Storage account permits insecure HTTP traffic", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "storage", "tls"}, CWE: []string{"CWE-319"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Storage account explicitly permits non-TLS HTTP requests.",
			Rationale:           "HTTP transmits request metadata and data without transport encryption, allowing interception and modification on untrusted networks.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set supportsHttpsTrafficOnly to true.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"supportsHttpsTrafficOnly\":true}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"supportsHttpsTrafficOnly\":false}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-storage-min-tls-below-12", Name: "Storage account permits TLS below 1.2", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "storage", "tls"}, CWE: []string{"CWE-326"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Storage account configures a minimum TLS version older than TLS 1.2.",
			Rationale:           "Legacy TLS versions have weaker protocol protections and are prohibited by many security baselines.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set minimumTlsVersion to TLS1_2 or a newer supported value.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"minimumTlsVersion\":\"TLS1_2\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"minimumTlsVersion\":\"TLS1_0\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-sql-min-tls-below-12", Name: "SQL server permits TLS below 1.2", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "sql", "tls"}, CWE: []string{"CWE-326"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure SQL logical server configures a minimum TLS version older than 1.2.",
			Rationale:           "Allowing legacy TLS exposes database connections to obsolete protocol behavior and may violate compliance requirements.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set minimalTlsVersion to 1.2 or newer.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"minimalTlsVersion\":\"1.2\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"minimalTlsVersion\":\"1.0\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-webapp-min-tls-below-12", Name: "Web app permits TLS below 1.2", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "app-service", "tls"}, CWE: []string{"CWE-326"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure App Service application allows incoming TLS versions older than 1.2.",
			Rationale:           "Legacy TLS weakens transport security for application users and integrations.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set siteConfig.minTlsVersion to 1.2 or newer.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"siteConfig\":{\"minTlsVersion\":\"1.2\"}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"siteConfig\":{\"minTlsVersion\":\"1.0\"}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-sql-tde-disabled", Name: "SQL transparent data encryption is disabled", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "sql", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure SQL transparent data encryption resource explicitly sets its status to Disabled.",
			Rationale:           "Disabling transparent data encryption leaves database files and backups without the expected at-rest encryption control.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set the transparent data encryption status to Enabled.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers/databases/transparentDataEncryption\",\"apiVersion\":\"2023-01-01\",\"name\":\"server/db/current\",\"properties\":{\"status\":\"Enabled\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers/databases/transparentDataEncryption\",\"apiVersion\":\"2023-01-01\",\"name\":\"server/db/current\",\"properties\":{\"status\":\"Disabled\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-vm-encryption-at-host-disabled", Name: "Virtual machine host encryption is not enabled", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "virtual-machine", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure virtual machine does not enable encryption at host.",
			Rationale:           "Without host encryption, temporary disks and host-side caches may not receive the additional encryption layer required by policy.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set securityProfile.encryptionAtHost to true on supported virtual machine sizes and regions.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Compute/virtualMachines\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityProfile\":{\"encryptionAtHost\":true}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Compute/virtualMachines\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityProfile\":{\"encryptionAtHost\":false}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-storage-infrastructure-encryption-disabled", Name: "Storage infrastructure encryption is not enabled", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "storage", "encryption"}, CWE: []string{"CWE-311"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Storage account does not require infrastructure encryption.",
			Rationale:           "Infrastructure encryption adds a second independent encryption layer for organizations with stronger data-at-rest requirements.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set encryption.requireInfrastructureEncryption to true where the account type and region support it.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"encryption\":{\"requireInfrastructureEncryption\":true}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"encryption\":{\"requireInfrastructureEncryption\":false}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-keyvault-purge-protection-disabled", Name: "Key Vault purge protection is not enabled", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "key-vault", "data-protection"}, CWE: []string{"CWE-693"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Key Vault does not enable purge protection.",
			Rationale:           "Without purge protection, a privileged actor can permanently remove a soft-deleted vault or secret before the retention period expires.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Set enablePurgeProtection to true and verify the retention period matches recovery requirements.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enablePurgeProtection\":true}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enablePurgeProtection\":false}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-hardcoded-secret", Name: "Hardcoded secret in ARM template", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "credentials", "secret"}, CWE: []string{"CWE-798"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionAST,
			Description:         "An ARM secure parameter or secret-like resource property contains a plaintext literal.",
			Rationale:           "Secrets committed in deployment templates are exposed to source readers, build logs, deployment history, and template exports.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove plaintext values and retrieve secrets from Key Vault through secure deployment parameters or service-native references.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"adminPassword\":{\"type\":\"secureString\",\"metadata\":{\"description\":\"Administrator password\"}}},\"resources\":[]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"adminPassword\":{\"type\":\"secureString\",\"defaultValue\":\"SuperSecret123!\",\"metadata\":{\"description\":\"Administrator password\"}}},\"resources\":[]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-secret-in-output", Name: "ARM output may expose secret material", Language: "Azure Resource Manager",
			Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityHigh,
			Tags: []string{"azure", "credentials", "output"}, CWE: []string{"CWE-200"}, OWASP: []string{"A02:2021"}, Detection: rule.DetectionAST,
			Description:         "An ARM output is secret-like or evaluates a function that returns key material.",
			Rationale:           "Deployment outputs can be recorded in logs, automation systems, and deployment history, making them unsafe for secrets.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices#outputs",
			Remediation:         "Remove the sensitive output and pass the secret directly to its consumer through Key Vault or a protected identity flow.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[],\"outputs\":{\"endpoint\":{\"type\":\"string\",\"value\":\"https://example.invalid\"}}}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[],\"outputs\":{\"storageKey\":{\"type\":\"string\",\"value\":\"[listKeys(resourceId('Microsoft.Storage/storageAccounts','s'),'2023-01-01').keys[0].value]\"}}}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-no-diagnostic-settings", Name: "Resource has no diagnostic settings", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow,
			Tags: []string{"azure", "logging", "monitoring"}, CWE: []string{"CWE-778"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A sensitive Azure resource has no diagnostic settings resource scoped to it.",
			Rationale:           "Without platform logs and metrics, suspicious access and configuration changes may not be visible to responders.\n\nSource: https://learn.microsoft.com/azure/azure-monitor/essentials/diagnostic-settings",
			Remediation:         "Create Microsoft.Insights/diagnosticSettings for the resource and route relevant logs and metrics to a monitored destination.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"vaultprod\",\"properties\":{\"publicNetworkAccess\":\"Disabled\"}},{\"type\":\"Microsoft.Insights/diagnosticSettings\",\"apiVersion\":\"2023-01-01\",\"name\":\"diag\",\"scope\":\"[resourceId('Microsoft.KeyVault/vaults','vaultprod')]\",\"properties\":{\"logs\":[{\"category\":\"AuditEvent\",\"enabled\":true}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"vaultprod\",\"properties\":{\"publicNetworkAccess\":\"Disabled\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-diagnostic-logs-disabled", Name: "Diagnostic setting has no enabled log categories", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow,
			Tags: []string{"azure", "logging", "monitoring"}, CWE: []string{"CWE-778"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure diagnostic setting contains no enabled log category.",
			Rationale:           "A diagnostic setting that records no logs can create a false sense of monitoring coverage while retaining little forensic evidence.\n\nSource: https://learn.microsoft.com/azure/azure-monitor/essentials/diagnostic-settings",
			Remediation:         "Enable the relevant log categories or category groups and route them to an approved destination.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Insights/diagnosticSettings\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"logs\":[{\"category\":\"AuditEvent\",\"enabled\":true}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Insights/diagnosticSettings\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"logs\":[{\"category\":\"AuditEvent\",\"enabled\":false}]}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-sql-auditing-disabled", Name: "SQL auditing is disabled", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "sql", "logging"}, CWE: []string{"CWE-778"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure SQL auditing settings resource explicitly disables auditing.",
			Rationale:           "Disabled auditing removes an important record of authentication, authorization, and data-access activity.\n\nSource: https://learn.microsoft.com/azure/azure-sql/database/auditing-overview",
			Remediation:         "Set the auditing state to Enabled and send events to a protected Log Analytics workspace, Event Hub, or storage account.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers/auditingSettings\",\"apiVersion\":\"2023-01-01\",\"name\":\"server/default\",\"properties\":{\"state\":\"Enabled\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Sql/servers/auditingSettings\",\"apiVersion\":\"2023-01-01\",\"name\":\"server/default\",\"properties\":{\"state\":\"Disabled\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-defender-pricing-free", Name: "Microsoft Defender plan uses the Free tier", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow,
			Tags: []string{"azure", "defender", "monitoring"}, CWE: []string{"CWE-693"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A Microsoft Defender for Cloud pricing resource selects the Free tier.",
			Rationale:           "The Free tier omits advanced workload protections and alerting that may be required for production resource types.\n\nSource: https://learn.microsoft.com/azure/defender-for-cloud/enhanced-security-features-overview",
			Remediation:         "Review the workload risk and use the Standard tier where the organization requires Defender protections.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Security/pricings\",\"apiVersion\":\"2023-01-01\",\"name\":\"VirtualMachines\",\"properties\":{\"pricingTier\":\"Standard\"}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Security/pricings\",\"apiVersion\":\"2023-01-01\",\"name\":\"VirtualMachines\",\"properties\":{\"pricingTier\":\"Free\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-keyvault-rbac-disabled", Name: "Key Vault Azure RBAC authorization is not enabled", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "key-vault", "authorization"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure Key Vault does not enable the Azure RBAC authorization model.",
			Rationale:           "Legacy access policies are harder to govern consistently across subscriptions and can permit direct self-escalation in some operating models.\n\nSource: https://learn.microsoft.com/azure/key-vault/general/rbac-guide",
			Remediation:         "Set enableRbacAuthorization to true and assign narrowly scoped built-in or custom roles.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enableRbacAuthorization\":true}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.KeyVault/vaults\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"enableRbacAuthorization\":false}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-managed-identity-missing", Name: "Resource has no managed identity", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow,
			Tags: []string{"azure", "identity", "credentials"}, CWE: []string{"CWE-798"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "A supported Azure compute or application resource declares no managed identity.",
			Rationale:           "Without a managed identity, applications are more likely to rely on long-lived client secrets or account keys.\n\nSource: https://learn.microsoft.com/entra/identity/managed-identities-azure-resources/overview",
			Remediation:         "Enable a system-assigned or user-assigned managed identity and authorize it with least-privilege roles.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"identity\":{\"type\":\"SystemAssigned\"},\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Web/sites\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-nsg-open-egress", Name: "Network security rule allows internet-wide outbound access", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "network", "firewall"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An Azure network security group contains an Allow outbound rule whose destination covers the entire internet.",
			Rationale:           "Unrestricted egress allows compromised workloads to contact arbitrary command-and-control endpoints and exfiltrate data.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Restrict destination prefixes and ports to the services the workload requires.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkSecurityGroups\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityRules\":[{\"name\":\"dns\",\"properties\":{\"direction\":\"Outbound\",\"access\":\"Allow\",\"destinationAddressPrefix\":\"10.0.0.4\",\"destinationPortRange\":\"53\"}}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkSecurityGroups\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"securityRules\":[{\"name\":\"allout\",\"properties\":{\"direction\":\"Outbound\",\"access\":\"Allow\",\"destinationAddressPrefix\":\"*\",\"destinationPortRange\":\"*\"}}]}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-public-ip-resource", Name: "Public IP address resource requires review", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityLow,
			Tags: []string{"azure", "network", "public-access"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "The ARM template provisions an Azure Public IP address resource.",
			Rationale:           "Public IP resources create internet-reachable entry points and should exist only when the exposure is intentional and controlled.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Prefer private connectivity; when a public IP is required, protect it with a firewall, narrow network rules, and monitoring.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/networkInterfaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"ipConfigurations\":[{\"name\":\"private\",\"properties\":{\"privateIPAllocationMethod\":\"Dynamic\"}}]}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Network/publicIPAddresses\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"publicIPAllocationMethod\":\"Static\"}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-aks-private-cluster-disabled", Name: "AKS API server is not private", Language: "Azure Resource Manager",
			Type: rule.TypeSecurityHotspot, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityMedium,
			Tags: []string{"azure", "aks", "network"}, CWE: []string{"CWE-284"}, OWASP: []string{"A05:2021"}, Detection: rule.DetectionAST,
			Description:         "An AKS cluster does not enable a private API server.",
			Rationale:           "A public Kubernetes control-plane endpoint is exposed to internet scanning and authentication attacks.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Enable apiServerAccessProfile.enablePrivateCluster or restrict authorized IP ranges to trusted administration networks.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.ContainerService/managedClusters\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"apiServerAccessProfile\":{\"enablePrivateCluster\":true}}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.ContainerService/managedClusters\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{\"apiServerAccessProfile\":{\"enablePrivateCluster\":false}}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-location-hardcoded", Name: "Resource location is hardcoded", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "portability", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM resource uses a fixed region literal instead of a deployment expression or parameter.",
			Rationale:           "Hardcoded locations make templates difficult to reuse across environments and can create inconsistent regional placement.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Use resourceGroup().location or a documented location parameter.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"location\":\"[resourceGroup().location]\",\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"location\":\"eastus\",\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-apiversion-old", Name: "Resource uses a very old API version", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "api-version", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM resource uses an API version dated before 2020.",
			Rationale:           "Very old API versions can retain obsolete defaults, omit current security properties, and become unsupported.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Select a supported stable API version and test the deployment for property or default changes.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2017-04-01\",\"name\":\"example\",\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-missing-tags", Name: "Resource has no governance tags", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "tags", "governance"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "A taggable top-level ARM resource declares no tags.",
			Rationale:           "Missing ownership, environment, and cost metadata makes operational governance and inventory management harder.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Add the organization-required tags, such as owner, environment, cost-center, and data-classification.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"tags\":{\"owner\":\"platform\",\"environment\":\"prod\"},\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-unused-parameter", Name: "Unused ARM parameter", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "parameter", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM template parameter is declared but never referenced.",
			Rationale:           "Unused parameters enlarge the deployment contract and confuse operators about which values affect the resulting resources.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Remove the parameter or reference it from the intended resource property.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"region\":{\"type\":\"string\",\"metadata\":{\"description\":\"Deployment region\"}}},\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"location\":\"[parameters('region')]\",\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"region\":{\"type\":\"string\",\"metadata\":{\"description\":\"Deployment region\"}}},\"resources\":[]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-unused-variable", Name: "Unused ARM variable", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "variable", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM template variable is declared but never referenced.",
			Rationale:           "Unused variables preserve dead configuration and make template intent harder to understand.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Remove the variable or reference it from the intended expression.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"variables\":{\"prefix\":\"app\"},\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"[variables('prefix')]\",\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"variables\":{\"prefix\":\"app\"},\"resources\":[]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-dependson-literal-id", Name: "dependsOn contains a literal resource identifier", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "dependency", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM dependsOn entry uses a literal identifier instead of an expression.",
			Rationale:           "Literal dependency identifiers are fragile when resource names, scopes, or parent relationships change.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Build dependency identifiers with resourceId(), subscriptionResourceId(), or the appropriate scope-aware function.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"dependsOn\":[\"[resourceId('Microsoft.Storage/storageAccounts','s')]\"],\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.EventHub/namespaces\",\"apiVersion\":\"2023-01-01\",\"name\":\"example\",\"dependsOn\":[\"/subscriptions/000/resourceGroups/rg/providers/Microsoft.Storage/storageAccounts/s\"],\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-resource-name-hardcoded", Name: "Globally scoped resource name is hardcoded", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "naming", "maintainability"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "A globally scoped Azure resource uses a fixed literal name.",
			Rationale:           "Fixed global names frequently collide between subscriptions, environments, or repeated test deployments.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Derive the name from a stable prefix plus uniqueString() or an explicit deployment parameter.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"[concat('company',uniqueString(resourceGroup().id))]\",\"properties\":{}}]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"type\":\"Microsoft.Storage/storageAccounts\",\"apiVersion\":\"2023-01-01\",\"name\":\"companyprodstore\",\"properties\":{}}]}",
			RemediationEffort:   15,
		},
		{
			Key: "arm-parameter-missing-description", Name: "ARM parameter has no description", Language: "Azure Resource Manager",
			Type: rule.TypeCodeSmell, Qualities: []rule.Quality{rule.QualityMaintainability}, DefaultSeverity: shared.SeverityInfo,
			Tags: []string{"azure", "parameter", "documentation"}, CWE: nil, OWASP: nil, Detection: rule.DetectionAST,
			Description:         "An ARM template parameter has no metadata description.",
			Rationale:           "Undocumented parameters make deployments error-prone because operators cannot see the expected purpose, format, or sensitivity.\n\nSource: https://learn.microsoft.com/azure/azure-resource-manager/templates/best-practices",
			Remediation:         "Add metadata.description with the parameter purpose, accepted form, and security considerations.",
			CompliantExample:    "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"environment\":{\"type\":\"string\",\"metadata\":{\"description\":\"Deployment environment name\"}}},\"resources\":[]}",
			NoncompliantExample: "{\"$schema\":\"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"environment\":{\"type\":\"string\"}},\"resources\":[]}",
			RemediationEffort:   15,
		},
	}
}
