package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

var htmlSecurityRules = []rule.Rule{
	{
		Key:                 "html:target-blank-noopener",
		Name:                "target=\"_blank\" without noopener or noreferrer",
		Language:            "HTML",
		Type:                rule.TypeVulnerability,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityMedium,
		Tags:                []string{"html", "security", "reverse-tabnabbing"},
		CWE:                 []string{"CWE-1022"},
		OWASP:               []string{},
		Description:         "Detects links or forms opening in a new tab via target=\"_blank\" without specifying noopener or noreferrer in the rel attribute.",
		Rationale:           "Opening a document in a new window or tab with target=\"_blank\" allows the opened page to access window.opener, exposing your site to reverse tabnabbing attacks.\n\nSource: https://html.spec.whatwg.org/multipage/links.html#link-type-noopener",
		Remediation:         "Add rel=\"noopener\" or rel=\"noreferrer\" to the element.",
		CompliantExample:    "<a href=\"https://example.com\" target=\"_blank\" rel=\"noopener\">Link</a>",
		NoncompliantExample: "<a href=\"https://example.com\" target=\"_blank\">Link</a>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:inline-event-handler",
		Name:                "Inline event handler attribute",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityMedium,
		Tags:                []string{"html", "security", "xss"},
		CWE:                 []string{"CWE-79"},
		OWASP:               []string{},
		Description:         "Detects inline event handler attributes such as onclick or onload containing executable JavaScript.",
		Rationale:           "Inline event handlers mix presentation with executable logic, hinder Content Security Policy (CSP) enforcement, and increase risk of Cross-Site Scripting (XSS).\n\nSource: https://www.w3.org/TR/CSP3/",
		Remediation:         "Remove inline event handler attributes and attach event listeners using external JavaScript scripts.",
		CompliantExample:    "<button id=\"btn\">Click</button>",
		NoncompliantExample: "<button onclick=\"doSomething()\">Click</button>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:javascript-url",
		Name:                "javascript: pseudo-protocol URL attribute",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityHigh,
		Tags:                []string{"html", "security", "xss"},
		CWE:                 []string{"CWE-79"},
		OWASP:               []string{},
		Description:         "Detects URL attributes (e.g. href, src, action) using the javascript: pseudo-protocol scheme.",
		Rationale:           "Using javascript: URLs allows arbitrary script execution when triggered, circumventing standard script context controls and contributing to XSS vulnerabilities.\n\nSource: https://cwe.mitre.org/data/definitions/79.html",
		Remediation:         "Replace javascript: URLs with proper HTTP/HTTPS URLs or standard event handlers attached via external scripts.",
		CompliantExample:    "<a href=\"/profile\">Profile</a>",
		NoncompliantExample: "<a href=\"javascript:alert(1)\">Click</a>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:iframe-sandbox-missing",
		Name:                "Missing iframe sandbox attribute",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityMedium,
		Tags:                []string{"html", "security", "iframe"},
		CWE:                 []string{"CWE-693"},
		OWASP:               []string{},
		Description:         "Detects iframe elements with active content sources (src or srcdoc) that lack a sandbox attribute.",
		Rationale:           "Embedded iframe content without a sandbox attribute executes with full permissions of the frame, posing risks of unwanted script execution or form submission.\n\nSource: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox",
		Remediation:         "Add a sandbox attribute to the iframe element with minimum necessary permissions.",
		CompliantExample:    "<iframe src=\"https://example.com\" sandbox></iframe>",
		NoncompliantExample: "<iframe src=\"https://example.com\"></iframe>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:iframe-sandbox-escape",
		Name:                "iframe sandbox allow-scripts and allow-same-origin escape combination",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityHigh,
		Tags:                []string{"html", "security", "iframe"},
		CWE:                 []string{"CWE-693"},
		OWASP:               []string{},
		Description:         "Detects iframe sandbox attributes combining both allow-scripts and allow-same-origin directives.",
		Rationale:           "Combining allow-scripts and allow-same-origin in an iframe sandbox attribute allows the framed document to remove its sandbox restrictions programmatically.\n\nSource: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox",
		Remediation:         "Do not combine allow-scripts and allow-same-origin on the same iframe element.",
		CompliantExample:    "<iframe src=\"page.html\" sandbox=\"allow-scripts\"></iframe>",
		NoncompliantExample: "<iframe src=\"page.html\" sandbox=\"allow-scripts allow-same-origin\"></iframe>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:insecure-form-action",
		Name:                "Insecure HTTP form action URL",
		Language:            "HTML",
		Type:                rule.TypeVulnerability,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityMedium,
		Tags:                []string{"html", "security", "transport"},
		CWE:                 []string{"CWE-319"},
		OWASP:               []string{},
		Description:         "Detects forms or form submission controls that send user data over unencrypted HTTP protocol.",
		Rationale:           "Submitting forms over cleartext HTTP exposes sensitive user inputs and data to interception and tampering by network adversaries.\n\nSource: https://www.w3.org/TR/mixed-content/",
		Remediation:         "Use secure HTTPS URLs for form action and formaction attributes.",
		CompliantExample:    "<form action=\"https://example.com/submit\"></form>",
		NoncompliantExample: "<form action=\"http://example.com/submit\"></form>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:active-content-over-http",
		Name:                "Active network content loaded over HTTP",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityHigh,
		Tags:                []string{"html", "security", "mixed-content"},
		CWE:                 []string{"CWE-319"},
		OWASP:               []string{},
		Description:         "Detects active resources (scripts, iframes, objects, embeds, stylesheets) loaded via unencrypted HTTP.",
		Rationale:           "Loading active resources over plain HTTP allows man-in-the-middle attackers to inject malicious script or alter styling and document behavior.\n\nSource: https://www.w3.org/TR/mixed-content/",
		Remediation:         "Change active resource URLs to use HTTPS protocol.",
		CompliantExample:    "<script src=\"https://cdn.example.com/lib.js\"></script>",
		NoncompliantExample: "<script src=\"http://cdn.example.com/lib.js\"></script>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "html:external-resource-no-integrity",
		Name:                "External script or stylesheet missing Subresource Integrity (SRI)",
		Language:            "HTML",
		Type:                rule.TypeSecurityHotspot,
		Qualities:           []rule.Quality{rule.QualitySecurity},
		DefaultSeverity:     shared.SeverityMedium,
		Tags:                []string{"html", "security", "sri"},
		CWE:                 []string{"CWE-353"},
		OWASP:               []string{},
		Description:         "Detects absolute HTTP or HTTPS external scripts and stylesheets that lack a valid non-empty integrity attribute.",
		Rationale:           "Loading external scripts or stylesheets without Subresource Integrity (SRI) hashes leaves applications vulnerable to third-party CDN compromises.\n\nSource: https://www.w3.org/TR/SRI/",
		Remediation:         "Add an integrity attribute containing cryptographic hash digests for external scripts and stylesheets.",
		CompliantExample:    "<script src=\"https://example.com/app.js\" integrity=\"sha384-xyz...\"></script>",
		NoncompliantExample: "<script src=\"https://example.com/app.js\"></script>",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
}
