package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func htmlRules() []rule.Rule {
	return append([]rule.Rule{
		{
			Key:                 "html:doctype-missing",
			Name:                "Missing HTML DOCTYPE declaration",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "doctype"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects full HTML documents that do not include a DOCTYPE declaration at the start.",
			Rationale:           "A DOCTYPE declaration is required at the beginning of an HTML document to inform the browser to render in standards mode instead of quirks mode.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#the-doctype",
			Remediation:         "Add <!DOCTYPE html> at the very beginning of the HTML document.",
			CompliantExample:    "<!DOCTYPE html>\n<html>\n<head><title>Test</title></head>\n<body></body>\n</html>",
			NoncompliantExample: "<html>\n<head><title>Test</title></head>\n<body></body>\n</html>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:doctype-invalid",
			Name:                "Invalid, misplaced, or duplicate DOCTYPE declaration",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "doctype"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects DOCTYPE declarations that are misplaced, duplicated, malformed, or specify a document type other than html.",
			Rationale:           "The DOCTYPE declaration must appear before any HTML elements, must specify html as the root element name, and must not be duplicated.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#the-doctype",
			Remediation:         "Ensure exactly one valid <!DOCTYPE html> declaration is placed before any HTML element.",
			CompliantExample:    "<!DOCTYPE html>\n<html></html>",
			NoncompliantExample: "<html></html>\n<!DOCTYPE html>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:duplicate-attribute",
			Name:                "Duplicate attribute on HTML element",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "attribute"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects elements that contain multiple attributes with the same name.",
			Rationale:           "Duplicate attribute names on a single HTML tag are invalid according to the HTML specification and can lead to unpredictable attribute value resolution.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#attributes-2",
			Remediation:         "Remove the duplicate attribute specification or combine their values appropriately.",
			CompliantExample:    "<div class=\"a b\"></div>",
			NoncompliantExample: "<div class=\"a\" class=\"b\"></div>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:duplicate-id",
			Name:                "Duplicate ID in HTML document",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "id"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects multiple elements in an HTML document sharing the same literal id attribute value.",
			Rationale:           "Element IDs must be unique within an HTML document to ensure proper DOM element selection, CSS styling, and fragment identification.\n\nSource: https://html.spec.whatwg.org/dev/dom.html#the-id-attribute",
			Remediation:         "Assign a unique ID value to each element in the document.",
			CompliantExample:    "<div id=\"header\"></div>\n<div id=\"footer\"></div>",
			NoncompliantExample: "<div id=\"item\"></div>\n<span id=\"item\"></span>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:invalid-id",
			Name:                "Invalid HTML element ID",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "id"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects id attribute values that are empty or contain ASCII whitespace.",
			Rationale:           "An HTML element ID must contain at least one character and must not contain any HTML ASCII whitespace characters.\n\nSource: https://html.spec.whatwg.org/dev/dom.html#the-id-attribute",
			Remediation:         "Remove whitespace from the ID value or provide a non-empty, valid identifier.",
			CompliantExample:    "<div id=\"main-content\"></div>",
			NoncompliantExample: "<div id=\"main content\"></div>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:unclosed-tag",
			Name:                "Unclosed HTML element",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"html", "correctness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects non-void HTML elements that require an explicit matching end tag but are left unclosed.",
			Rationale:           "Non-void HTML elements without an explicit end tag cause unintended DOM hierarchy nesting and layout errors.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#elements-2",
			Remediation:         "Add a matching closing tag for the unclosed element.",
			CompliantExample:    "<div><p>Content</p></div>",
			NoncompliantExample: "<div><p>Content</div>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:unexpected-end-tag",
			Name:                "Unexpected HTML end tag",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"html", "correctness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects end tags that do not match any open element or are specified for void elements.",
			Rationale:           "End tags that do not match an open element or are used on void elements are invalid syntax and trigger parser errors.\n\nSource: https://html.spec.whatwg.org/multipage/parsing.html#parse-errors",
			Remediation:         "Remove the orphaned or invalid end tag.",
			CompliantExample:    "<img src=\"icon.png\">\n<div>Text</div>",
			NoncompliantExample: "<img src=\"icon.png\"></img>\n</div>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:nonvoid-self-closing",
			Name:                "Self-closing syntax on non-void HTML element",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"html", "correctness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects self-closing trailing slashes on non-void HTML elements outside foreign content.",
			Rationale:           "In HTML syntax, self-closing slashes (/>) are only meaningful on void elements or SVG/MathML elements; on non-void HTML elements they are ignored by standard parsers, often causing misnested trees.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#start-tags",
			Remediation:         "Use explicit closing tags (<tag></tag>) for non-void HTML elements.",
			CompliantExample:    "<div></div>\n<img />",
			NoncompliantExample: "<div />\n<span />",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:nested-form",
			Name:                "Nested HTML form element",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"html", "correctness", "form"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects a form element nested inside another form element.",
			Rationale:           "The HTML specification explicitly prohibits nesting a form element inside another form element because nested forms lead to broken form control registration and submission behavior.\n\nSource: https://html.spec.whatwg.org/multipage/forms.html#the-form-element",
			Remediation:         "Separate nested forms into sibling form elements.",
			CompliantExample:    "<form id=\"form1\"></form>\n<form id=\"form2\"></form>",
			NoncompliantExample: "<form id=\"form1\">\n  <form id=\"form2\"></form>\n</form>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "html:duplicate-document-element",
			Name:                "Duplicate explicit document element",
			Language:            "HTML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"html", "correctness", "structure"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects multiple explicit html, head, or body structural elements in a single document.",
			Rationale:           "An HTML document can only contain one instance of each structural element (html, head, body). Duplicating them results in malformed document structure.\n\nSource: https://html.spec.whatwg.org/dev/syntax.html#writing-html-documents",
			Remediation:         "Combine structural content under a single html, head, or body element.",
			CompliantExample:    "<html>\n<head></head>\n<body></body>\n</html>",
			NoncompliantExample: "<html></html>\n<html></html>",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
	}, htmlSecurityRules...)
}
