package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func htmlMaintainabilityRule(
	key, name string,
	severity shared.Severity,
	description, rationale, source, remediation, compliant, noncompliant string,
) rule.Rule {
	return rule.Rule{
		Key:                 rule.Key("html:" + key),
		Name:                name,
		Language:            "HTML",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     severity,
		Tags:                []string{"html", "maintainability", "accessibility"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         description,
		Rationale:           rationale + "\n\nSource: " + source,
		Remediation:         remediation,
		CompliantExample:    compliant,
		NoncompliantExample: noncompliant,
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	}
}

var htmlMaintainabilityRules = []rule.Rule{
	htmlMaintainabilityRule(
		"img-alt-missing", "Image is missing an alt attribute", shared.SeverityMedium,
		"Detects visible img elements that omit the alt attribute.",
		"Alternative text gives non-visual users an equivalent for image content, while an explicit empty alt marks decoration.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H37",
		"Add an alt attribute containing a concise equivalent, or alt=\"\" for a decorative image.",
		`<img src="chart.png" alt="Quarterly revenue increased">`,
		`<img src="chart.png">`,
	),
	htmlMaintainabilityRule(
		"area-alt-missing", "Image map area is missing alternative text", shared.SeverityMedium,
		"Detects linked area elements without meaningful alt text.",
		"Each active image-map region needs a text alternative so its destination can be understood without the image.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H24",
		"Describe the linked region in the area element's alt attribute.",
		`<area href="/offices" alt="Office locations">`,
		`<area href="/offices" alt="">`,
	),
	htmlMaintainabilityRule(
		"input-image-alt-missing", "Image input is missing alternative text", shared.SeverityMedium,
		"Detects input elements with type=image that have no meaningful alt text.",
		"An image submit control needs a text label that communicates the action when the image cannot be perceived.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H36",
		"Add an alt attribute that names the image button's action.",
		`<input type="image" src="search.png" alt="Search">`,
		`<input type="image" src="search.png">`,
	),
	htmlMaintainabilityRule(
		"object-fallback-missing", "Object element has no fallback content", shared.SeverityMedium,
		"Detects object elements without meaningful fallback text or content.",
		"Fallback content keeps embedded information understandable when the external resource cannot be rendered.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H53",
		"Place meaningful text or an alternative element inside the object.",
		`<object data="report.pdf"><a href="report.pdf">Download the report</a></object>`,
		`<object data="report.pdf"><param name="page" value="1"></object>`,
	),
	htmlMaintainabilityRule(
		"iframe-title-missing", "Iframe is missing an accessible title", shared.SeverityMedium,
		"Detects iframe elements without a title or supported ARIA name.",
		"A concise frame name lets users distinguish embedded regions and decide whether to navigate into them.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H64",
		"Add a non-empty title, aria-label, or resolvable aria-labelledby attribute.",
		`<iframe src="/weather" title="Local weather"></iframe>`,
		`<iframe src="/weather"></iframe>`,
	),
	htmlMaintainabilityRule(
		"html-title-missing", "HTML document is missing a meaningful title", shared.SeverityMedium,
		"Detects full HTML documents without meaningful title text directly under head.",
		"A document title identifies the page in browser tabs, history, bookmarks, and assistive-technology navigation.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H25",
		"Add one meaningful title element as a child of head.",
		`<html lang="en"><head><title>Account settings</title></head><body><main></main></body></html>`,
		`<html lang="en"><head></head><body><main></main></body></html>`,
	),
	htmlMaintainabilityRule(
		"missing-lang", "HTML document is missing a language", shared.SeverityLow,
		"Detects explicit root html elements without a meaningful lang attribute.",
		"Declaring the document language helps pronunciation, translation, spell checking, and language-specific rendering.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H57",
		"Set lang on the root html element to the document's primary language.",
		`<html lang="en"><head><title>Home</title></head><body><main></main></body></html>`,
		`<html><head><title>Home</title></head><body><main></main></body></html>`,
	),
	htmlMaintainabilityRule(
		"label-missing", "Form control is missing an accessible label", shared.SeverityMedium,
		"Detects text-entry and selection controls without a supported accessible label.",
		"Persistent labels communicate the purpose of form controls and remain available after a value is entered.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/e086e5/",
		"Associate a label element or provide a meaningful supported ARIA label.",
		`<label for="email">Email</label><input id="email" type="email">`,
		`<input type="email" placeholder="Email">`,
	),
	htmlMaintainabilityRule(
		"button-name-missing", "Button is missing an accessible name", shared.SeverityMedium,
		"Detects native and ARIA buttons without a supported static accessible name.",
		"A button name communicates the action to screen-reader and voice-control users.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/97a4e1/; https://www.w3.org/TR/accname-1.2/",
		"Add visible text or a supported ARIA label that describes the action.",
		`<button type="button">Save changes</button>`,
		`<button type="button"><span aria-hidden="true">✓</span></button>`,
	),
	htmlMaintainabilityRule(
		"link-name-missing", "Link is missing an accessible name", shared.SeverityMedium,
		"Detects native and ARIA links without a supported static accessible name.",
		"Meaningful link names allow users to understand destinations when links are listed outside surrounding context.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/c487ae/; https://www.w3.org/TR/html-aam-1.0/",
		"Provide visible link text, alternative image text, or another supported accessible name.",
		`<a href="/billing">Billing settings</a>`,
		`<a href="/billing"></a>`,
	),
	htmlMaintainabilityRule(
		"fieldset-legend-missing", "Fieldset is missing a meaningful legend", shared.SeverityMedium,
		"Detects fieldsets grouping multiple controls without a first-child legend or ARIA name.",
		"A legend describes the relationship among grouped form controls and is announced with each control.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H71",
		"Place a meaningful legend as the fieldset's first element child.",
		`<fieldset><legend>Contact preference</legend><input aria-label="Email"><input aria-label="Phone"></fieldset>`,
		`<fieldset><input aria-label="Email"><input aria-label="Phone"></fieldset>`,
	),
	htmlMaintainabilityRule(
		"table-caption-missing", "Data table is missing a caption", shared.SeverityLow,
		"Detects data tables without a meaningful caption or supported ARIA name.",
		"A table caption summarizes the table's purpose before users navigate its rows and columns.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H39",
		"Add a meaningful caption as a direct child of the table.",
		`<table><caption>Monthly expenses</caption><tr><th>Month</th></tr></table>`,
		`<table><tr><th>Month</th></tr></table>`,
	),
	htmlMaintainabilityRule(
		"table-header-reference-missing", "Table header reference does not resolve", shared.SeverityMedium,
		"Detects headers attributes that are empty or reference a missing th in another table.",
		"Correct header relationships let assistive technology announce the context of complex table cells.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H43",
		"Reference existing th IDs from the same nearest table.",
		`<table><tr><th id="name">Name</th></tr><tr><td headers="name">Ada</td></tr></table>`,
		`<table><tr><td headers="missing">Ada</td></tr></table>`,
	),
	htmlMaintainabilityRule(
		"heading-empty", "Heading has no accessible name", shared.SeverityMedium,
		"Detects visible native and ARIA headings without meaningful accessible text.",
		"Headings form a navigable outline only when each heading communicates the section it introduces.",
		"https://www.w3.org/TR/wai-aria-1.2/#heading",
		"Add meaningful visible text or a supported ARIA name.",
		`<h2>Payment methods</h2>`,
		`<h2><span aria-hidden="true">Section</span></h2>`,
	),
	htmlMaintainabilityRule(
		"heading-order", "Heading level is skipped", shared.SeverityLow,
		"Detects visible headings whose level increases by more than one.",
		"A gradual heading hierarchy makes document structure predictable and easier to navigate.",
		"https://www.w3.org/WAI/WCAG22/Techniques/general/G141",
		"Use the next sequential heading level when introducing a subsection.",
		`<h2>Settings</h2><h3>Notifications</h3>`,
		`<h2>Settings</h2><h4>Notifications</h4>`,
	),
	htmlMaintainabilityRule(
		"main-landmark-missing", "HTML document is missing a main landmark", shared.SeverityLow,
		"Detects full HTML documents without a visible native or ARIA main landmark.",
		"A main landmark provides a direct navigation target for the page's primary content.",
		"https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/",
		"Wrap the primary page content in one visible main landmark.",
		`<html lang="en"><head><title>News</title></head><body><main>Stories</main></body></html>`,
		`<html lang="en"><head><title>News</title></head><body>Stories</body></html>`,
	),
	htmlMaintainabilityRule(
		"duplicate-main-landmark", "Main landmarks need unique accessible names", shared.SeverityLow,
		"Detects second and later visible main landmarks that are unnamed or repeat an earlier main landmark name.",
		"Multiple main landmarks can be distinguished in landmark navigation when every additional landmark has a unique accessible name.",
		"https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/main.html",
		"Keep one visible main landmark, or give each additional main landmark a unique accessible name.",
		`<main aria-label="Primary content"></main><main aria-label="Related content"></main>`,
		`<main aria-label="Content"></main><div role="main" aria-label="Content"></div>`,
	),
	htmlMaintainabilityRule(
		"tabindex-positive", "Positive tabindex overrides natural focus order", shared.SeverityLow,
		"Detects literal tabindex values greater than zero.",
		"Positive tabindex values create a separate focus sequence that is difficult to maintain as the page changes.",
		"https://www.w3.org/WAI/WCAG22/Techniques/html/H4",
		"Use source order and tabindex=\"0\" or tabindex=\"-1\" instead.",
		`<button tabindex="0">Continue</button>`,
		`<button tabindex="3">Continue</button>`,
	),
	htmlMaintainabilityRule(
		"accesskey-used", "Accesskey attribute is used", shared.SeverityLow,
		"Detects non-empty accesskey attributes.",
		"Access keys can conflict with browser, operating-system, localization, and assistive-technology shortcuts.",
		"https://html.spec.whatwg.org/multipage/interaction.html#the-accesskey-attribute; https://html.spec.whatwg.org/",
		"Remove accesskey and provide ordinary keyboard navigation.",
		`<button>Save</button>`,
		`<button accesskey="s">Save</button>`,
	),
	htmlMaintainabilityRule(
		"autofocus-used", "Autofocus attribute is used", shared.SeverityLow,
		"Detects complete autofocus attributes.",
		"Automatically moving focus can disorient users and unexpectedly open virtual keyboards.",
		"https://html.spec.whatwg.org/multipage/interaction.html#the-autofocus-attribute",
		"Remove autofocus and let users choose where to begin interacting.",
		`<input aria-label="Search">`,
		`<input aria-label="Search" autofocus>`,
	),
	htmlMaintainabilityRule(
		"nested-interactive-control", "Interactive control is nested inside another control", shared.SeverityMedium,
		"Detects sequentially focusable elements nested in strict interactive controls.",
		"Nested controls create conflicting activation and focus behavior across browsers and assistive technologies.",
		"https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2",
		"Separate controls into sibling elements with independent actions.",
		`<a href="/details">Details</a><button>Edit</button>`,
		`<a href="/details">Details <button>Edit</button></a>`,
	),
	htmlMaintainabilityRule(
		"aria-hidden-focusable", "ARIA-hidden subtree contains a focusable element", shared.SeverityMedium,
		"Detects aria-hidden=true elements that remain focusable or contain focusable descendants.",
		"Keyboard focus must not move to content that is absent from the accessibility tree.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/6cfa84/",
		"Remove the element from keyboard focus or do not hide it from accessibility APIs.",
		`<div aria-hidden="true"><button tabindex="-1">Hidden action</button></div>`,
		`<div aria-hidden="true"><button>Hidden action</button></div>`,
	),
	htmlMaintainabilityRule(
		"aria-hidden-body", "Document body is hidden from accessibility APIs", shared.SeverityMedium,
		"Detects aria-hidden=true on an explicit body element.",
		"Hiding body removes the entire document from accessibility APIs.",
		"https://www.w3.org/TR/wai-aria-1.2/#aria-hidden",
		"Remove aria-hidden from body and hide only the intended inactive region.",
		`<body><main>Content</main></body>`,
		`<body aria-hidden="true"><main>Content</main></body>`,
	),
	htmlMaintainabilityRule(
		"aria-reference-missing", "ARIA ID reference does not resolve", shared.SeverityMedium,
		"Detects empty or unresolved static ARIA relationship references.",
		"ARIA relationships work only when every static ID reference identifies an element in the same document.",
		"https://www.w3.org/TR/wai-aria-1.2/#attrs_relationships; https://www.w3.org/TR/wai-aria-1.2/",
		"Correct the token list or add the referenced elements with matching IDs.",
		`<button aria-describedby="help">Save</button><p id="help">Stores changes</p>`,
		`<button aria-describedby="missing">Save</button>`,
	),
	htmlMaintainabilityRule(
		"aria-role-invalid", "ARIA role list has no valid concrete role", shared.SeverityMedium,
		"Detects non-empty role attributes containing no valid concrete WAI-ARIA role.",
		"Unknown and abstract roles provide no usable semantic fallback to assistive technologies.",
		"https://www.w3.org/TR/wai-aria-1.2/#role_definitions; https://www.w3.org/TR/html-aria/",
		"Use a valid concrete role appropriate for the element's behavior.",
		`<div role="button" tabindex="0">Save</div>`,
		`<div role="widget">Save</div>`,
	),
	htmlMaintainabilityRule(
		"aria-required-attribute-missing", "ARIA role is missing a required property", shared.SeverityMedium,
		"Detects explicit roles that omit one or more required non-empty ARIA properties.",
		"Required role properties expose the state or relationship necessary to understand and operate a custom widget.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/4e8ab6/",
		"Add all required ARIA properties with meaningful values.",
		`<div role="checkbox" aria-checked="false">Remember me</div>`,
		`<div role="checkbox">Remember me</div>`,
	),
	htmlMaintainabilityRule(
		"role-img-name-missing", "ARIA image is missing an accessible name", shared.SeverityMedium,
		"Detects visible role=img elements without a supported static accessible name.",
		"An element exposed as one image needs a name because descendant content is flattened into that image semantic.",
		"https://www.w3.org/TR/wai-aria-1.2/#img",
		"Add aria-label, aria-labelledby, title, or native img alternative text.",
		`<div role="img" aria-label="Sales increased"></div>`,
		`<div role="img"><span>Sales increased</span></div>`,
	),
	htmlMaintainabilityRule(
		"meta-refresh-used", "Meta refresh requires accessibility review", shared.SeverityMedium,
		"Detects syntactically valid static meta refresh instructions for review.",
		"Refresh behavior depends on the delay and whether the directive refreshes or redirects; this finding requests review and does not by itself assert a WCAG violation.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/bc659a/",
		"Review the delay and navigation behavior, then prefer an HTTP redirect or an explicit user-controlled refresh action when appropriate.",
		`<meta name="description" content="Account overview">`,
		`<meta http-equiv="refresh" content="5;url=/next">`,
	),
	htmlMaintainabilityRule(
		"viewport-zoom-disabled", "Viewport configuration restricts zoom", shared.SeverityMedium,
		"Detects viewport directives that disable scaling or set maximum scale below two.",
		"Users with low vision rely on browser zoom to enlarge content without losing access.",
		"https://www.w3.org/WAI/standards-guidelines/act/rules/b4f0c3/",
		"Remove user-scalable restrictions and allow a maximum scale of at least two.",
		`<meta name="viewport" content="width=device-width, initial-scale=1">`,
		`<meta name="viewport" content="width=device-width, user-scalable=no">`,
	),
	htmlMaintainabilityRule(
		"media-autoplay", "Unmuted media autoplays", shared.SeverityLow,
		"Detects audio and video elements that autoplay without muted.",
		"Unexpected sound interferes with concentration, screen-reader output, and user control.",
		"https://html.spec.whatwg.org/multipage/media.html#attr-media-autoplay",
		"Remove autoplay or combine it with muted and provide playback controls.",
		`<video controls src="intro.mp4"></video>`,
		`<video autoplay src="intro.mp4"></video>`,
	),
	htmlMaintainabilityRule(
		"deprecated-tag", "Deprecated HTML element is used", shared.SeverityLow,
		"Detects obsolete HTML elements outside SVG and MathML.",
		"Obsolete presentational and plugin elements have poor interoperability and should be replaced by semantic HTML and CSS.",
		"https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features",
		"Replace the obsolete element with a current semantic element and CSS.",
		`<p class="notice">Important</p>`,
		`<center>Important</center>`,
	),
	htmlMaintainabilityRule(
		"deprecated-attribute", "Deprecated HTML attribute is used", shared.SeverityLow,
		"Detects element-specific obsolete attributes and conditional legacy attributes.",
		"Legacy presentational and integration attributes make markup harder to maintain and may be ignored by modern user agents.",
		"https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features",
		"Remove the obsolete attribute and use current HTML semantics or CSS.",
		`<p class="centered">Text</p>`,
		`<p align="center">Text</p>`,
	),
}
