package rulecatalog

import (
	"fmt"
	"strings"

	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

// swiftRuleSpec is the frozen #208 inventory. Tests enforce the family counts.
type swiftRuleSpec struct {
	family                                               string
	key, name, cwe, compliant, noncompliant, remediation string
	type_                                                rule.Type
	quality                                              rule.Quality
	severity                                             shared.Severity
	detection                                            rule.Detection
}

func swiftRule(key, name, cwe, compliant, noncompliant, remediation string, typ rule.Type, quality rule.Quality, severity shared.Severity) swiftRuleSpec {
	return swiftRuleSpec{key: key, name: name, cwe: cwe, compliant: compliant, noncompliant: noncompliant, remediation: remediation, type_: typ, quality: quality, severity: severity, detection: rule.DetectionAST}
}

func swiftRules() []rule.Rule {
	bugs := []swiftRuleSpec{
		swiftRule("force-unwrap", "Forced optional unwrap", "CWE-476", "let name = value ?? \"unknown\"", "let name = value!", "Bind the optional safely or provide an explicit fallback.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
		swiftRule("force-try", "Forced throwing call", "CWE-248", "let data = try decoder.decode(Model.self, from: input)", "let data = try! decoder.decode(Model.self, from: input)", "Handle the thrown error instead of forcing the call to succeed.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
		swiftRule("force-cast", "Forced type cast", "CWE-704", "let title = value as? String", "let title = value as! String", "Use a conditional cast and handle values of other types.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("array-index-literal", "Literal array index needs bounds review", "CWE-125", "let first = items.first", "let first = items[0]", "Check collection bounds or use a safe collection API.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("dictionary-force-lookup", "Forced dictionary lookup", "CWE-476", "let token = headers[\"Authorization\"]", "let token = headers[\"Authorization\"]!", "Handle missing keys instead of forcing a dictionary result.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("fatal-error", "Unconditional fatalError call", "CWE-248", "throw AppError.unsupported", "fatalError(\"unsupported\")", "Return an error or handle the unsupported state explicitly.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("precondition-failure", "Unconditional precondition failure", "CWE-248", "guard valid else { throw AppError.invalid }", "preconditionFailure(\"invalid\")", "Use recoverable validation at runtime boundaries.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("try-optional-discard", "Optional result from try? is discarded", "CWE-391", "let saved = try? store.save(record)", "try? store.save(record)", "Inspect the optional result or propagate the error.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("empty-switch-case", "Empty switch case", "CWE-561", "case .idle: return", "case .idle: break", "Implement the case or document an intentional no-op.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("constant-condition", "Constant conditional expression", "CWE-570", "if enabled { run() }", "if true { run() }", "Replace the constant condition with the intended runtime predicate.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("duplicate-switch-case", "Duplicate literal switch case", "CWE-561", "case 1: one()\ncase 2: two()", "case 1: one()\ncase 1: again()", "Remove or merge the repeated case value.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("self-assignment", "Value assigned to itself", "CWE-563", "self.name = name", "name = name", "Assign the intended value or qualify the destination.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("comparison-self", "Value compared with itself", "CWE-570", "if left == right { run() }", "if value == value { run() }", "Compare distinct values or remove the redundant condition.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("invalid-range", "Descending closed range", "CWE-193", "for i in 0...3 { use(i) }", "for i in 3...0 { use(i) }", "Construct ranges with lower bounds before upper bounds.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("integer-division", "Integer division assigned to floating value", "CWE-682", "let ratio = Double(done) / Double(total)", "let ratio = Double(done / total)", "Convert operands before division when a fractional result is required.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("nil-coalescing-self", "Nil coalescing repeats the same value", "CWE-561", "let value = input ?? fallback", "let value = input ?? input", "Use a meaningful fallback or remove the redundant expression.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("redundant-optional-bind", "Optional binding discards bound value", "CWE-398", "if let user = user { greet(user) }", "if let _ = user { greet() }", "Use the bound value or test optional presence directly.", rule.TypeBug, rule.QualityReliability, shared.SeverityInfo),
		swiftRule("unreachable-after-return", "Statement after terminal control flow", "CWE-561", "return result", "return result\nlog(result)", "Remove the unreachable statement or move it before control flow exits.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("empty-catch", "Empty catch block", "CWE-390", "catch { logger.error(\"save failed\") }", "catch { }", "Handle, log, or propagate the caught error.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("return-in-defer", "Control flow in defer", "CWE-584", "defer { close() }", "defer { return }", "Keep defer blocks limited to cleanup.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("assert-production", "Assertion used for runtime validation", "CWE-617", "guard userID != nil else { throw AppError.invalid }", "assert(userID != nil)", "Use explicit error handling for production input validation.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("implicitly-unwrapped-local", "Implicitly unwrapped local optional", "CWE-476", "var token: String?", "var token: String!", "Use an ordinary optional and unwrap it at the point of use.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("optional-equality-nil", "Optional equality used as presence test", "CWE-398", "if value != nil { use(value) }", "if value == Optional.none { use(value) }", "Use nil directly when testing optional presence.", rule.TypeBug, rule.QualityReliability, shared.SeverityInfo),
		swiftRule("guard-without-exit", "Guard body does not exit scope", "CWE-670", "guard ready else { return }", "guard ready else { log() }", "End a guard else body with return, throw, break, or continue.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
		swiftRule("duplicate-dictionary-key", "Duplicate dictionary literal key", "CWE-561", "let flags = [\"debug\": false]", "let flags = [\"debug\": false, \"debug\": true]", "Keep one value for each literal dictionary key.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
	}
	errs := []swiftRuleSpec{
		swiftRule("broad-catch", "Overly broad catch clause", "CWE-396", "catch let error as NetworkError { recover(error) }", "catch { recover() }", "Catch the error types the operation can recover from.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("error-discarded", "Thrown error is ignored", "CWE-391", "try save(record)", "_ = try? save(record)", "Propagate, report, or deliberately handle the error.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("empty-defer", "Empty defer block", "CWE-398", "defer { stream.close() }", "defer { }", "Remove the empty defer or add the required cleanup.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("throw-generic-error", "Generic NSError construction", "", "throw AppError.invalidInput", "throw NSError(domain: \"App\", code: 1)", "Use a typed error that conveys a stable failure contract.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("catch-print-only", "Catch block only prints error", "CWE-391", "catch { logger.error(\"save failed\") }", "catch { print(error) }", "Use structured logging and preserve an error path for callers.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("error-message-lost", "Thrown error loses context", "", "throw AppError.saveFailed(error)", "catch { throw AppError.failed }", "Preserve the underlying error when translating failures.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
	}
	res := []swiftRuleSpec{
		swiftRule("retain-cycle-self", "Strong self captured by stored closure", "CWE-401", "handler = { [weak self] in self?.refresh() }", "handler = { self.refresh() }", "Capture self weakly or unowned when the closure is retained by the object.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("implicitly-unwrapped-optional", "Implicitly unwrapped optional property", "CWE-476", "var delegate: Delegate?", "var delegate: Delegate!", "Use an ordinary optional property and handle absence explicitly.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("notification-observer-unremoved", "Notification observer lifecycle needs review", "CWE-401", "deinit { NotificationCenter.default.removeObserver(self) }", "NotificationCenter.default.addObserver(self, selector: #selector(run), name: nil, object: nil)", "Remove selector-based observers during the owning object lifecycle.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("timer-retain-cycle", "Repeating timer closure captures self", "CWE-401", "Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in self?.tick() }", "Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { _ in self.tick() }", "Capture self weakly in repeating timer closures.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("file-handle-unclosed", "FileHandle lifetime needs explicit closure", "CWE-404", "defer { try? handle.close() }", "let handle = try FileHandle(forReadingFrom: url)", "Close the file handle on every completion path.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("dispatch-source-unbalanced", "Dispatch source lifecycle needs cancellation review", "CWE-404", "source.cancel()", "let source = DispatchSource.makeTimerSource()", "Cancel dispatch sources when their owner stops using them.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("autoreleasepool-missing", "Large Objective-C bridge loop needs autoreleasepool review", "CWE-401", "for item in items { autoreleasepool { process(item) } }", "for item in items { process(item as NSString) }", "Use autoreleasepool around long bridge-heavy loops when profiling confirms growth.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("unsafe-pointer-escape", "Unsafe pointer escapes local scope", "CWE-825", "buffer.withUnsafeBytes { use($0) }", "return UnsafePointer(&value)", "Keep unsafe pointers inside the closure that guarantees storage lifetime.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
	}
	conc := []swiftRuleSpec{
		swiftRule("task-unstructured", "Unstructured Task requires ownership review", "", "let task = Task { await refresh() }", "Task { await refresh() }", "Store, cancel, or otherwise define ownership for unstructured tasks.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("task-sleep-error-discarded", "Task.sleep cancellation is ignored", "CWE-391", "try await Task.sleep(for: .seconds(1))", "try? await Task.sleep(for: .seconds(1))", "Handle cancellation or propagate the sleep error.", rule.TypeBug, rule.QualityReliability, shared.SeverityLow),
		swiftRule("main-queue-sync", "Synchronous dispatch to main queue", "CWE-667", "DispatchQueue.main.async { updateUI() }", "DispatchQueue.main.sync { updateUI() }", "Use asynchronous dispatch or prove the caller is not on the main queue.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("semaphore-wait-main", "Semaphore wait requires main-thread review", "CWE-667", "await operation()", "semaphore.wait()", "Prefer structured concurrency over blocking a thread.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("continuation-resume-missing", "Checked continuation completion needs review", "CWE-667", "withCheckedContinuation { continuation in continuation.resume(returning: value) }", "withCheckedContinuation { continuation in startWork() }", "Resume every continuation on every completion path.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("detached-task-self", "Detached task captures instance state", "CWE-362", "Task { [weak self] in await self?.refresh() }", "Task.detached { self.refresh() }", "Avoid capturing actor- or instance-isolated state in detached tasks.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("actor-blocking-call", "Actor method contains blocking synchronization", "CWE-667", "await service.fetch()", "lock.lock()", "Do not block actor executors; use async coordination.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("lock-with-await", "Await while lock is held", "CWE-667", "lock.lock()\nlet value = state\nlock.unlock()\nawait use(value)", "lock.lock()\nawait refresh()\nlock.unlock()", "Release synchronous locks before suspension points.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
		swiftRule("dispatch-group-wait", "Blocking DispatchGroup wait", "CWE-667", "group.notify(queue: .main) { done() }", "group.wait()", "Use notify or structured concurrency instead of blocking.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("operation-queue-main-block", "OperationQueue main-thread wait", "CWE-667", "queue.addOperation { work() }", "queue.waitUntilAllOperationsAreFinished()", "Avoid synchronously waiting for queued work on UI paths.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
	}
	inj := []swiftRuleSpec{
		swiftRule("sql-concat", "SQL assembled with interpolation", "CWE-89", "query(\"SELECT * FROM users WHERE id = ?\", [id])", "query(\"SELECT * FROM users WHERE id = \\(id)\")", "Bind query parameters instead of embedding values in SQL.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("command-shell", "Shell command string construction", "CWE-78", "process.executableURL = URL(fileURLWithPath: \"/usr/bin/printenv\")\nprocess.arguments = [\"PATH\"]", "let command = input\nlet process = Process()\nprocess.executableURL = URL(fileURLWithPath: \"/bin/sh\")\nprocess.arguments = [\"-c\", command]", "Avoid shell interpreters and pass fixed executable arguments.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("path-concat", "Path assembled from untrusted component", "CWE-22", "let url = base.appendingPathComponent(name)", "let path = base + \"/\" + name", "Validate path components and use URL path APIs.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("url-interpolation", "URL built by interpolation", "CWE-918", "var parts = URLComponents()", "URL(string: \"https://api.example/\\(path)\")", "Use URLComponents and validate untrusted URL parts.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("predicate-format", "NSPredicate format includes interpolation", "CWE-943", "NSPredicate(format: \"name == %@\", name)", "NSPredicate(format: \"name == '\\(name)'\")", "Use predicate format placeholders for dynamic values.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("html-string", "HTML string constructed from interpolation", "CWE-79", "label.text = name", "webView.loadHTMLString(\"<p>\\(name)</p>\", baseURL: nil)", "Encode untrusted data or use a non-HTML rendering API.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("unsafe-deserialization", "Unrestricted NSKeyedUnarchiver decode", "CWE-502", "try NSKeyedUnarchiver.unarchivedObject(ofClass: Model.self, from: data)", "NSKeyedUnarchiver.unarchiveObject(with: data)", "Restrict decoded classes with the secure decoding APIs.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("regex-from-input", "Regular expression created from dynamic input", "CWE-1333", "let regex = try NSRegularExpression(pattern: #\"^[A-Z]+$\"#)", "let regex = try NSRegularExpression(pattern: userPattern)", "Constrain dynamic patterns and set resource limits where available.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityLow),
	}
	crypto := []swiftRuleSpec{
		swiftRule("weak-hash", "Weak cryptographic hash", "CWE-327", "let digest = SHA256.hash(data: data)", "let digest = Insecure.MD5.hash(data: data)", "Use a modern collision-resistant hash such as SHA-256.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("insecure-random", "Non-cryptographic random value in security context", "CWE-338", "var bytes = [UInt8](repeating: 0, count: 32)\nguard SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) == errSecSuccess else { throw AppError.random }", "let sessionToken = random()", "Use Security framework randomness for secrets and tokens.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("ecb-mode", "Electronic codebook cipher mode", "CWE-327", "let sealed = try AES.GCM.seal(data, using: key)", "options: .ecbMode", "Use an authenticated encryption mode such as AES-GCM.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("hardcoded-key", "Hardcoded cryptographic key material", "CWE-321", "let apiKey = try keyStore.loadKey()", "let apiKey = \"0123456789abcdef\"", "Load key material from a protected key store or configuration boundary.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("static-iv", "Static initialization vector", "CWE-329", "let nonce = try AES.GCM.Nonce()", "let iv = Data(repeating: 0, count: 16)", "Generate a unique nonce or IV for every encryption operation.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("tls-trust-all", "Certificate trust evaluation bypass", "CWE-295", "return performDefaultHandling(challenge)", "func receive(_ challenge: URLAuthenticationChallenge) { completionHandler(.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!)) }", "Use platform certificate validation and narrow any exception deliberately.", rule.TypeVulnerability, rule.QualitySecurity, shared.SeverityHigh),
	}
	hotspot := []swiftRuleSpec{
		swiftRule("http-url", "Cleartext HTTP URL", "CWE-319", "URL(string: \"https://example.com\")", "URL(string: \"http://example.com\")", "Use HTTPS for network endpoints.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("ats-disabled", "App Transport Security allows insecure loads", "CWE-319", "<key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><false/></dict>", "<key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><true/></dict>", "Remove broad ATS exceptions and use HTTPS endpoints.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityHigh),
		swiftRule("webview-javascript", "Web view evaluates dynamic JavaScript", "CWE-79", "webView.load(URLRequest(url: url))", "webView.evaluateJavaScript(script)", "Treat dynamic script input as a security boundary and avoid evaluating it.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("pasteboard-sensitive", "Sensitive value copied to pasteboard", "CWE-200", "pasteboard.string = publicLabel", "pasteboard.string = password", "Avoid placing secrets on the system pasteboard.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("keychain-accessible-always", "Keychain item accessible at all times", "CWE-922", "kSecAttrAccessible: kSecAttrAccessibleWhenUnlocked", "kSecAttrAccessible: kSecAttrAccessibleAlways", "Use the least permissive keychain accessibility class.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("biometric-fallback", "Biometric policy fallback needs review", "CWE-287", "let context = LAContext()\ntry context.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: \"Unlock\")", "let context = LAContext()\ntry context.evaluatePolicy(.deviceOwnerAuthentication, localizedReason: \"Unlock\")", "Choose the authentication policy matching the protected operation.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityLow),
		swiftRule("debug-server", "Debug service enabled", "CWE-489", "server.enabled = false", "server.enabled = true", "Disable diagnostic network services in release builds.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("sensitive-log", "Sensitive value sent to log API", "CWE-532", "logger.info(\"signed in\")", "logger.info(\"token: \\(token)\")", "Redact secrets and personal data before logging.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
	}
	api := []swiftRuleSpec{
		swiftRule("print-logging", "Print used for application logging", "", "logger.info(\"started\")", "print(\"started\")", "Use a structured logging API with levels and privacy controls.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("nsurl-legacy", "Legacy NSURL API", "", "let url = URL(string: value)", "let url = NSURL(string: value)", "Use Swift URL value types for new code.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("nsdata-legacy", "Legacy NSData API", "", "let data = Data()", "let data = NSData()", "Use Swift Data for new code.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("nsstring-legacy", "Legacy NSString API", "", "let name: String = value", "let name: NSString = value as NSString", "Use Swift String unless an Objective-C boundary requires NSString.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("dispatch-once", "Deprecated dispatch_once pattern", "", "static let shared = Service()", "dispatch_once(&token) { setup() }", "Use static initialization, which Swift guarantees is lazy and safe.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("uiapplication-openurl", "Deprecated openURL API", "", "UIApplication.shared.open(url)", "UIApplication.shared.openURL(url)", "Use the completion-aware open API.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("string-size", "String length uses UTF-16 bridge", "", "let count = text.count", "let count = (text as NSString).length", "Use String count or explicit Unicode views for the intended unit.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("selector-string", "Selector created from string", "CWE-470", "#selector(Controller.refresh)", "NSSelectorFromString(name)", "Use #selector so compiler checks the referenced method.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityLow),
		swiftRule("perform-selector", "Dynamic selector invocation", "CWE-470", "controller.refresh()", "target.perform(selector)", "Use typed method calls instead of dynamic selector dispatch.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("kvc-string", "Key-value coding with string key", "CWE-470", "model.name = value", "model.setValue(value, forKey: key)", "Prefer typed properties over string-keyed KVC.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityLow),
		swiftRule("notification-string-name", "String notification name", "", "Notification.Name.didRefresh", "Notification.Name(\"didRefresh\")", "Declare notification names as static typed constants.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("userdefaults-sensitive", "Sensitive data stored in UserDefaults", "CWE-922", "try keychain.save(token)", "UserDefaults.standard.set(password, forKey: \"password\")", "Store secrets in Keychain rather than user defaults.", rule.TypeSecurityHotspot, rule.QualitySecurity, shared.SeverityMedium),
		swiftRule("bundle-path", "Bundle resource path used as string", "", "Bundle.main.url(forResource: \"Config\", withExtension: \"json\")", "Bundle.main.path(forResource: \"Config\", ofType: \"json\")", "Use URL-returning resource APIs to preserve path semantics.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("foundation-date-formatter", "DateFormatter allocated at call site", "", "static let formatter = DateFormatter()", "let formatter = DateFormatter()", "Cache formatters when profiling shows repeated formatting cost.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("deprecated-availability", "Deprecated API availability annotation", "", "@available(iOS, introduced: 15)", "@available(iOS, deprecated: 12)", "Migrate callers to the supported replacement API.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
	}
	types := []swiftRuleSpec{
		swiftRule("any-without-protocol", "Unconstrained Any parameter", "", "func render(_ value: Renderable)", "func render(_ value: Any)", "Use a protocol or generic constraint that states the required capability.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("anyobject-cast", "AnyObject downcast requires review", "CWE-704", "if let view = value as? UIView { use(view) }", "let view = value as! UIView", "Use conditional casts at Objective-C bridge boundaries.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("implicitly-unwrapped-parameter", "Implicitly unwrapped optional parameter", "CWE-476", "func show(_ title: String?) {}", "func show(_ title: String!) {}", "Accept an ordinary optional and validate it explicitly.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("raw-value-enum-string", "String literal passed instead of enum case", "", "let method = HTTPMethod.post", "let method = HTTPMethod(rawValue: \"POST\")!", "Use typed enum cases for closed sets of values.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("tuple-return-many", "Large tuple return", "", "struct Result { let value: Int; let name: String }", "func load() -> (Int, String, Bool, Date)", "Return a named type when a result has several fields.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("optional-boolean", "Optional Boolean state", "", "var isEnabled = false", "var isEnabled: Bool?", "Use an enum when state has more than two meaningful values.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("stringly-typed-key", "String literal used as typed key", "", "settings[.theme] = value", "settings[\"theme\"] = value", "Use a typed key or enum for stable settings names.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("type-erasure-cast", "Type-erased value is force cast", "CWE-704", "guard let view = value as? View else { return }", "let view = value as! View", "Preserve generic type information or use a conditional cast.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("objc-dynamic", "Dynamic Objective-C dispatch", "", "final class Store {}", "@objc dynamic var value = 0", "Use dynamic dispatch only when Objective-C runtime behavior is required.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("inout-escaping", "Escaping closure captures inout value", "CWE-825", "mutate(&value) { result in use(result) }", "func work(_ value: inout Int, done: @escaping () -> Void) { done = { use(value) } }", "Do not let inout storage escape the call scope.", rule.TypeBug, rule.QualityReliability, shared.SeverityHigh),
		swiftRule("protocol-composition-long", "Long protocol composition", "", "protocol Service: Cacheable, Sendable {}", "func use(_ value: A & B & C & D)", "Name the composition with a domain protocol.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("metatype-cast", "Runtime metatype cast", "CWE-704", "if let type = value as? Service.Type { use(type) }", "let type = value as! Service.Type", "Validate dynamic metatypes before using them.", rule.TypeBug, rule.QualityReliability, shared.SeverityMedium),
		swiftRule("optional-collection", "Optional collection requires dual-state review", "", "var items: [Item] = []", "var items: [Item]?", "Use an empty collection when absence is not semantically distinct.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("existential-any", "Existential protocol storage", "", "func render<T: Renderable>(_ value: T) {}", "let value: any Renderable", "Use generics when the concrete type should be preserved.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("opaque-result-erased", "Opaque result erased to Any", "", "func make() -> some View { Text(\"Hi\") }", "func make() -> Any { Text(\"Hi\") }", "Keep the result typed with a protocol or opaque return type.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
	}
	perf := []swiftRuleSpec{
		swiftRule("array-contains-loop", "Linear contains lookup inside loop", "", "let known = Set(items)\nfor item in input { if known.contains(item) {} }", "for item in input { if items.contains(item) {} }", "Use a Set when repeated membership checks dominate.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("string-concat-loop", "String concatenation in loop", "", "var parts: [String] = []\nfor item in items { parts.append(item) }", "for item in items { text += item }", "Accumulate parts and join them when building large text.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("map-filter-chain", "Eager map and filter chain", "", "let values = items.lazy.filter(valid).map(transform)", "let values = items.filter(valid).map(transform)", "Use lazy sequences when a long pipeline need not materialize intermediates.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("sort-first", "Sort used to select one value", "", "let best = items.max(by: compare)", "let best = items.sorted(by: compare).first", "Use min or max when only one ordered value is needed.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("count-zero", "Collection count compared with zero", "", "if items.isEmpty { return }", "if items.count == 0 { return }", "Use isEmpty for a direct emptiness check.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("repeated-dateformatter", "DateFormatter allocated repeatedly", "", "static let formatter = DateFormatter()", "func format(_ date: Date) { let formatter = DateFormatter() }", "Reuse formatters when repeated allocation is measurable.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("data-copy", "Unnecessary Data copy", "", "consume(data)", "consume(Data(data))", "Pass existing Data values unless an isolated mutable copy is required.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("main-thread-heavy-loop", "Large loop on main queue requires review", "", "Task.detached { process(items) }", "DispatchQueue.main.async { for item in items { process(item) } }", "Move CPU-heavy work off the main actor or main queue.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
	}
	maint := []swiftRuleSpec{
		swiftRule("cognitive-complexity", "Function cognitive complexity exceeds threshold", "", "func load() { return }", "func load() { if a { for b in c { if d { run() } } } }", "Split nested decisions into focused functions or use guard clauses.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("long-function", "Overly long function", "", "func render() {\n"+strings.Repeat("title()\n", 50)+"}", "func render() {\n"+strings.Repeat("title()\n", 51)+"}", "Extract cohesive sections into named functions.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("large-type", "Type has many members", "", "struct User {\n"+strings.Repeat("var id = 0\n", 40)+"}", "struct User {\n"+strings.Repeat("var id = 0\n", 41)+"}", "Split the type along domain responsibilities.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("deep-nesting", "Deeply nested control flow", "", "func render() { if a { if b { if c { if d { run() } } } } }", "func render() { if a { if b { if c { if d { if e { run() } } } } } }", "Flatten control flow with guards and extracted helpers.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityMedium),
		swiftRule("too-many-parameters", "Function has too many parameters", "", "func connect(host: String, port: Int) {}", "func connect(a: String, b: String, c: String, d: String, e: String, f: String, g: String, h: String) {}", "Group related inputs into a value type.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("todo-comment", "Pending work marker", "", "// Explain an invariant here", "// TODO: replace this", "Resolve the pending work or record it in issue tracking.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("commented-code", "Commented-out code", "", "// Explain why this branch exists", "// let legacy = oldValue()", "Remove dead code and rely on version control for history.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("magic-number", "Unexplained numeric literal", "", "let retryLimit = 3", "if attempts > 3 { stop() }", "Name domain-significant numeric values.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("single-letter-name", "Single-letter declaration name", "", "let userID = value", "let x = userID", "Use descriptive names outside conventional short scopes.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
		swiftRule("public-undocumented", "Public declaration lacks documentation", "", "/// Loads the current profile.\npublic func load() {}", "public func load() {}", "Document public behavior, parameters, and failure modes.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityLow),
		swiftRule("redundant-self", "Redundant self qualification", "", "name = value", "self.name = value", "Remove self when Swift can resolve the member unambiguously.", rule.TypeCodeSmell, rule.QualityMaintainability, shared.SeverityInfo),
	}
	families := map[string][]swiftRuleSpec{"bugs": bugs, "err": errs, "res": res, "conc": conc, "inj": inj, "crypto": crypto, "hotspot": hotspot, "api": api, "types": types, "perf": perf, "maint": maint}
	var specs []swiftRuleSpec
	for _, family := range []string{"bugs", "err", "res", "conc", "inj", "crypto", "hotspot", "api", "types", "perf", "maint"} {
		for i := range families[family] {
			families[family][i].family = family
		}
		specs = append(specs, families[family]...)
	}
	rules := make([]rule.Rule, 0, len(specs))
	for _, s := range specs {
		detection := s.detection
		if s.key == "ats-disabled" {
			detection = rule.DetectionParse
		}
		if s.key == "cognitive-complexity" {
			detection = rule.DetectionMetric
		}
		rules = append(rules, rule.Rule{
			Key: rule.Key("swift:" + s.key), Name: s.name, Language: "Swift", Type: s.type_, Qualities: []rule.Quality{s.quality}, DefaultSeverity: s.severity,
			Tags: []string{"swift", "swift-" + s.family, "swift-" + strings.ReplaceAll(s.key, ":", "-")}, CWE: optionalCWE(s.cwe), OWASP: []string{},
			Description: swiftDescription(s),
			Rationale:   swiftRationale(s),
			Remediation: s.remediation, CompliantExample: s.compliant, NoncompliantExample: s.noncompliant, RemediationEffort: swiftEffort(s), Detection: detection,
		})
	}
	return rules
}

func swiftDescription(s swiftRuleSpec) string {
	shape := map[string]string{
		"force-unwrap": "a postfix ! optional unwrap", "force-try": "a try! expression", "force-cast": "an as! cast", "array-index-literal": "a literal numeric subscript", "dictionary-force-lookup": "a force-unwrapped string-key subscript", "fatal-error": "a fatalError call", "precondition-failure": "a preconditionFailure call", "try-optional-discard": "a standalone try? expression", "empty-switch-case": "a switch case whose body is break", "constant-condition": "an if or while condition written as true or false", "duplicate-switch-case": "a repeated literal switch label", "self-assignment": "an identifier assigned to itself", "comparison-self": "an identifier compared with itself", "invalid-range": "a descending integer closed range", "integer-division": "integer division passed to a floating conversion", "nil-coalescing-self": "the same identifier on both sides of ??", "redundant-optional-bind": "an if let _ binding", "unreachable-after-return": "a statement immediately following terminal control flow", "empty-catch": "a catch block with no body", "return-in-defer": "terminal control flow inside defer", "assert-production": "an assert call", "implicitly-unwrapped-local": "a local declaration with ! optional syntax", "optional-equality-nil": "a comparison against Optional.none", "guard-without-exit": "a guard else body without a visible exit keyword", "duplicate-dictionary-key": "a dictionary literal with repeated string keys",
		"broad-catch": "an untyped catch block", "error-discarded": "_ = try?", "empty-defer": "a defer block with no statements", "throw-generic-error": "throw NSError(...)", "catch-print-only": "a catch body consisting only of print(error)", "error-message-lost": "a catch that throws without mentioning error",
		"retain-cycle-self": "a stored closure assignment that captures self strongly", "implicitly-unwrapped-optional": "a property declared with ! optional syntax", "notification-observer-unremoved": "a selector-based NotificationCenter observer registration", "timer-retain-cycle": "a repeating Timer closure capturing self strongly", "file-handle-unclosed": "a FileHandle construction", "dispatch-source-unbalanced": "a DispatchSource.make call", "autoreleasepool-missing": "a bridge-heavy for loop lacking autoreleasepool", "unsafe-pointer-escape": "a return of UnsafePointer(...) from a local value",
		"task-unstructured": "an unassigned Task { ... } call", "task-sleep-error-discarded": "try? Task.sleep", "main-queue-sync": "DispatchQueue.main.sync", "semaphore-wait-main": "a semaphore.wait call", "continuation-resume-missing": "a withCheckedContinuation closure without continuation.resume", "detached-task-self": "Task.detached whose closure mentions self", "actor-blocking-call": "an actor declaration containing lock or wait calls", "lock-with-await": "await between lock() and unlock() statements", "dispatch-group-wait": "a DispatchGroup wait call", "operation-queue-main-block": "waitUntilAllOperationsAreFinished",
		"sql-concat": "a SQL-like string interpolation passed to a query sink", "command-shell": "a locally declared command passed to Process with sh -c", "path-concat": "string concatenation assigned to a path or URL name", "url-interpolation": "URL(...) with string interpolation", "predicate-format": "NSPredicate(format:) with interpolation", "html-string": "loadHTMLString with interpolation", "unsafe-deserialization": "NSKeyedUnarchiver.unarchiveObject", "regex-from-input": "NSRegularExpression with a nonliteral pattern",
		"weak-hash": "an MD5 or SHA-1 API", "insecure-random": "a random() call assigned to a sensitive name", "ecb-mode": "an .ecbMode argument", "hardcoded-key": "a sensitive local name initialized from a string literal", "static-iv": "constant Data assigned or passed as an IV or nonce", "tls-trust-all": "unconditional URLCredential trust handling",
		"http-url": "an http:// literal in a URL call", "ats-disabled": "an NSAllowsArbitraryLoads key set to true within NSAppTransportSecurity", "webview-javascript": "evaluateJavaScript", "pasteboard-sensitive": "a sensitive value assigned to pasteboard.string", "keychain-accessible-always": "kSecAttrAccessibleAlways", "biometric-fallback": "LAContext.evaluatePolicy using .deviceOwnerAuthentication", "debug-server": "server.enabled = true", "sensitive-log": "a logging call mentioning a sensitive name",
		"print-logging": "print, debugPrint, NSLog, or os_log", "nsurl-legacy": "NSURL(...) construction", "nsdata-legacy": "NSData(...) construction", "nsstring-legacy": "NSString conversion", "dispatch-once": "dispatch_once", "uiapplication-openurl": ".openURL", "string-size": "NSString.length", "selector-string": "NSSelectorFromString", "perform-selector": ".perform", "kvc-string": ".setValue(..., forKey:)", "notification-string-name": "Notification.Name with a string literal", "userdefaults-sensitive": "UserDefaults.standard.set of a sensitive name", "bundle-path": "Bundle path(forResource:)", "foundation-date-formatter": "DateFormatter()", "deprecated-availability": "@available(... deprecated: ...)",
		"any-without-protocol": "a function parameter typed Any", "anyobject-cast": "an AnyObject as! cast", "implicitly-unwrapped-parameter": "a parameter declared with ! optional syntax", "raw-value-enum-string": "HTTPMethod(rawValue:) with a string literal", "tuple-return-many": "a function return tuple with four or more elements", "optional-boolean": "a Bool? property", "stringly-typed-key": "a string-literal settings or config subscript", "type-erasure-cast": "a View as! cast", "objc-dynamic": "@objc dynamic", "inout-escaping": "an inout parameter captured by an escaping closure", "protocol-composition-long": "a type annotation composing four protocols", "metatype-cast": "a .Type as! cast", "optional-collection": "an optional collection property", "existential-any": "a type annotation containing any", "opaque-result-erased": "a function returning Any",
		"array-contains-loop": "Array.contains inside a loop", "string-concat-loop": "text += inside a loop", "map-filter-chain": "an eager filter(...).map(...) chain", "sort-first": "sorted(...).first", "count-zero": "a .count comparison with zero", "repeated-dateformatter": "DateFormatter() inside a function", "data-copy": "Data(data)", "main-thread-heavy-loop": "a for loop nested in DispatchQueue.main",
		"cognitive-complexity": "a function whose computed cognitive score exceeds the configured threshold", "long-function": "a function body with more than 50 statements", "large-type": "a type body with more than 40 members", "deep-nesting": "control flow nested beyond four levels", "too-many-parameters": "a function declaration with eight or more parameters", "todo-comment": "a comment containing TODO:", "commented-code": "a comment beginning with a Swift statement", "magic-number": "an integer literal greater than one in a comparison", "single-letter-name": "a local declaration with a one-character name", "public-undocumented": "a public declaration without immediately preceding /// documentation", "redundant-self": "self.member where the member is stored and unambiguous",
	}[s.key]
	return fmt.Sprintf("Reports %s. It inspects only that local syntax or metric and does not prove the surrounding runtime path, ownership, input trust, or intent.", shape)
}

func swiftRationale(s swiftRuleSpec) string {
	reason := map[string]string{
		"force-unwrap": "An absent optional terminates execution at the unwrap site.", "force-try": "A thrown failure terminates execution instead of reaching recovery code.", "force-cast": "A value of another runtime type terminates execution.", "array-index-literal": "The literal may exceed a collection's runtime bounds.", "dictionary-force-lookup": "A missing key turns a normal lookup into a trap.", "fatal-error": "Production input can reach an unrecoverable termination.", "precondition-failure": "Recoverable external state should not terminate the process.", "try-optional-discard": "The failed operation becomes invisible to callers.", "empty-switch-case": "A case can silently skip required work.", "constant-condition": "A branch is permanently enabled or unreachable.", "duplicate-switch-case": "Repeated labels make intended case handling unclear.", "self-assignment": "The apparent update preserves stale state.", "comparison-self": "The predicate is constant for ordinary values.", "invalid-range": "The range traps because its lower bound exceeds its upper bound.", "integer-division": "The fractional portion is lost before conversion.", "nil-coalescing-self": "The fallback cannot change the result.", "redundant-optional-bind": "The binding obscures a plain presence test.", "unreachable-after-return": "The following statement cannot run.", "empty-catch": "Failure is suppressed without a recovery decision.", "return-in-defer": "Cleanup blocks should not obscure control flow.", "assert-production": "Assertions can be disabled and are not input validation.", "implicitly-unwrapped-local": "Later use can trap when initialization is absent.", "optional-equality-nil": "The verbose form obscures the intended presence check.", "guard-without-exit": "A guard must transfer control when its condition fails.", "duplicate-dictionary-key": "One literal value masks another.",
		"broad-catch": "An untyped catch can recover from failures it does not understand.", "error-discarded": "Callers lose the failed operation's signal.", "empty-defer": "The cleanup marker adds no behavior.", "throw-generic-error": "Untyped NSError construction weakens a stable application error contract.", "catch-print-only": "Console output is not a caller-visible recovery path.", "error-message-lost": "Discarding the underlying error removes diagnostic context.",
		"retain-cycle-self": "The owner and its stored closure can retain each other indefinitely.", "implicitly-unwrapped-optional": "Property access can trap before lifecycle setup completes.", "notification-observer-unremoved": "Observer lifetime is hard to verify from registration alone.", "timer-retain-cycle": "A repeating timer can keep its owner alive.", "file-handle-unclosed": "The local construction does not show every close path.", "dispatch-source-unbalanced": "Source cancellation is an ownership obligation outside the constructor call.", "autoreleasepool-missing": "Bridged temporary objects can accumulate across a long loop.", "unsafe-pointer-escape": "The returned pointer can outlive its referenced storage.",
		"task-unstructured": "An unowned task can outlive the work that started it.", "task-sleep-error-discarded": "Cancellation of sleep is silently ignored.", "main-queue-sync": "Calling it from the main queue deadlocks; the local call cannot prove the caller.", "semaphore-wait-main": "Blocking can freeze UI work, though thread context is not proven locally.", "continuation-resume-missing": "A checked continuation that never resumes leaves its awaiting task suspended.", "detached-task-self": "Detached work can violate actor or object isolation.", "actor-blocking-call": "Blocking an actor executor delays isolated work.", "lock-with-await": "Suspension while holding a synchronous lock can block other callers.", "dispatch-group-wait": "Waiting synchronously consumes a thread instead of scheduling completion.", "operation-queue-main-block": "A UI-path wait can stall responsiveness, but the local call cannot prove that path.",
		"sql-concat": "Interpolated data can change a SQL command's meaning.", "command-shell": "A shell interprets data as command syntax.", "path-concat": "Unchecked components can escape the intended path.", "url-interpolation": "A dynamic URL part can redirect a request to an unintended destination.", "predicate-format": "Interpolated predicate text changes the expression language.", "html-string": "Interpolated HTML can execute or render unintended content.", "unsafe-deserialization": "Unrestricted decoding accepts classes beyond the intended model.", "regex-from-input": "Unbounded patterns can consume excessive matching time.",
		"weak-hash": "MD5 and SHA-1 no longer provide modern collision resistance.", "insecure-random": "Predictable randomness is unsuitable for secret material.", "ecb-mode": "ECB reveals repeated plaintext patterns.", "hardcoded-key": "Embedded key material is exposed to source and binary readers.", "static-iv": "Nonce reuse can compromise encryption security.", "tls-trust-all": "Bypassing normal trust evaluation permits impostor certificates.",
		"http-url": "Cleartext transport can expose or alter traffic.", "webview-javascript": "Dynamic script evaluation crosses a code-execution boundary.", "pasteboard-sensitive": "Other apps or users may read the shared pasteboard.", "keychain-accessible-always": "The item remains available more broadly than necessary.", "biometric-fallback": "The fallback policy changes the authentication assurance.", "debug-server": "Release diagnostics can expose an unintended network surface.", "sensitive-log": "Logs can persist credentials beyond their intended lifetime.",
		"print-logging": "Print lacks structured levels and privacy controls.", "nsurl-legacy": "Legacy reference types obscure modern Swift value semantics.", "nsdata-legacy": "Legacy reference types add bridging overhead.", "nsstring-legacy": "UTF-16 length can differ from Swift character count.", "dispatch-once": "Swift static initialization already provides safe lazy setup.", "uiapplication-openurl": "The newer API exposes completion and options.", "string-size": "UTF-16 units may not match the intended text unit.", "selector-string": "String selectors bypass compiler checking.", "perform-selector": "Dynamic dispatch defers method validation to runtime.", "kvc-string": "String keys can fail after refactoring.", "notification-string-name": "Ad hoc names make notification use harder to find.", "userdefaults-sensitive": "UserDefaults is not a credential store.", "bundle-path": "String paths lose URL operations and semantics.", "foundation-date-formatter": "Fresh formatters can add repeated setup cost.", "deprecated-availability": "Deprecated APIs accumulate migration debt.",
		"any-without-protocol": "Any hides the capability the function actually needs.", "anyobject-cast": "A failed bridge downcast traps.", "implicitly-unwrapped-parameter": "A nil argument can trap at use.", "raw-value-enum-string": "A misspelled raw value fails at runtime.", "tuple-return-many": "Unnamed fields become hard to read and extend.", "optional-boolean": "Three states require callers to infer semantics.", "stringly-typed-key": "Typos in keys evade compiler checking.", "type-erasure-cast": "Erased type information is recovered with a trapping cast.", "objc-dynamic": "Dynamic dispatch weakens static optimization and checking.", "inout-escaping": "Escaped inout storage violates its call-scoped lifetime.", "protocol-composition-long": "Repeated compositions hide a reusable domain abstraction.", "metatype-cast": "A metatype mismatch traps.", "optional-collection": "Nil and empty force callers to handle two states.", "existential-any": "Existential storage can hide concrete type requirements.", "opaque-result-erased": "Returning Any loses the result's protocol contract.",
		"array-contains-loop": "Repeated linear searches multiply loop cost.", "string-concat-loop": "Repeated concatenation can repeatedly copy growing text.", "map-filter-chain": "Eager chains materialize intermediate collections.", "sort-first": "Sorting all values costs more than selecting one.", "count-zero": "isEmpty states the intent directly.", "repeated-dateformatter": "Formatter setup can dominate small formatting calls.", "data-copy": "Copying Data can allocate without changing ownership needs.", "main-thread-heavy-loop": "CPU work on the main queue can delay UI events, but loop cost is not measured locally.",
		"cognitive-complexity": "Nested decisions raise the effort required to reason about every path.", "long-function": "Large bodies mix responsibilities and resist focused tests.", "large-type": "Many members suggest multiple responsibilities.", "deep-nesting": "Nested branches obscure the active path.", "too-many-parameters": "Long parameter lists invite ordering mistakes.", "todo-comment": "Untracked pending work can survive indefinitely.", "commented-code": "Version control preserves old code without leaving dead text.", "magic-number": "Unnamed thresholds hide domain meaning.", "single-letter-name": "Short names outside small scopes reduce review clarity.", "public-undocumented": "Public callers need the behavior and failure contract.", "redundant-self": "Unneeded qualification adds visual noise.",
	}[s.key]
	source := "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/"
	if s.cwe != "" {
		source = "https://cwe.mitre.org/data/definitions/" + strings.TrimPrefix(s.cwe, "CWE-") + ".html"
	}
	switch s.family {
	case "conc":
		source = "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/"
	case "crypto":
		source = "https://developer.apple.com/documentation/cryptokit"
	case "hotspot":
		source = "https://developer.apple.com/documentation/security"
	case "api", "perf":
		source = "https://developer.apple.com/documentation/foundation"
	}
	switch s.key {
	case "ats-disabled":
		source = "https://developer.apple.com/documentation/bundleresources/information-property-list/nsapptransportsecurity"
	case "biometric-fallback":
		source = "https://developer.apple.com/documentation/localauthentication/lacontext/evaluatepolicy(_:localizedreason:reply:)"
	case "insecure-random":
		source = "https://developer.apple.com/documentation/security/secrandomcopybytes(_:_:_:)"
	case "hardcoded-key":
		source = "https://developer.apple.com/documentation/security/keychain-services"
	case "static-iv":
		source = "https://developer.apple.com/documentation/cryptokit/aes/gcm"
	}
	return fmt.Sprintf("%s\n\nSource: %s", reason, source)
}

func swiftEffort(s swiftRuleSpec) int {
	switch s.family {
	case "inj", "crypto":
		return 60
	case "conc", "res":
		return 30
	case "hotspot":
		return 30
	case "maint", "api", "perf":
		return 5
	default:
		return 15
	}
}
