package rulecatalog

import (
	"strings"

	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func textRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "text:bidi-unicode",
			Name:                "Bidi Unicode control character",
			Language:            "Text",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"text", "security", "injection", "bidi"},
			CWE:                 []string{"CWE-1007"},
			OWASP:               []string{},
			Description:         "Detects Unicode bidirectional control characters that can disguise malicious code by reversing or reordering displayed text.",
			Rationale:           "Bidi control characters (LRO, RLO, LRE, RLE, LRI, RLI, FSI, PDI, ALM, LRM, RLM) can visually reorder source code so that what appears benign to a reviewer is actually dangerous when compiled or interpreted.\n\nSource: https://trojansource.codes/trojan-source.pdf",
			Remediation:         "Remove all bidirectional control characters from source files. If text directionality is needed, use explicit markup or formatting rather than embedded Unicode controls.",
			CompliantExample:    "if (admin) grant_access();",
			NoncompliantExample: "if " + string(rune(0x202E)) + "admin" + string(rune(0x200E)) + " grant_access();",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:invisible-unicode",
			Name:                "Invisible Unicode format character",
			Language:            "Text",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"text", "security", "unicode", "invisible"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects invisible Unicode format characters (category Cf) that can be used to hide malicious content or confuse code reviewers.",
			Rationale:           "Unicode format control characters (other than bidi controls reported separately) are zero-width or otherwise invisible and can be inserted into source code to alter parsing or disguise payloads.\n\nSource: https://unicode.org/reports/tr36/",
			Remediation:         "Remove all invisible format characters from source files unless they serve a documented and intentional purpose.",
			CompliantExample:    "config = read()",
			NoncompliantExample: "config" + string(rune(0x00AD)) + " = read()",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:utf8-bom",
			Name:                "UTF-8 BOM at start of file",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"text", "maintainability", "encoding", "bom"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects a UTF-8 byte order mark (BOM) at the beginning of a file.",
			Rationale:           "A leading UTF-8 BOM (EF BB BF) is unnecessary because UTF-8 has no byte-order ambiguity. Many tools and parsers treat it as content rather than metadata, which can cause unexpected errors.\n\nSource: https://unicode.org/faq/utf_bom.html",
			Remediation:         "Remove the BOM or configure your editor to save without it.",
			CompliantExample:    "hello world",
			NoncompliantExample: "\xEF\xBB\xBF" + "hello world",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:mixed-line-endings",
			Name:                "Mixed line endings in file",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"text", "maintainability", "line-endings"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects files that contain more than one style of line ending (CRLF, bare LF, or bare CR).",
			Rationale:           "Mixed line endings cause inconsistent diffs, break tools that expect a single convention, and create spurious whitespace changes. Normalize to one style per project using an editorconfig or formatter setting.\n\nSource: https://spec.editorconfig.org/",
			Remediation:         "Normalize all line endings to a single convention (LF or CRLF) using an editorconfig or formatter setting.",
			CompliantExample:    "line one\nline two\nline three\n",
			NoncompliantExample: "line one\nline two\r\nline three\r\n",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:trailing-whitespace",
			Name:                "Trailing whitespace",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"text", "maintainability", "whitespace"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects trailing ASCII spaces or tabs at the end of a line.",
			Rationale:           "Trailing whitespace creates noisy diffs, can cause subtle issues in some formats, and is invisible in most editors. An exception is made for exactly two trailing spaces before a newline in Markdown files, which signals a hard line break.\n\nSource: https://spec.commonmark.org/0.31.2/#hard-line-breaks",
			Remediation:         "Configure your editor to strip trailing whitespace on save.",
			CompliantExample:    "clean line",
			NoncompliantExample: "dirty line" + strings.Repeat(" ", 3),
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:oversized-file",
			Name:                "Text file exceeds 1 MiB",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"text", "maintainability", "size"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects text files larger than 1 MiB.",
			Rationale:           "Very large text files are difficult to review in code review tools and slow down editors. The 1 MiB threshold is a Synapse policy threshold and is not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:         "Split large files into smaller, logically scoped units or move generated content out of the source tree.",
			CompliantExample:    "small file content",
			NoncompliantExample: strings.Repeat("a", 200),
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:missing-final-newline",
			Name:                "Missing final newline",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"text", "maintainability", "newline"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects non-empty text files that do not end with a line terminator.",
			Rationale:           "POSIX defines a line as ending with a newline character. Files missing a final newline cause concatenation errors and break many text-processing tools.\n\nSource: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html",
			Remediation:         "Add a final newline to the file. Configure your editor to insert final newlines automatically.",
			CompliantExample:    "last line\n",
			NoncompliantExample: "last line without newline",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "text:overlong-line",
			Name:                "Line exceeds 200 Unicode runes",
			Language:            "Text",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"text", "maintainability", "line-length"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects physical lines longer than 200 Unicode runes.",
			Rationale:           "Very long lines are harder to read, review, and diff. The 200-rune threshold is a Synapse policy threshold and is not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:         "Break long lines into multiple shorter lines using appropriate line-continuation syntax.",
			CompliantExample:    "short line",
			NoncompliantExample: strings.Repeat("a", 201),
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
	}
}
